### ISSUE TITLE
Forced 16:9 aspect ratio

### ISSUE THREAD

**Issue by Bruh-Man14** [jmir1/aniyomi#1004]
### Steps to reproduce

Watching anime with aspect ratios other than 16:9

### Expected behavior

Maintain original aspect ratio

### Actual behavior

When watching anime which is in 4:3 ratio, it gets stretched out

### Aniyomi version

0.12.3.10

### Android version

Android 11

### Device

Samsung Galaxy A30s

### Other details

I dont know if it is a decision to force it but it makes anime uncomfortable to watch

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/jmir1/aniyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://aniyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.12.3.10](https://github.com/jmir1/aniyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by Bruh-Man14** [comment]
I did not realize it was my mistake. Please ignore this issue. Though I must add its not easy to notice you can change aspect ratio.

**Comment by josefredohd** [comment]
@Bruh-Man14 How do you change the aspect ratio?

**Comment by Bruh-Man14** [comment]
@josefredohd in the player. In the controls at the bottom of the screen there is a square and clicking it once or twice should make it automatic and better ![Screenshot_20231111-075159_Aniyomi.jpg](https://github.com/aniyomiorg/aniyomi/assets/112637743/2ff2953d-ef4a-4c5c-9eae-34a92870da3f)
This should help

**Comment by josefredohd** [comment]
@Bruh-Man14 Thank you so much!!
