### ISSUE TITLE
Sorting by "Latest Chapter" causes all anime to disappear from library

### ISSUE THREAD

**Issue by nameless** [jmir1/aniyomi#104]
### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/jmir1/aniyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to the **[latest version](https://github.com/jmir1/aniyomi/releases)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

### Aniyomi version

Stable 0.11.1.10 

### Android version

Android 10

### Device

Note 9

### Steps to reproduce

1. Sort by Latest Chapter (happens on Total Chapters too)
2. Switch to manga library and back to anime library
3. Anime poof

### Expected behavior

It should be sorting it by latest aired episode

### Actual behavior

Anime in library disappear until you switch sorting methods

### Other details

I know it says "latest chapters" instead of episodes which is why I thought that maybe it was less of a bug and more of the feature wasnt yet made for anime section when it was forked from the Tachiyomi. But I still reported it as a bug anyway just in case

**Comment by Ugaog123** [comment]
Exactly what happened to me which made me think it was a glitch so I just did a fresh install to fix which it didnt

**Comment by jmir1** [comment]
closed by 520499f7d0029e201454b9600b7050243dd8fbd7
