### ISSUE TITLE
Include anime data for backups

### ISSUE THREAD

**Issue by Ugaog123** [jmir1/aniyomi#106]
### Acknowledgements

- [x] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/jmir1/aniyomi-extensions/issues/new/choose).
- [X] I have updated the app to the **[latest version](https://github.com/jmir1/aniyomi/releases)**.
- [X] I will fill out all of the requested information in this form.

### Describe your suggested feature

Include anime data and tracking in the backup/restore feature as I had to do it manually after reinstalling aniyomi despite making the backup file within aniyomi.

**Comment by jmir1** [comment]
this feature already exists.
