### ISSUE TITLE
Need new extensions for Anime 

### ISSUE THREAD

**Issue by Rohan-Somadder** [jmir1/aniyomi#108]
### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/jmir1/aniyomi-extensions/issues/new/choose).
- [X] I have updated the app to the **[latest version](https://github.com/jmir1/aniyomi/releases)**.
- [X] I will fill out all of the requested information in this form.

### Describe your suggested feature

As of now, the manga extensions almost cover all the popular ones like MangaDex, MangaSee, MangaLife, Mangakakalots, etc. But the **anime has only 4**, and with the recent shutdown of **4anime.to** there is one less for the anime but also the remaining of them also don't have all of the animes. So it will be appreciated if a new anime extension is added like **animixplay**, **zoro.to**, **9anime**, or others.

**Comment by swaggoose** [comment]
I think zoro or 9anime should be the new extension.

**Comment by conztanz045** [comment]
Animekisa

**Comment by MetalBabe420** [comment]
I know there's some anime on there but kimcartoon.to is a good one

**Comment by jmir1** [comment]
https://github.com/jmir1/aniyomi-extensions.
