### ISSUE TITLE
Gogoanime extension not allowing downloads

### ISSUE THREAD

**Issue by Rohan-Somadder** [jmir1/aniyomi#109]
### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/jmir1/aniyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to the **[latest version](https://github.com/jmir1/aniyomi/releases)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

### Aniyomi version

Preview r3817

### Android version

Android 8.1

### Device

Motorola G5 s Plus

### Steps to reproduce

1. Download any episode from any anime from the gogoanime extension
2. The download just completes in an instant.
2. It refuses to play in any player be it internal or external 

### Expected behavior

After the downloading of any episode the video should play as normal.

### Actual behavior

But it stays in some intermediate state where the video keeps loading and the total time keeps shifting from the original time and 0.

### Other details

https://photos.google.com/photo/AF1QipPg3L-4VPTVO3l-y7mKdAcHItVBo5cja4en5pd1
https://photos.google.com/photo/AF1QipOwPtiYin6EUbHR1CVMkzXN1Bh8smBe8o9ZqFkP
https://photos.google.com/photo/AF1QipNV3lbbDKWiBSKVG__xITxoJy41HI8Atgq2Cdpl

**Comment by Retro410** [comment]
Same here, it keeps happening with all anime extension!!

**Comment by Felixkoolkid** [comment]
Same with me

**Comment by Beast711** [comment]
Same with me

**Comment by tohrukobayashii** [comment]
Same

**Comment by AscendeDDemoN** [comment]
Is anyone has same issue of http error 403 on gogoanime

**Comment by ColorlessKing25** [comment]
Same for me
