### ISSUE TITLE
An option to migrate anime list from mal into library

### ISSUE THREAD

**Issue by Koupla** [jmir1/aniyomi#113]
### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/jmir1/aniyomi-extensions/issues/new/choose).
- [X] I have updated the app to the **[latest version](https://github.com/jmir1/aniyomi/releases)**.
- [X] I will fill out all of the requested information in this form.

### Describe your suggested feature

Being able to get your anime list and having it added to your app library

**Comment by jmir1** [comment]
Probably not
