### ISSUE TITLE
Control video player using tv remote

### ISSUE THREAD

**Issue by FrixBOX** [jmir1/aniyomi#114]
### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/jmir1/aniyomi-extensions/issues/new/choose).
- [X] I have updated the app to the **[latest version](https://github.com/jmir1/aniyomi/releases)**.
- [X] I will fill out all of the requested information in this form.

### Describe your suggested feature

i've tested aniyomi preview on android tv. It's working fine but inability to control video player using remote control is really annoying i need to use mouse to control video player.

**Comment by jmir1** [comment]
#162 is the same, closing this to avoid clutter
