### ISSUE TITLE
UI Bars not disappering when previewing manga/anime in updates tab.

### ISSUE THREAD

**Issue by WH1T3No1SE** [jmir1/aniyomi#116]
### Aniyomi version

0.11.1.11

### Android version

8.1

### Device

Oppo AX7

### Steps to reproduce

1. Go to Updates tab
2. Tap on Thumbnail of Manga/Anime (not text) to see the description of the manga

### Expected behavior

Bottom navigation bar and top Anime/Manga bar should not be visible.

### Actual behavior

Bottom navigation bar and top Anime/Manga bar are visible.
Bottom navigation bar obscures buttons for actions when you hold down select chapters.
![Screenshot_2021-07-23-19-08-11-52](https://user-images.githubusercontent.com/48910598/126817650-26b2063b-83ea-40e3-b65d-1a867ee31f35.jpg)

**Comment by jmir1** [comment]
Fixed by 940c4cfabf3322ebc67c3770d3bf11518c43f756
