### ISSUE TITLE
[Bug] gogoanime.tv: cannot stream nor download 

### ISSUE THREAD

**Issue by 69DUCKMYSICK69** [jmir1/aniyomi#122]
### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/jmir1/aniyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to the **[latest version](https://github.com/jmir1/aniyomi/releases)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

### Aniyomi version

0.11.1.11

### Android version

11

### Device

S10+

### Steps to reproduce

1. Open gogoanime.tv extension library
2. Click on any anime to watch
3. Click on an episode
4. Click download

### Expected behavior

Start the episode or download it

### Actual behavior

Crashes the app and if you try the download it crashes saying list empty

### Crash logs

[tachiyomi_crash_logs.txt](https://github.com/jmir1/aniyomi/files/6890000/tachiyomi_crash_logs.txt)

**Comment by Saitashun** [comment]
I also have the same issue and came to report this bug

**Comment by MrUNKNOWNN7** [comment]
I'm also facing the same issue. Whenever I am trying to watch an anime, the app gets crashed. Manga is working fine though.

**Comment by Bawalian** [comment]
Other extensions are working fine only gogoanime is crashing. Use other extension to watch anime then the app will work properly 😉.

**Comment by Saitashun** [comment]
Yeah other extensions are working but gogoanime have a lot anime which is
not there in other extensions and the extentions are limited to

**Comment by Saitashun** [comment]
So I would like u to fix this bug please..

**Comment by VashTheStampede0** [comment]
Bruh, this happens often , you have noticed it just now?

**Comment by Saitashun** [comment]
I started using this recently....

**Comment by 69DUCKMYSICK69** [comment]
Same i just discovered the app this week so i'm still new to it

**Comment by jmir1** [comment]
just fyi, open all extension related issues in jmir1/aniyomi-extensions
it's also fixed now.

**Comment by Saitashun** [comment]
Thanks for fixing the bug... It made my day realy thanx
