### ISSUE TITLE
anime servers to spanish language please

### ISSUE THREAD

**Issue by Rochiexbm** [jmir1/aniyomi#124]
### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/jmir1/aniyomi-extensions/issues/new/choose).
- [X] I have updated the app to the **[latest version](https://github.com/jmir1/aniyomi/releases)**.
- [X] I will fill out all of the requested information in this form.

### Describe your suggested feature

I have been using the application for a long time Tachiyomi is the best manga app in Spanish and just to think that now I could watch anime and manga at the same time is this app that is very comfortable, we would really appreciate if you add servers to Spanish like anime flv or tioanime, monoschinos or hentai sites as muchohentai or hentaila
I hope they take us into account thanks for reading

**Comment by jmir1** [comment]
"If this is an issue with an extension, I should be opening an issue in the extensions repository."
