### ISSUE TITLE
Make the app available on F-Droid or another repository

### ISSUE THREAD

**Issue by Yugen42** [jmir1/aniyomi#131]
### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/jmir1/aniyomi-extensions/issues/new/choose).
- [X] I have updated the app to the **[latest version](https://github.com/jmir1/aniyomi/releases)**.
- [X] I will fill out all of the requested information in this form.

### Describe your suggested feature

This app should be on a proper repository such as F-Droid to make it easier to install and keep updated.

**Comment by jmir1** [comment]
See #60
