### ISSUE TITLE
Pls put the history in home

### ISSUE THREAD

**Issue by Ekd143** [jmir1/aniyomi#135]
### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/jmir1/aniyomi-extensions/issues/new/choose).
- [X] I have updated the app to the **[latest version](https://github.com/jmir1/aniyomi/releases)**.
- [X] I will fill out all of the requested information in this form.

### Describe your suggested feature

Pls put it on the home button like the tachi2jk where you can find the history close to the updates.

>

**Comment by jmir1** [comment]
#163 could be a possible option
letting the user decide which is more important

**Comment by jmir1** [comment]
Moving this discussion to #163
