### ISSUE TITLE
Pls make a feature where we can decide on the quality of the download 

### ISSUE THREAD

**Issue by Ekd143** [jmir1/aniyomi#136]
### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/jmir1/aniyomi-extensions/issues/new/choose).
- [X] I have updated the app to the **[latest version](https://github.com/jmir1/aniyomi/releases)**.
- [X] I will fill out all of the requested information in this form.

### Describe your suggested feature

When pressing the download it will suggest the quality of it and you can change it to your preferences. 

### Other details

Make it when pressing the download button a sapce will pop up then it will show quality. It takes to much space to download 1080 p

In some extension pls add something like a suggestion of subtitles to the download

**Comment by joyful-cambion** [comment]
I was going to start an issue about this, I wish it'll happen

**Comment by jmir1** [comment]
You can find quality settings in your extension settings
