### ISSUE TITLE
More Anime Extensions

### ISSUE THREAD

**Issue by CryoMitake** [jmir1/aniyomi#139]
### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/jmir1/aniyomi-extensions/issues/new/choose).
- [X] I have updated the app to the **[latest version](https://github.com/jmir1/aniyomi/releases)**.
- [X] I will fill out all of the requested information in this form.

### Describe your suggested feature

I'm not sure if this was already discussed or not but Id like to request more anime extensions like Animepahe, Animepahe is an encoding site in short the storage usage of every anime videos on their site is low and can be helpful for those who are saving storage capacity and watching offline like me.
![Screenshot_2021-08-21-19-18-25-86](https://user-images.githubusercontent.com/89301132/130320282-e9646512-f4f3-44c0-b5fd-5743c59851f6.jpg)

**Comment by kuldeepbairwa** [comment]
animepahe.com is not supported in my country (india). so changing subdomain to animepahe.org will be helpful
thank you in advance 
![Screenshot_20210914-122734_Aniyomi](https://user-images.githubusercontent.com/33427127/133210386-0472b4c9-298d-48fa-8d65-49e15d645288.jpg)

**Comment by jmir1** [comment]
> animepahe.com is not supported in my country (india). so changing subdomain to animepahe.org will be helpful
> thank you in advance
> ![Screenshot_20210914-122734_Aniyomi](https://user-images.githubusercontent.com/33427127/133210386-0472b4c9-298d-48fa-8d65-49e15d645288.jpg)

very wrong place for this discussion
