### ISSUE TITLE
Settings icon in player dissapearing

### ISSUE THREAD

**Issue by SevenNotFound** [jmir1/aniyomi#140]
### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/jmir1/aniyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to the **[latest version](https://github.com/jmir1/aniyomi/releases)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

### Aniyomi version

App version: 0.12.1.1

### Android version

Miui 11

### Device

Redmi 4

### Steps to reproduce

1. Open an anime
2.Play it
3.Now go to next episode using the button in the 
   player
4. The Settings icon dissapears from the player
     (The icon used to change playback speed and 
      video quality)

### Expected behavior

The settings icon dissapears

### Actual behavior

The icon shouldn't have dissapeared

**Comment by jmir1** [comment]
fixed by d8530db85d6459732c5622429e8b3443210a83bd
