### ISSUE TITLE
In-app floating video player + PIP mode for Internal player+ video thumbnail preview while seeking 

### ISSUE THREAD

**Issue by KyleBroflowski** [jmir1/aniyomi#143]
### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/jmir1/aniyomi-extensions/issues/new/choose).
- [X] I have updated the app to the **[latest version](https://github.com/jmir1/aniyomi/releases)**.
- [X] I will fill out all of the requested information in this form.

### Describe your suggested feature

1. PIP mode with video controls (prev,pause,next) is an absolute necessity. 

2. An in-app floating window which still keeps the video playing even while browsing the app.

3. Adding a thumbnails preview option to internal player to seek the video would be great.

**Comment by jmir1** [comment]
Closed by #634
