### ISSUE TITLE
No anime library backup option.

### ISSUE THREAD

**Issue by AD2011** [jmir1/aniyomi#146]
### Steps to reproduce

No anime and anime tracking backup option while creating backup on backup and restore option. Also integrate google drive backup if possible. It is helpful for me as I constantly change ROMs on my phone.

### Expected behavior

Backup option for Anime while Create Backup under Backup And Restore.

### Actual behavior

No such option available. Just backup available for Manga.

### Aniyomi version

Stable 0.12.1.2

### Android version

Android 11

### Device

POCO F1

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/jmir1/aniyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to the **[latest version](https://github.com/jmir1/aniyomi/releases)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by H3LLB0Y101** [comment]
Even tho it doesn't say anime backup, it still backs it up, trust me
