### ISSUE TITLE
Windows Versions (pls)

### ISSUE THREAD

**Issue by SevenNotFound** [jmir1/aniyomi#147]
### Describe your suggested feature

I really need a windows version without using any emulators...
There are many windows anime apps but none of them work.

Pls make windows version 🙏

### Other details

Pls do reply

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/jmir1/aniyomi-extensions/issues/new/choose).
- [X] I have updated the app to the **[latest version](https://github.com/jmir1/aniyomi/releases)**.
- [X] I will fill out all of the requested information in this form.

**Comment by JFronny** [comment]
[Tachidesk](https://github.com/Suwayomi/Tachidesk-Server) is a desktop-port of tachiyomi that supports anime via aniyomis extensions

**Comment by H3LLB0Y101** [comment]
> [Tachidesk](https://github.com/Suwayomi/Tachidesk-Server) is a desktop-port of tachiyomi that supports anime via aniyomis extensions

This client is really buggy. Is it possible that we get a proper application for windows

**Comment by jmir1** [comment]
fyi: tachidesk is currently not supporting aniyomi extensions anymore

**Comment by jmir1** [comment]
It is possible to install Aniyomi in Windows Subsystem for Android.
Here is a tutorial on how to do it: https://www.xda-developers.com/how-to-sideload-android-apps-on-windows-11/

**Comment by github-account1111** [comment]
My computer doesn't support Windows 11 :(

**Comment by JFronny** [comment]
You can still use anbox, waydroid, googles android emulator, android-x86 (maybe) and nox even if you don't use windows 11
