### ISSUE TITLE
Cover option is not available from overflow menu

### ISSUE THREAD

**Issue by krispykiq** [jmir1/aniyomi#148]
### Steps to reproduce

1. Open any Manga/Anime
2. Look at top right 

### Expected behavior

Tapping on the overflow menu should show **Cover** option.

### Actual behavior

The whole overflow menu is gone. It only appears when adding to library but the reason for that is because of the Migrate option.

### Aniyomi version

0.12.1.2

### Android version

Android 9

### Device

Redmi Note 8

### Other details

I checked Tachiyomi and it's available in the overflow menu. It is only gone in Aniyomi.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/jmir1/aniyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to the **[latest version](https://github.com/jmir1/aniyomi/releases)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by jmir1** [comment]
this is not a bug, it's a new feature. you have to click on the cover itself to get the cover options

**Comment by krispykiq** [comment]
I checked the changelog of Tachiyomi v0.12.1. This is the part of the cover options:

- Share and save cover actions (@Jays2Kings, @E3FxGaming)
    - Available from overflow menu or:
    - When long-pressing manga cover (@datreesezcup)

**Comment by jmir1** [comment]
It will replace it in the next version of tachiyomi... Aniyomi is just a bit ahead that's all

**Comment by krispykiq** [comment]
I just tried the preview version and saw that it was removed. Sorry about that.

**Comment by jmir1** [comment]
Np
