### ISSUE TITLE
The App Don't let me Watch an Anime Episode

### ISSUE THREAD

**Issue by CryoMitake** [jmir1/aniyomi#150]
### Steps to reproduce

1.. I choose the Anime I want to watch
2. I choose the Episode I want to watch
3. Once I'm in the player the game goes back on the Anime Interface
![Screenshot_2021-09-07-11-35-36-73](https://user-images.githubusercontent.com/89301132/132282732-11e30ff2-aedd-466b-b564-3b333b0f5963.jpg)

### Expected behavior

It should not goes back at anime interface

### Actual behavior

It goes back at anime interface

### Crash logs

![Screenshot_2021-09-07-11-35-36-73](https://user-images.githubusercontent.com/89301132/132282897-0c05e59f-1cd5-48b5-af86-a70b702879b6.jpg)

### Aniyomi version

0.12.1.2

### Android version

Android 8

### Device

Oppo A5S

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/jmir1/aniyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to the **[latest version](https://github.com/jmir1/aniyomi/releases)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by 15sydny** [comment]
same I was gonna write an issue just now also that error keeps popping up whenever I download an episode like fr

**Comment by Paskalo94** [comment]
I get the same error too but it only happens with the gogoanime extension.

**Comment by robonxt** [comment]
Same issue as well. Perhaps the website changed something?

**Comment by iamavu** [comment]
The Gogoanime extension did get an update, but now it is showing HTTP ERROR 403, instead of the previous error (present in the OP's images)

**Comment by joshuaschi** [comment]
mine's HTTP error 403 on gogoanime extension and "error getting links" on AnimePahe

**Comment by AscendeDDemoN** [comment]
> I get the same error too but it only happens on gogoanime

**Comment by 15sydny** [comment]
it's working now I think, I updated my gogoanime extension

**Comment by lonleyman** [comment]
Hey fix error getting links bug and navigation bar parament pop up in gogo anime I don't care about other extension fix gogoanime first. This latest update is worst .

**Comment by lonleyman** [comment]
> 

No it's not working. Man they always come up with ugly bugs.
