### ISSUE TITLE
mine's HTTP error 403 on gogoanime extension and "error getting links" on AnimePahe

### ISSUE THREAD

**Issue by AscendeDDemoN** [jmir1/aniyomi#151]
mine's HTTP error 403 on gogoanime extension and "error getting links" on AnimePahe

_Originally posted by @joshuaschi in https://github.com/jmir1/aniyomi/issues/150#issuecomment-914402114_

**Comment by shanmugabalan** [comment]
Yes i am also facing that issue with my latest update.HELP PLS...

**Comment by Ruisu-09** [comment]
I also got this issue, i cant play anime in animepahe, it shows "error getting links". But my gogoanime is just fine it's working
