### ISSUE TITLE
Preferred video quality settings

### ISSUE THREAD

**Issue by suraj3486** [jmir1/aniyomi#155]
### Describe your suggested feature

It will be really helpful to add a setting by which it will be pre defined to open any anime in needed quality.
If using external player than it open it in maximum quality all the time.
Right now in inbuilt player it open it in maximum quality than i have to select needed quality.
Having a setting for preferred quality settings will save time and data.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/jmir1/aniyomi-extensions/issues/new/choose).
- [X] I have updated the app to the **[latest version](https://github.com/jmir1/aniyomi/releases)**.
- [X] I will fill out all of the requested information in this form.

**Comment by mnabid** [comment]
Pretty much all the extensions have "Preferred Quality" option now.

See jmir1/aniyomi-extensions#79
