### ISSUE TITLE
Add anime extentions

### ISSUE THREAD

**Issue by suraj3486** [jmir1/aniyomi#159]
### Describe your suggested feature

Please add these sites as anime extentions these sites are widely popular.
Thank you for your time and help

### Other details

[9anime](https://9anime.to/home) 
[animejp](https://animejp.net/) 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/jmir1/aniyomi-extensions/issues/new/choose).
- [X] I have updated the app to the **[latest version](https://github.com/jmir1/aniyomi/releases)**.
- [X] I will fill out all of the requested information in this form.

**Comment by krispykiq** [comment]
They're already planning on adding 9anime but no ETA. Suggesting new sources should be opened in the extensions repository.
