### ISSUE TITLE
Resize Option

### ISSUE THREAD

**Issue by JahinAbrar** [jmir1/aniyomi#164]
### Describe your suggested feature

Resize is the function used to resuze the the anime to fullscreen in mobiles so just do it!!!!!

### Other details

Do it

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/jmir1/aniyomi-extensions/issues/new/choose).
- [X] I have updated the app to the **[latest version](https://github.com/jmir1/aniyomi/releases)**.
- [X] I will fill out all of the requested information in this form.

**Comment by jmir1** [comment]
are you kidding me
