### ISSUE TITLE
[Feature Request] Customize double tapping for internal player

### ISSUE THREAD

**Issue by huangdangwibu** [jmir1/aniyomi#176]
### Describe your suggested feature

I'd if I could choose to make it skip a customizable amount of time

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/jmir1/aniyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.12.2.3](https://github.com/jmir1/aniyomi/releases)**.
- [X] I will fill out all of the requested information in this form.

**Comment by jmir1** [comment]
added with 950ecb4be1df84265488ae18f5f1a7dad660c9dc
