### ISSUE TITLE
Video quality for download. 

### ISSUE THREAD

**Issue by f1998f1998** [jmir1/aniyomi#177]
### Describe your suggested feature

Add option to select video quality for downloader. Because there is no way to change video quality for downloader. even if i open episode and change quality in player to 480p. it still downloads 1080p video. 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/jmir1/aniyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.12.2.3](https://github.com/jmir1/aniyomi/releases)**.
- [X] I will fill out all of the requested information in this form.

**Comment by suraj3486** [comment]
In extentions change the quality

**Comment by f1998f1998** [comment]
oh. ok thanks
