### ISSUE TITLE
No Pause/Resume Button in Download Queue

### ISSUE THREAD

**Issue by mnabid** [jmir1/aniyomi#178]
<details>
<summary><h3>Acknowledgements (Click to Expand)</h3></summary>

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/jmir1/aniyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.12.2.4](https://github.com/jmir1/aniyomi/releases)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.
</details>

### Steps to reproduce

1. Open a manga.
2. Start downloading a chapter.
3. Go to "Download Queue".

### Expected behavior

There should be a button to pause/resume download, like there is in Tachiyomi.

### Actual behavior

There is no pause/resume button in "Download queue".

### Aniyomi version

0.12.2.4

### Android version

8.1.0

### Device

Symphony V140

### Screenshots

| Tachiyomi 0.12.2 | Aniyomi 0.12.2.4 |
| --- | --- |
| ![Screenshot from Tachiyomi](https://user-images.githubusercontent.com/62117272/134849083-f25e55d6-6e63-4ef1-be6f-22c62a2a4ce8.png) | ![Screenshot from Aniyomi](https://user-images.githubusercontent.com/62117272/134849424-ac463ceb-0e23-4fa4-bf8d-12361a715366.png) |

**Comment by jmir1** [comment]
fixed in 1a89150563691e003e73c20da92578a58006e072
