### ISSUE TITLE
Issue while playing media through updates tab

### ISSUE THREAD

**Issue by Rohan-Somadder** [jmir1/aniyomi#179]
### Steps to reproduce

1. Go to **Updates** tab
2. Try to play any updated media (video) either through Internet or downloaded media

### Expected behavior

It should be played with the preffered player (external/internal).

### Actual behavior

It always plays with internal player regarding the user settings or external player. But it acts propery while playing them through the library.

### Aniyomi version

Preview r4146

### Android version

Android 8.1

### Device

Motorola G5 s Plus

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/jmir1/aniyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.12.2.4](https://github.com/jmir1/aniyomi/releases)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by jmir1** [comment]
> Can you delete this issue and join #193 issue (Problem with external players). There we have already 3 people who is raised similar issue.😄

no, this is a different issue

**Comment by erickyun** [comment]
if you set `external player preference` to `none` you can choose your preffered player.
