### ISSUE TITLE
Add anime extensions

### ISSUE THREAD

**Issue by MaMMM7** [jmir1/aniyomi#181]
### Describe your suggested feature

Could you add more italian anime extensions like animeworld or animeunity. Thank you.

### Acknowledgements

- [ ] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [ ] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/jmir1/aniyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.12.2.4](https://github.com/jmir1/aniyomi/releases)**.
- [ ] I will fill out all of the requested information in this form.

**Comment by jmir1** [comment]
https://github.com/jmir1/aniyomi-extensions/issues/new/choose
