### ISSUE TITLE
Error updating library

### ISSUE THREAD

**Issue by MaMMM7** [jmir1/aniyomi#183]
### Steps to reproduce

When i update the library the Mangaworld (Italian extension) extension the app give me an error.

### Expected behavior

If there aren't any new chapter it should just say nothing.

### Actual behavior

When i update the library the Mangaworld (Italian extension) extension the app give me an error.

### Crash logs

Error no chapter found

### Aniyomi version

12.2.4

### Android version

Android 11

### Device

Samsung S10 lite

### Other details

I guess the issue is that Mangaworld changed its domain from Mangaworld.tv to Mangaworld.in

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/jmir1/aniyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.12.2.4](https://github.com/jmir1/aniyomi/releases)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by mnabid** [comment]
https://github.com/jmir1/aniyomi-extensions/issues/new/choose
