### ISSUE TITLE
Extensions not working, can't watch Anime

### ISSUE THREAD

**Issue by SevenNotFound** [jmir1/aniyomi#187]
### Steps to reproduce

First Step: open extensions tab and try to install Extensions

### Expected behavior

Extensions would be installed and i could watch anime

### Actual behavior

so when i open the extension tab, it says
"raw.githubusercontent.com no address associated with hostname"

So i installed manually using the extensions repo and now I can't watch any anime, because it says
"Cant resolve host <extension name>"

### Aniyomi version

App version: 0.12.1.1

### Android version

Miui 11

### Device

Redmi 4

### Other details

![Screenshot_2021-10-07-09-59-29-747_xyz jmir tachiyomi mi](https://user-images.githubusercontent.com/85227518/136322502-20e7f12d-024e-47ee-ba80-73d6158da2d4.jpg)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/jmir1/aniyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.12.3.1](https://github.com/jmir1/aniyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by jmir1** [comment]
either an issue with github's servers or your internet connection.
