### ISSUE TITLE
App crashes when switching to 720p

### ISSUE THREAD

**Issue by s12227054** [jmir1/aniyomi#201]
## Device information
* Aniyomi version: 0.12.3.2
* Android version: 9
* Device: Unimax UMX U69CL

## Steps to reproduce
1. Change quality to 720p (only works on some episodes)

## Issue/Request
On certain episodes of shows, the app crashes when switching to 720p

## Other details
Additional details and attachments.

[tachiyomi_crash_logs.txt](https://github.com/jmir1/aniyomi/files/7393359/tachiyomi_crash_logs.txt)

**Comment by jmir1** [comment]
Fixed by 1a0f90793a72b9930c5d9842f978b8b4354a2982
