### ISSUE TITLE
Downloading anime

### ISSUE THREAD

**Issue by AscendeDDemoN** [jmir1/aniyomi#203]
### Steps to reproduce

Start downloading
Go home/run the app on background
Tap the download notification on notification panel

### Expected behavior

The downloading stops

### Actual behavior

Tapping the downloading notification should take you to download queues

### Aniyomi version

0.12.3.1

### Android version

Android 11

### Device

Samsung a20

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/jmir1/aniyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.12.3.1](https://github.com/jmir1/aniyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by jmir1** [comment]
This issue has been fixed.
