### ISSUE TITLE
Invalid backup file error

### ISSUE THREAD

**Issue by vpankaj97** [jmir1/aniyomi#205]
## Device information
* Aniyomi version: 0.12.3.2
* Android version: 11
* Device: Samsung S20+

## Steps to reproduce
1. Take backup of files in older version (aniyomi)
2. Delete and uninstall app.
3. install latest version.
4. try to restore the backup.

## Issue/Request
Invalid backup file (expected wire type 0 but got 2)

Almost a duplicate of other issues, but the weird thing being this happened with a backup file created with Aniyomi itself

**Comment by jmir1** [comment]
there used to be issues with backup creation in some older aniyomi versions.
in order to restore them, you need to downgrade your app to the old version that you used to create the backup, restore the backup and then update to the current version
