### ISSUE TITLE
Anime Local Source Empty

### ISSUE THREAD

**Issue by noobistbeach** [jmir1/aniyomi#206]
## Device information
* Aniyomi version: 0.12.3.2
* Android version: 11 (LineageOS 18.1)
* Device: Xiaomi Redmi 7

## Steps to reproduce
1. Copy anime to Aniyomi/local/_anime folder_
2. Open Aniyomi and switch to the Browse page
3. Open Local source
4. You will most likely be presented with an empty page

## Issue/Request
Typically, in Tachiyomi or any of its other forks, the Local source corresponds to the local folder under Tachiyomi or the app's name. I assume that is the same here but the app simply does not display the anime as it should. It does not display any error or any other information that I know of as to why it cannot display the anime. For reference, I tried the beta version (r4253) and 0.12.3.1 of the stable version but the same result there. The anime entry shows up under manga's Local source but it obviously won't work there.

## Other details
This is a new install, just found out about the app some hours ago and I should say, I am very excited about it. I have also run some DuckDuckGo and Google searches about the issue but it doesn't seem like there is anything else about it. Or at all.

**Comment by jmir1** [comment]
there's your issue:
> 1. Copy anime to Aniyomi/local/_anime folder_
you need to use the "Aniyomi/localanime" folder (and then put all your videos in one folder without subdirectories for episodes)
i should probably document this somewhere for users.
in other news, local anime currently has a lot of bugs with setting covers and episode number detection, so sorry if some stuff doesn't work as expected.

**Comment by jmir1** [comment]
> This is a new install, just found out about the app some hours ago and I should say, I am very excited about it. I have also run some DuckDuckGo and Google searches about the issue but it doesn't seem like there is anything else about it. Or at all.

also, if you use discord, join our server if you have any further questions. the community there would probably love to help you out.

**Comment by noobistbeach** [comment]
> there's your issue:
> 
> > 1. Copy anime to Aniyomi/local/_anime folder_
> 
> you need to use the "Aniyomi/localanime" folder (and then put all your videos in one folder without subdirectories for episodes) i should probably document this somewhere for users. in other news, local anime currently has a lot of bugs with setting covers and episode number detection, so sorry if some stuff doesn't work as expected.

Yes, that does make sense. I did think that it could be that the folder structure is different but since I couldn't find the info about it, I assume it was a bug. Thanks for the info. And I will be joining your discord.
