### ISSUE TITLE
App crash on refresh

### ISSUE THREAD

**Issue by rubanunes** [jmir1/aniyomi#207]
### Steps to reproduce

Swipe down to refresh on Anime tab.

### Expected behavior

Refresh Anime entries.

### Actual behavior

Crashes and creates a notification just saying Aniyomi. It stays until I open the app again.

### Crash logs

--------- beginning of crash
10-31 00:28:31.340 31171 31171 E AndroidRuntime: FATAL EXCEPTION: main
10-31 00:28:31.340 31171 31171 E AndroidRuntime: Process: xyz.jmir.tachiyomi.mi.debug, PID: 31171
10-31 00:28:31.340 31171 31171 E AndroidRuntime: java.lang.RuntimeException: Unable to start service eu.kanade.tachiyomi.data.animelib.AnimelibUpdateService@82f41ce with Intent { cmp=xyz.jmir.tachiyomi.mi.debug/eu.kanade.tachiyomi.data.animelib.AnimelibUpdateService (has extras) }: java.util.NoSuchElementException
10-31 00:28:31.340 31171 31171 E AndroidRuntime: 	at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:4440)
10-31 00:28:31.340 31171 31171 E AndroidRuntime: 	at android.app.ActivityThread.access$1900(ActivityThread.java:242)
10-31 00:28:31.340 31171 31171 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2026)
10-31 00:28:31.340 31171 31171 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:106)
10-31 00:28:31.340 31171 31171 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:263)
10-31 00:28:31.340 31171 31171 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7832)
10-31 00:28:31.340 31171 31171 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
10-31 00:28:31.340 31171 31171 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
10-31 00:28:31.340 31171 31171 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:952)
10-31 00:28:31.340 31171 31171 E AndroidRuntime: Caused by: java.util.NoSuchElementException
10-31 00:28:31.340 31171 31171 E AndroidRuntime: 	at eu.kanade.tachiyomi.data.animelib.AnimelibUpdateService.addAnimeToQueue(AnimelibUpdateService.kt:48)
10-31 00:28:31.340 31171 31171 E AndroidRuntime: 	at eu.kanade.tachiyomi.data.animelib.AnimelibUpdateService.onStartCommand(AnimelibUpdateService.kt:5)
10-31 00:28:31.340 31171 31171 E AndroidRuntime: 	at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:4422)
10-31 00:28:31.340 31171 31171 E AndroidRuntime: 	... 8 more
10-31 00:30:30.973 32658 32658 E AndroidRuntime: FATAL EXCEPTION: main
10-31 00:30:30.973 32658 32658 E AndroidRuntime: Process: xyz.jmir.tachiyomi.mi.debug, PID: 32658
10-31 00:30:30.973 32658 32658 E AndroidRuntime: java.lang.RuntimeException: Unable to start service eu.kanade.tachiyomi.data.animelib.AnimelibUpdateService@555c927 with Intent { cmp=xyz.jmir.tachiyomi.mi.debug/eu.kanade.tachiyomi.data.animelib.AnimelibUpdateService (has extras) }: java.util.NoSuchElementException
10-31 00:30:30.973 32658 32658 E AndroidRuntime: 	at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:4440)
10-31 00:30:30.973 32658 32658 E AndroidRuntime: 	at android.app.ActivityThread.access$1900(ActivityThread.java:242)
10-31 00:30:30.973 32658 32658 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2026)
10-31 00:30:30.973 32658 32658 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:106)
10-31 00:30:30.973 32658 32658 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:263)
10-31 00:30:30.973 32658 32658 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7832)
10-31 00:30:30.973 32658 32658 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
10-31 00:30:30.973 32658 32658 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
10-31 00:30:30.973 32658 32658 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:952)
10-31 00:30:30.973 32658 32658 E AndroidRuntime: Caused by: java.util.NoSuchElementException
10-31 00:30:30.973 32658 32658 E AndroidRuntime: 	at eu.kanade.tachiyomi.data.animelib.AnimelibUpdateService.addAnimeToQueue(AnimelibUpdateService.kt:48)
10-31 00:30:30.973 32658 32658 E AndroidRuntime: 	at eu.kanade.tachiyomi.data.animelib.AnimelibUpdateService.onStartCommand(AnimelibUpdateService.kt:5)
10-31 00:30:30.973 32658 32658 E AndroidRuntime: 	at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:4422)
10-31 00:30:30.973 32658 32658 E AndroidRuntime: 	... 8 more
--------- beginning of main
10-31 00:33:32.441   408  2224 E SQLiteLog: (284) automatic index on C(manga_id)
10-31 00:33:32.441   408  2224 E SQLiteLog: (284) automatic index on mangas_categories(manga_id)
10-31 00:33:33.649   408   408 E chromium: [ERROR:network_service_instance_impl.cc(179)] Failed to grant sandbox access to network context data for /data/user/0/xyz.jmir.tachiyomi.mi.debug/app_webview/Default with result 7: No such file or directory (2)
App version: 0.12.3.2-4285 (standard, d7121599f, 71, 2021-10-30T22:33Z)
Android version: 11 (SDK 30)
Android build ID: RKQ1.201022.002.30.12.112.36 release-keys
Device brand: asus
Device manufacturer: asus
Device name: ASUS_I006D
Device model: ASUS_I006D
Device product name: EU_I006D

### Aniyomi version

Preview r4285

### Android version

11

### Device

Zenphone 8

### Other details

Functions normally when using the update library button on top.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/jmir1/aniyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.12.3.1](https://github.com/jmir1/aniyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by jmir1** [comment]
I can reproduce the crash if the category is empty or only contains anime which shouldn't be updated (like completed anime if you have turned that setting on).

Will fix later.
