### ISSUE TITLE
App doesn't see local manga on sdcard

### ISSUE THREAD

**Issue by rexolboy8** [jmir1/aniyomi#208]
Title says it all. I've been using Tachiyomi for years, and stored manga on my sdcard. Tachiyomi does see my local manga, while this app doesn't for some reason. Can you please fix that? Thank you.

**Comment by jmir1** [comment]
Make sure you put your manga in the same folder structure, but change the Tachiyomi folder name to Aniyomi.

**Comment by rexolboy8** [comment]
oh man, thank you very much, appreciate the work
