### ISSUE TITLE
Video player Crashing and just not playing

### ISSUE THREAD

**Issue by Rinkan-Club** [jmir1/aniyomi#210]
### Steps to reproduce

1.Play Anime 
2.Anime is back and the pause button just pauses automatically 

### Expected behavior

It should play

### Actual behavior

It crashes and just puts me in the categories 

### Aniyomi version

0.12.3.2

### Android version

Android 9

### Device

Realme c1

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/jmir1/aniyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.12.3.1](https://github.com/jmir1/aniyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by jmir1** [comment]
Probably the same issue as #212
