### ISSUE TITLE
[Bug] Animpahe link not found 404 on download or when streaming

### ISSUE THREAD

**Issue by yooman1213** [jmir1/aniyomi#225]
### Steps to reproduce

Step to reproduce:
1. Pick any anime from animepahe ext
2. Try to stream or download -> Error link not found
3. Try to download -> error link 404

### Expected behavior

Expected behavior:
Watch normally or download normally 

### Actual behavior

Error link not found or error 404

### Aniyomi version

App version: 0.12.3.2-4285 (standard, d7121599f, 71, 2021-10-30T22:33Z)

### Android version

Android version: 11 (SDK 30)

### Device

Device model: SM-G988U1, S20 Ultra

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/jmir1/aniyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.12.3.1](https://github.com/jmir1/aniyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by jmir1** [comment]
This is an issue with an extension, not the app itself.
