### ISSUE TITLE
Not showing release date of anime episode

### ISSUE THREAD

**Issue by KMohZaid** [jmir1/aniyomi#226]
### Steps to reproduce

1. Open any anime page/section in app
2. When checking Release date of episode it show only "Today" on all episodes 

### Expected behavior

It should show correct date of episode release

### Actual behavior

Showing "Today" on every episode
![Screenshot_20211116-010557_Aniyomi](https://user-images.githubusercontent.com/68484509/141843563-0e68ccec-72f8-4af8-bca9-ba07d704c3ca.png)

### Aniyomi version

0.12.3.2

### Android version

Android 11

### Device

Samsung Note 10 Plus

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/jmir1/aniyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.12.3.1](https://github.com/jmir1/aniyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by jmir1** [comment]
This is the normal behaviour.
