### ISSUE TITLE
Error gatting link

### ISSUE THREAD

**Issue by Sudip909** [jmir1/aniyomi#231]
Whin i try to play anime in aniyomi always show me error gatting link in anime pahe , and jmir you always close my issue so hear the prof![Screenshot_20211119-010552.png](https://user-images.githubusercontent.com/78501062/142485250-3df2562f-5db7-48ea-8010-51b8f2c2d690.png)

**Comment by jmir1** [comment]
this issue belongs in a different repository: https://github.com/jmir1/aniyomi-extensions

**Comment by Sudip909** [comment]
Then what i do now???
