### ISSUE TITLE
Unable to edit covers of local source anime

### ISSUE THREAD

**Issue by AbdullahMehiz** [jmir1/aniyomi#232]
### Steps to reproduce

1. Add a local source anime to the library
2. Add a cover to the added anime

### Expected behavior

Updated cover appears

### Actual behavior

No cover whatsoever

### Aniyomi version

R4432

### Android version

Android 11

### Device

Xiaomi Redmi Note 8 Pro

### Other details

https://streamable.com/0j7s9j

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/jmir1/aniyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.12.3.1](https://github.com/jmir1/aniyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by jmir1** [comment]
fixed in 995dd1d77595c2e5cb0362ac15f0e96c88df0f46

**Comment by Prin010** [comment]
> ### Steps to reproduce
> 1. Add a local source anime to the library
> 2. Add a cover to the added anime
> 
> ### Expected behavior
> Updated cover appears
> 
> ### Actual behavior
> No cover whatsoever
> 
> ### Crash logs
> _No response_
> 
> ### Aniyomi version
> R4432
> 
> ### Android version
> Android 11
> 
> ### Device
> Xiaomi Redmi Note 8 Pro
> 
> ### Other details
> https://streamable.com/0j7s9j
> 
> ### Acknowledgements
> * [x]  I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
> * [x]  I have written a short but informative title.
> * [x]  If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/jmir1/aniyomi-extensions/issues/new/choose).
> * [x]  I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
> * [x]  I have updated the app to version **[0.12.3.1](https://github.com/jmir1/aniyomi/releases/latest)**.
> * [x]  I have updated all installed extensions.
> * [x]  I will fill out all of the requested information in this form.

Same issue

**Comment by abdallahmehiz** [comment]
> Same issue

Update your app

**Comment by jmir1** [comment]
> > ### Steps to reproduce
> > 1. Add a local source anime to the library
> > 2. Add a cover to the added anime
> > 
> > ### Expected behavior
> > Updated cover appears
> > 
> > ### Actual behavior
> > No cover whatsoever
> > 
> > ### Crash logs
> > _No response_
> > 
> > ### Aniyomi version
> > R4432
> > 
> > ### Android version
> > Android 11
> > 
> > ### Device
> > Xiaomi Redmi Note 8 Pro
> > 
> > ### Other details
> > https://streamable.com/0j7s9j
> > 
> > ### Acknowledgements
> > * [x]  I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
> > * [x]  I have written a short but informative title.
> > * [x]  If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/jmir1/aniyomi-extensions/issues/new/choose).
> > * [x]  I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
> > * [x]  I have updated the app to version **[0.12.3.1](https://github.com/jmir1/aniyomi/releases/latest)**.
> > * [x]  I have updated all installed extensions.
> > * [x]  I will fill out all of the requested information in this form.
> 
> Same issue 

Necro'd a 2 year old issue that's wild
