### ISSUE TITLE
hm2d extention

### ISSUE THREAD

**Issue by nirmal0001** [jmir1/aniyomi#233]
### Steps to reproduce

1. It's not showing the chapter
2. Chapter are available on websites

### Expected behavior

Should show chapter in app

### Actual behavior

Show no chapter available

### Aniyomi version

latest beta

### Android version

Android 12

### Device

realme 5 pro

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/jmir1/aniyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.12.3.1](https://github.com/jmir1/aniyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by jmir1** [comment]
wrong place to open this issue.
go to https://github.com/tachiyomiorg/tachiyomi-extensions
