### ISSUE TITLE
I don't think i can describe this issue lol

### ISSUE THREAD

**Issue by AbdullahMehiz** [jmir1/aniyomi#236]
### Steps to reproduce

You should watch the video attached

### Expected behavior

A cover change

### Actual behavior

The cover doesn't change

### Crash logs

No crashes

### Aniyomi version

0.12.3.3

### Android version

Android 11

### Device

Xiaomi Redmi Note 8 Pro

### Other details

https://streamable.com/6hxgq3

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/jmir1/aniyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.12.3.3](https://github.com/jmir1/aniyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by AbdullahMehiz** [comment]
The romaji naming worked tho
![Screenshot_2021-11-22-00-43-29-112_xyz jmir tachiyomi mi](https://user-images.githubusercontent.com/85505634/142783795-c1c6ed50-5576-4bb0-a88b-5fca4dc8e3c2.jpg)

**Comment by jmir1** [comment]
the way to fix this is:
- remove that local anime form your library
- go to settings - advanced - clear database
- select the local source and clear its database
- go back to your local anime source and you will see the cover and can add it back to your library

**Comment by jmir1** [comment]
Please try again after updating, I think I fixed it now.
https://github.com/jmir1/aniyomi/releases/tag/v0.12.3.4
