### ISSUE TITLE
App crashes when trying to play videos

### ISSUE THREAD

**Issue by SW3377007H** [jmir1/aniyomi#241]
### Steps to reproduce

1. Click anime
2. Choose episode(tried both external and internal players)
3. Crash and back to device home screen
4. Start back from step 1🤷‍♂️

### Expected behavior

A video should play(atleast i think so🤔)

### Actual behavior

*Crash💥

### Crash logs

------- beginning of crash
11-22 12:38:07.291 22302 22302 E AndroidRuntime: FATAL EXCEPTION: main
11-22 12:38:07.291 22302 22302 E AndroidRuntime: Process: xyz.jmir.tachiyomi.mi.debug, PID: 22302
11-22 12:38:07.291 22302 22302 E AndroidRuntime: java.lang.NoSuchMethodError: No direct method <init>(Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Landroid/net/Uri;Lokhttp3/Headers;)V in class Leu/kanade/tachiyomi/animesource/model/Video; or its super classes (declaration of 'eu.kanade.tachiyomi.animesource.model.Video' appears in base.apk)
11-22 12:38:07.291 22302 22302 E AndroidRuntime: 	at eu.kanade.tachiyomi.animeextension.en.gogoanime.GogoAnime.videoFromElement(GogoAnime.kt:139)
11-22 12:38:07.291 22302 22302 E AndroidRuntime: 	at eu.kanade.tachiyomi.animeextension.en.gogoanime.GogoAnime.videoListParse(GogoAnime.kt:91)
11-22 12:38:07.291 22302 22302 E AndroidRuntime: 	at eu.kanade.tachiyomi.animesource.online.AnimeHttpSource.fetchVideoList$lambda-7(AnimeHttpSource.kt:247)
11-22 12:38:07.291 22302 22302 E AndroidRuntime: 	at eu.kanade.tachiyomi.animesource.online.AnimeHttpSource.lambda$pln_XthPFU5cVytU8N66XM0o42k(Unknown Source:0)
11-22 12:38:07.291 22302 22302 E AndroidRuntime: 	at eu.kanade.tachiyomi.animesource.online.-$$Lambda$AnimeHttpSource$pln_XthPFU5cVytU8N66XM0o42k.call(Unknown Source:4)
11-22 12:38:07.291 22302 22302 E AndroidRuntime: 	at rx.internal.operators.OnSubscribeMap$MapSubscriber.onNext(OnSubscribeMap.java:69)
11-22 12:38:07.291 22302 22302 E AndroidRuntime: 	at rx.internal.operators.OnSubscribeDoOnEach$DoOnEachSubscriber.onNext(OnSubscribeDoOnEach.java:101)
11-22 12:38:07.291 22302 22302 E AndroidRuntime: 	at eu.kanade.tachiyomi.network.OkHttpExtensionsKt$asObservable$1$requestArbiter$1.request(OkHttpExtensions.kt:39)
11-22 12:38:07.291 22302 22302 E AndroidRuntime: 	at rx.Subscriber.setProducer(Subscriber.java:211)
11-22 12:38:07.291 22302 22302 E AndroidRuntime: 	at rx.internal.operators.OnSubscribeMap$MapSubscriber.setProducer(OnSubscribeMap.java:102)
11-22 12:38:07.291 22302 22302 E AndroidRuntime: 	at rx.internal.operators.OnSubscribeMap$MapSubscriber.setProducer(OnSubscribeMap.java:102)
11-22 12:38:07.291 22302 22302 E AndroidRuntime: 	at rx.internal.operators.OnSubscribeMap$MapSubscriber.setProducer(OnSubscribeMap.java:102)
11-22 12:38:07.291 22302 22302 E AndroidRuntime: 	at rx.Subscriber.setProducer(Subscriber.java:205)
11-22 12:38:07.291 22302 22302 E AndroidRuntime: 	at eu.kanade.tachiyomi.network.OkHttpExtensionsKt.asObservable$lambda-0(OkHttpExtensions.kt:59)
11-22 12:38:07.291 22302 22302 E AndroidRuntime: 	at eu.kanade.tachiyomi.network.OkHttpExtensionsKt.lambda$V4FTlhE0zGLykdl_yqVQNonk7gs(Unknown Source:0)
11-22 12:38:07.291 22302 22302 E AndroidRuntime: 	at eu.kanade.tachiyomi.network.-$$Lambda$OkHttpExtensionsKt$V4FTlhE0zGLykdl_yqVQNonk7gs.call(Unknown Source:4)
11-22 12:38:07.291 22302 22302 E AndroidRuntime: 	at rx.Observable.unsafeSubscribe(Observable.java:10327)
11-22 12:38:07.291 22302 22302 E AndroidRuntime: 	at rx.internal.operators.OnSubscribeDoOnEach.call(OnSubscribeDoOnEach.java:41)
11-22 12:38:07.291 22302 22302 E AndroidRuntime: 	at rx.internal.operators.OnSubscribeDoOnEach.call(OnSubscribeDoOnEach.java:30)
11-22 12:38:07.291 22302 22302 E AndroidRuntime: 	at rx.Observable.unsafeSubscribe(Observable.java:10327)
11-22 12:38:07.291 22302 22302 E AndroidRuntime: 	at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:48)
11-22 12:38:07.291 22302 22302 E AndroidRuntime: 	at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:33)
11-22 12:38:07.291 22302 22302 E AndroidRuntime: 	at rx.Observable.unsafeSubscribe(Observable.java:10327)
11-22 12:38:07.291 22302 22302 E AndroidRuntime: 	at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:48)
11-22 12:38:07.291 22302 22302 E AndroidRuntime: 	at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:33)
11-22 12:38:07.291 22302 22302 E AndroidRuntime: 	at rx.Observable.unsafeSubscribe(Observable.java:10327)
11-22 12:38:07.291 22302 22302 E AndroidRuntime: 	at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:48)
11-22 12:38:07.291 22302 22302 E AndroidRuntime: 	at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:33)
11-22 12:38:07.291 22302 22302 E AndroidRuntime: 	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
11-22 12:38:07.291 22302 22302 E AndroidRuntime: 	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
11-22 12:38:07.291 22302 22302 E AndroidRuntime: 	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
11-22 12:38:07.291 22302 22302 E AndroidRuntime: 	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
11-22 12:38:07.291 22302 22302 E AndroidRuntime: 	at rx.Observable.subscribe(Observable.java:10423)
11-22 12:38:07.291 22302 22302 E AndroidRuntime: 	at rx.Observable.subscribe(Observable.java:10390)
11-22 12:38:07.291 22302 22302 E AndroidRuntime: 	at eu.kanade.tachiyomi.util.lang.RxCoroutineBridgeKt.awaitOne(RxCoroutineBridge.kt:25)
11-22 12:38:07.291 22302 22302 E AndroidRuntime: 	at eu.kanade.tachiyomi.util.lang.RxCoroutineBridgeKt.awaitSingle(RxCoroutineBridge.kt:21)
11-22 12:38:07.291 22302 22302 E AndroidRuntime: 	at eu.kanade.tachiyomi.ui.watcher.WatcherActivity$awaitVideoList$2.invokeSuspend(WatcherActivity.kt:232)
11-22 12:38:07.291 22302 22302 E AndroidRuntime: 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
11-22 12:38:07.291 22302 22302 E AndroidRuntime: 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
11-22 12:38:07.291 22302 22302 E AndroidRuntime: 	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
11-22 12:38:07.291 22302 22302 E AndroidRuntime: 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
11-22 12:38:07.291 22302 22302 E AndroidRuntime: 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
11-22 12:38:07.291 22302 22302 E AndroidRuntime: 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
--------- beginning of main
11-23 18:54:08.318 24555 24555 E AndroidRuntime: FATAL EXCEPTION: main
11-23 18:54:08.318 24555 24555 E AndroidRuntime: Process: xyz.jmir.tachiyomi.mi.debug, PID: 24555
11-23 18:54:08.334 24555 24555 E ACRA    : ACRA caught a RuntimeException for xyz.jmir.tachiyomi.mi.debug
11-23 18:54:20.025 25742 25861 E SQLiteLog: (284) automatic index on C(manga_id)
11-23 18:54:20.025 25742 25861 E SQLiteLog: (284) automatic index on mangas_categories(manga_id)
11-23 18:54:21.909 25587 25801 E ACRA    : Failed to send crash reports for /data/user/0/xyz.jmir.tachiyomi.mi.debug/app_ACRA-approved/2021-11-23T18:52:58.136-04:00.stacktrace
App version: 0.11.1.9-3749 (standard, 45a50a7e9, 64, 2021-06-30T14:53Z)
Android version: 9 (SDK 28)
Android build ID: PPR1.180610.011.J260AUCS5BSK1
Device brand: samsung

### Aniyomi version

R3749

### Android version

10

### Device

Samsung

### Other details

Worked perfect a couple months ago then i stopped for a while and now i start back i see this🤷‍♂️

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/jmir1/aniyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.12.3.4](https://github.com/jmir1/aniyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by AbdullahMehiz** [comment]
Did it happen on animepahe?

**Comment by SW3377007H** [comment]
> Did it happen on animepahe?

And gogoanime then i downloaded another to try and same thing happen

**Comment by AbdullahMehiz** [comment]
Gogo is working fine on my end, but i am having the same problem as u with animepahe

**Comment by jmir1** [comment]
> App version: 0.11.1.9-3749 (standard, [45a50a7](https://github.com/jmir1/aniyomi/commit/45a50a7e918e61e8540ebb43bf34fa45afd27bb3), 64, 2021-06-30T14:53Z)

bruh your app version is 5 months outdated
PLEASE update your app (go to more > about > check for updates)
you also checked the box  "I have updated the app to version 0.12.3.4." when opening this issue...
please learn to read
