### ISSUE TITLE
Mark anime/manga as complete after finishing completed series'

### ISSUE THREAD

**Issue by Golumpa** [jmir1/aniyomi#242]
### Describe your suggested feature

On entries where it has been marked as a complete series aka, no longer being released, the last episode should change the tracker to completed instead of just incrementing the watch count by 1 and leaving the series in watching.

Currently it increments the counter so it goes to 12/12 episodes watched but leaves it as watching, when it should be moved to the completed list on the trackers.

### Other details

Expected Result:
![Screenshot 2021-11-24 21 48 16](https://user-images.githubusercontent.com/932845/143317203-f00b5687-a7e6-43c6-b800-560e5e6d0da3.png)

Currently the tracker is left at watching status even though it is finished.
![Screenshot 2021-11-24 21 47 27](https://user-images.githubusercontent.com/932845/143317205-00b41f1b-5180-4e1c-beb2-c2482ea52a1f.png)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/jmir1/aniyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.12.3.4](https://github.com/jmir1/aniyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by jmir1** [comment]
nice suggestion!
i added that feature!
