### ISSUE TITLE
Showing the download resolution

### ISSUE THREAD

**Issue by Winner875** [jmir1/aniyomi#243]
### Describe your suggested feature

Showing the resolution of the anime that is being downloaded because I think it can only download 1080p adding 360p would be helpful

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/jmir1/aniyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.12.3.4](https://github.com/jmir1/aniyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by jmir1** [comment]
see #154

**Comment by Winner875** [comment]
I see can you please do it it would be really helpful
