### ISSUE TITLE
Error getting links whenever i open an episode 

### ISSUE THREAD

**Issue by MooseZM** [jmir1/aniyomi#246]
### Steps to reproduce

I tried all the sources but I still get it, I have adguard so I switched to that in the settings but still nothing. I deactivated adguard and restarted the app but still nothing. I cleared cache and data but no dice. External players seem to work but whenever I try to start an episode it takes such a long time to start the external player that it's not worth doing for every episode (my phone isn't slow btw, while waiting for the ext player to open I can still control the phone just fine)

### Expected behavior

it should start the episode normally

### Actual behavior

I get Error getting links instead

### Aniyomi version

0.12.3.4 latest one

### Android version

android 11

### Device

samsung galaxy a11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/jmir1/aniyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.12.3.4](https://github.com/jmir1/aniyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by Zackhzy** [comment]
Not only watching reading too you can't update your library, slow extensions, this happened in tachiyomi too before I switched in aniyomi, just waited until the extension are fixed.

**Comment by jmir1** [comment]
please open an issue in the extensions repo and include your source, the episode you're trying to play and the error message.
