### ISSUE TITLE
Add swipe gestures for volume, brightness and seek in player

### ISSUE THREAD

**Issue by SoumyBhow** [jmir1/aniyomi#248]
### Describe your suggested feature

Would it be possible to add swipe gestures similar to that of MX Player or even YouTube Vanced? What I mean is when you're in the player:

Swipe up/down on the right side of the screen to increase decrease volume.

Swipe up/down on the left side of the screen to increase/decrease brightness

Swipe left/right on the screen to adjust seek

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/jmir1/aniyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.12.3.5](https://github.com/jmir1/aniyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by tofuisme** [comment]
Second this.

**Comment by SoumyBhow** [comment]
Oh it seems that swipe gestures have been added add seen in #276 and #349 but I can't find them in the settings? I'm on the latest preview build.

**Comment by 12ohit** [comment]
@SoumyBhow If you want to test it you have to download it from the beta build: https://github.com/jmir1/aniyomi-mpv-beta/releases/latest

**Comment by SoumyBhow** [comment]
> @SoumyBhow If you want to test it you have to download it from the beta build: https://github.com/jmir1/aniyomi-mpv-beta/releases/latest

Ohh I didn't know it was a seperate build. Thank you very much for this. It works flawlessly!
