### ISSUE TITLE
Library not updating

### ISSUE THREAD

**Issue by Zackhzy** [jmir1/aniyomi#249]
### Steps to reproduce

Can't Update the library
Slow extension
Can't read or watch

### Expected behavior

Updates the library
Can read and watch
Fast extensions

### Actual behavior

Slow update and extension
Can't read or watch

### Aniyomi version

0.12.3.5

### Android version

Android 10

### Device

OPPO A5s

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/jmir1/aniyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.12.3.5](https://github.com/jmir1/aniyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by jmir1** [comment]
please provide actually useful information.
also, 
> * [x]  If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/jmir1/aniyomi-extensions/issues/new/choose).
