### ISSUE TITLE
Just wanted to inform Bug in the app.

### ISSUE THREAD

**Issue by MARIOWARE** [jmir1/aniyomi#251]
### Steps to reproduce

1. Open vpn and press any videos in hani

### Expected behavior

Press a video and plays in hani

### Actual behavior

 "unable to reslove hosts "hw.hanime.tv" no adress associated with hostsname" appears

### Crash logs

 "unable to reslove hosts "hw.hanime.tv" no adress associated with hostsname"

### Aniyomi version

App version: 0.12.3.5-4381 (standard, e793c6cd1, 71, 2021-11-26T00:20Z) Android version: 11 (SDK 30) Android build ID: RP1A.200720.012.P615XXS4DUJ3 Device brand: samsung Device manufacturer: samsung Device name: gta4xl Device model: SM-P615 Device product name: gta4xlxx

### Android version

11

### Device

Tab s6 lite

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/jmir1/aniyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.12.3.5](https://github.com/jmir1/aniyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by jmir1** [comment]
this is the wrong repo to report this issue! "If this is an issue with an extension, I should be opening an issue in the extensions repository."

the way to fix it is to update the hanime extension and refresh the episode list.
