### ISSUE TITLE
get notifications on new episodes of the anime that one is watching 

### ISSUE THREAD

**Issue by victourousMonk** [jmir1/aniyomi#257]
### Describe your suggested feature

it would be nice to have a feature where the app would give notifications if a new episode is aired on the series that one is watching like the new ones thats being aired .

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/jmir1/aniyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.12.3.5](https://github.com/jmir1/aniyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by jmir1** [comment]
this has always been a feature of this app...
