### ISSUE TITLE
Can't play the video player

### ISSUE THREAD

**Issue by JamesAsmodeus** [jmir1/aniyomi#271]
### Steps to reproduce

First off:
1.) Open Up Aniyomi
2.) Try to play an Episode from any anime
3.) Crashes and I get this notice

![Screenshot_20211204-190448](https://user-images.githubusercontent.com/95528287/144707243-6dac8c51-9d65-436c-8e41-e8d318701e34.png)

### Expected behavior

It should be playing the anime as usual

### Actual behavior

But it is not actually playing and it keeps crashing

### Aniyomi version

0.12.3.5

### Android version

Android 11

### Device

Tecno Spark 6 Go

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/jmir1/aniyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.12.3.5](https://github.com/jmir1/aniyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by omniversial** [comment]
Did you discover the cause?

Happens to me too...

**Comment by jmir1** [comment]
this error message is caused by your isp blocking the domain `dood.ws`
you can try using a different dns or a vpn
