### ISSUE TITLE
Can't play videos

### ISSUE THREAD

**Issue by Mua10** [jmir1/aniyomi#281]
### Steps to reproduce

First off:
1.) Open Up Aniyomi
2.) Open anime4up and try to watch any anime
3.) Crashes and I get this notice
![Screenshot_20211213-181433](https://user-images.githubusercontent.com/95976690/145840465-eefa0138-1822-4291-ab35-1c6f08e1d669.png)

### Expected behavior

It should be playing the anime as usual

### Actual behavior

But it is not actually playing and it keeps crashing

### Aniyomi version

0.12.3.5

### Android version

Android 8.1.0

### Device

Honor 7S

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/jmir1/aniyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.12.3.5](https://github.com/jmir1/aniyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by jmir1** [comment]
this issue is opened in the wrong repo.

please try reading next time.

> If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/jmir1/aniyomi-extensions/issues/new/choose).

**Comment by Ghfye** [comment]
Tt
