### ISSUE TITLE
[Feature Request] Add new display option of thumbnails

### ISSUE THREAD

**Issue by rajbahakdanyu** [jmir1/aniyomi#282]
### Describe your suggested feature

An option to change the thumbnails in the grid view.
Like have the ability to have 4 manga in a row.

### Other details

Like what you can do in tachij2k.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/jmir1/aniyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.12.3.5](https://github.com/jmir1/aniyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by jmir1** [comment]
I'm not sure I understand. You can already change how many manga are displayed per row.
