### ISSUE TITLE
Aniyomi Anime/Manga Categories

### ISSUE THREAD

**Issue by EyeYumStewFeed** [jmir1/aniyomi#286]
### Describe your suggested feature

Why we cant delete, edit, rename our categories?? All it have is Add , ADD ADD  WHY ???

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/jmir1/aniyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.12.3.5](https://github.com/jmir1/aniyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by jmir1** [comment]
you can edit, rename and delete.
just long press the category and click the icons that pop up in the top right corner.

**Comment by EyeYumStewFeed** [comment]
> 

What would happen if I deleted a category with my Manga list in it?

**Comment by jmir1** [comment]
They get moved to the default category.
