### ISSUE TITLE
Error 404 on extension

### ISSUE THREAD

**Issue by Andrewreeves916** [jmir1/aniyomi#291]
### Steps to reproduce

On Animepahe and other extensions for anime it says error 404 it can't find the source code.
Say black clover you can't watch it or download episodes it says error 404

### Expected behavior

Opens or downloads episode

### Actual behavior

Error 404 pops up

### Crash logs

--------- beginning of system
--------- beginning of main
12-21 21:11:52.617  8430  8430 E hiyomi.mi.debu: Invalid ID 0x00000000.
12-21 21:11:52.619  8430  8430 E hiyomi.mi.debu: Invalid ID 0x00000000.
12-21 21:11:53.981  8430  8430 E hiyomi.mi.debu: Invalid ID 0x00000000.
12-21 21:11:53.981  8430  8430 E hiyomi.mi.debu: Invalid ID 0x00000000.
12-21 21:11:55.344  8430  8430 E hiyomi.mi.debu: Invalid ID 0x00000000.
12-21 21:11:55.345  8430  8430 E hiyomi.mi.debu: Invalid ID 0x00000000.
App version: 0.12.3.5-4403 (standard, 737c5c988, 71, 2021-11-29T21:33Z)
Android version: 11 (SDK 30)
Android build ID: RP1A.200720.011
Device brand: POCO
Device manufacturer: Xiaomi
Device name: chopin
Device model: 21061110AG
Device product name: chopin_global

### Aniyomi version

App version: 0.12.3.5-4403 (standard, 737c5c988, 71, 2021-11-29T21:33Z) Android version: 11 (SDK 30) Android build ID: RP1A.200720.011 Device brand: POCO Device manufacturer: Xiaomi Device name: chopin Device model: 21061110AG Device product name: chopin_global

### Android version

Android 11

### Device

Xiaomi Poco X3 GT

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/jmir1/aniyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.12.3.5](https://github.com/jmir1/aniyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by jmir1** [comment]
refresh the episode list. also this is not the right repo for this issue.

> If this is an issue with an extension, I should be opening an issue in the extensions repository.
