### ISSUE TITLE
Very slow video loading

### ISSUE THREAD

**Issue by Anubhabroy787** [jmir1/aniyomi#296]
### Steps to reproduce

Opening any anime in gogoanime or zoro

### Expected behavior

Anime should be loading real quick like it does with hanime plug in which proves it's not a internet connection problem

### Actual behavior

Tried different website plug ins but animes are taking too much time to load or sometimes they just keep buffering and never load

### Aniyomi version

12.3.5

### Android version

11

### Device

Realme 8 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [ ] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/jmir1/aniyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.12.3.5](https://github.com/jmir1/aniyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by jmir1** [comment]
it's because the website limits download speeds.
also: "If this is an issue with an extension, I should be opening an issue in the extensions repository."
