### ISSUE TITLE
App crashes when opening video

### ISSUE THREAD

**Issue by crxssed7** [jmir1/aniyomi#297]
### Steps to reproduce

Steps to reproduce:
1. Click on an anime episode
2. App crashes and exits

### Expected behavior

Video should play

### Actual behavior

The app crashes completely, exits out of the app. This started happening after an Android update.

### Crash logs

--------- beginning of crash
12-30 22:33:52.666 26751 26751 E AndroidRuntime: FATAL EXCEPTION: main
12-30 22:33:52.666 26751 26751 E AndroidRuntime: Process: xyz.jmir.tachiyomi.mi, PID: 26751
12-30 22:33:52.666 26751 26751 E AndroidRuntime: java.lang.RuntimeException: Unable to instantiate activity ComponentInfo{xyz.jmir.tachiyomi.mi/eu.kanade.tachiyomi.ui.player.PlayerActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.pm.ApplicationInfo android.content.Context.getApplicationInfo()' on a null object reference
12-30 22:33:52.666 26751 26751 E AndroidRuntime: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3901)
12-30 22:33:52.666 26751 26751 E AndroidRuntime: 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:4188)
12-30 22:33:52.666 26751 26751 E AndroidRuntime: 	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:103)
12-30 22:33:52.666 26751 26751 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
12-30 22:33:52.666 26751 26751 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
12-30 22:33:52.666 26751 26751 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2425)
12-30 22:33:52.666 26751 26751 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:106)
12-30 22:33:52.666 26751 26751 E AndroidRuntime: 	at android.os.Looper.loopOnce(Looper.java:226)
12-30 22:33:52.666 26751 26751 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:313)
12-30 22:33:52.666 26751 26751 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:8582)
12-30 22:33:52.666 26751 26751 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
12-30 22:33:52.666 26751 26751 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:563)
12-30 22:33:52.666 26751 26751 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1133)
12-30 22:33:52.666 26751 26751 E AndroidRuntime: Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.pm.ApplicationInfo android.content.Context.getApplicationInfo()' on a null object reference
12-30 22:33:52.666 26751 26751 E AndroidRuntime: 	at android.content.ContextWrapper.getApplicationInfo(ContextWrapper.java:190)
12-30 22:33:52.666 26751 26751 E AndroidRuntime: 	at android.webkit.WebSettings.addWebViewAssetPath(WebSettings.java:1376)
12-30 22:33:52.666 26751 26751 E AndroidRuntime: 	at android.webkit.WebSettings.getDefaultUserAgent(WebSettings.java:1369)
12-30 22:33:52.666 26751 26751 E AndroidRuntime: 	at eu.kanade.tachiyomi.ui.player.PlayerActivity.<init>(PlayerActivity.kt:21)
12-30 22:33:52.666 26751 26751 E AndroidRuntime: 	at java.lang.Class.newInstance(Native Method)
12-30 22:33:52.666 26751 26751 E AndroidRuntime: 	at android.app.AppComponentFactory.instantiateActivity(AppComponentFactory.java:95)
12-30 22:33:52.666 26751 26751 E AndroidRuntime: 	at androidx.core.app.CoreComponentFactory.instantiateActivity(CoreComponentFactory.java:1)
12-30 22:33:52.666 26751 26751 E AndroidRuntime: 	at android.app.Instrumentation.newActivity(Instrumentation.java:1273)
12-30 22:33:52.666 26751 26751 E AndroidRuntime: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3888)
12-30 22:33:52.666 26751 26751 E AndroidRuntime: 	... 12 more
--------- beginning of main
12-30 22:40:11.125  7382 10010 E SQLiteLog: (284) automatic index on C(anime_id)
12-30 22:40:11.125  7382 10010 E SQLiteLog: (284) automatic index on animes_categories(anime_id)
12-30 22:58:40.867  7382 10009 E SQLiteLog: (284) automatic index on C(manga_id)
12-30 22:58:40.867  7382 10009 E SQLiteLog: (284) automatic index on mangas_categories(manga_id)
12-30 23:24:00.483  7382  7382 E ViewRootImpl: sendUserActionEvent() mView returned.
12-30 23:24:08.424  7382  7382 E ViewRootImpl: sendUserActionEvent() mView returned.
12-30 23:24:39.974 19258 19258 E ir.tachiyomi.m: Not starting debugger since process cannot load the jdwp agent.
12-30 23:24:39.975 19258 19258 E USNET   : USNET: appName: xyz.jmir.tachiyomi.mi
12-30 23:24:40.146 19258 19291 E FirebaseCrashlytics: Settings request failed.
12-30 23:24:40.146 19258 19291 E FirebaseCrashlytics: java.net.ConnectException: Failed to connect to firebase-settings.crashlytics.com/127.1.1.1:443
12-30 23:24:40.146 19258 19291 E FirebaseCrashlytics: 	at com.android.okhttp.internal.io.RealConnection.connectSocket(RealConnection.java:147)
12-30 23:24:40.146 19258 19291 E FirebaseCrashlytics: 	at com.android.okhttp.internal.io.RealConnection.connect(RealConnection.java:116)
12-30 23:24:40.146 19258 19291 E FirebaseCrashlytics: 	at com.android.okhttp.internal.http.StreamAllocation.findConnection(StreamAllocation.java:186)
12-30 23:24:40.146 19258 19291 E FirebaseCrashlytics: 	at com.android.okhttp.internal.http.StreamAllocation.findHealthyConnection(StreamAllocation.java:128)
12-30 23:24:40.146 19258 19291 E FirebaseCrashlytics: 	at com.android.okhttp.internal.http.StreamAllocation.newStream(StreamAllocation.java:97)
12-30 23:24:40.146 19258 19291 E FirebaseCrashlytics: 	at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:289)
12-30 23:24:40.146 19258 19291 E FirebaseCrashlytics: 	at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:232)
12-30 23:24:40.146 19258 19291 E FirebaseCrashlytics: 	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:465)
12-30 23:24:40.146 19258 19291 E FirebaseCrashlytics: 	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.connect(HttpURLConnectionImpl.java:131)
12-30 23:24:40.146 19258 19291 E FirebaseCrashlytics: 	at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.connect(DelegatingHttpsURLConnection.java:90)
12-30 23:24:40.146 19258 19291 E FirebaseCrashlytics: 	at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.connect(HttpsURLConnectionImpl.java:30)
12-30 23:24:40.146 19258 19291 E FirebaseCrashlytics: 	at com.google.firebase.crashlytics.internal.network.HttpGetRequest.execute(HttpGetRequest.java:11)
12-30 23:24:40.146 19258 19291 E FirebaseCrashlytics: 	at com.google.firebase.crashlytics.internal.settings.SettingsController$1.then(SettingsController.java:11)
12-30 23:24:40.146 19258 19291 E FirebaseCrashlytics: 	at com.google.android.gms.tasks.zzf.run(Unknown Source:3)
12-30 23:24:40.146 19258 19291 E FirebaseCrashlytics: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
12-30 23:24:40.146 19258 19291 E FirebaseCrashlytics: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
12-30 23:24:40.146 19258 19291 E FirebaseCrashlytics: 	at com.google.firebase.crashlytics.internal.common.ExecutorUtils$1$1.onRun(ExecutorUtils.java:1)
12-30 23:24:40.146 19258 19291 E FirebaseCrashlytics: 	at com.google.firebase.crashlytics.internal.common.BackgroundPriorityRunnable.run(BackgroundPriorityRunnable.java:2)
12-30 23:24:40.146 19258 19291 E FirebaseCrashlytics: 	at java.lang.Thread.run(Thread.java:920)
12-30 23:24:43.883 19258 19367 E SQLiteLog: (284) automatic index on C(anime_id)
12-30 23:24:43.883 19258 19367 E SQLiteLog: (284) automatic index on animes_categories(anime_id)
12-30 23:25:30.047 20197 20197 E ir.tachiyomi.m: Not starting debugger since process cannot load the jdwp agent.
12-30 23:25:30.048 20197 20197 E USNET   : USNET: appName: xyz.jmir.tachiyomi.mi
12-30 23:25:30.189 20197 20225 E FirebaseCrashlytics: Settings request failed.
12-30 23:25:30.189 20197 20225 E FirebaseCrashlytics: java.net.ConnectException: Failed to connect to firebase-settings.crashlytics.com/127.1.1.1:443
12-30 23:25:30.189 20197 20225 E FirebaseCrashlytics: 	at com.android.okhttp.internal.io.RealConnection.connectSocket(RealConnection.java:147)
12-30 23:25:30.189 20197 20225 E FirebaseCrashlytics: 	at com.android.okhttp.internal.io.RealConnection.connect(RealConnection.java:116)
12-30 23:25:30.189 20197 20225 E FirebaseCrashlytics: 	at com.android.okhttp.internal.http.StreamAllocation.findConnection(StreamAllocation.java:186)
12-30 23:25:30.189 20197 20225 E FirebaseCrashlytics: 	at com.android.okhttp.internal.http.StreamAllocation.findHealthyConnection(StreamAllocation.java:128)
12-30 23:25:30.189 20197 20225 E FirebaseCrashlytics: 	at com.android.okhttp.internal.http.StreamAllocation.newStream(StreamAllocation.java:97)
12-30 23:25:30.189 20197 20225 E FirebaseCrashlytics: 	at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:289)
12-30 23:25:30.189 20197 20225 E FirebaseCrashlytics: 	at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:232)
12-30 23:25:30.189 20197 20225 E FirebaseCrashlytics: 	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:465)
12-30 23:25:30.189 20197 20225 E FirebaseCrashlytics: 	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.connect(HttpURLConnectionImpl.java:131)
12-30 23:25:30.189 20197 20225 E FirebaseCrashlytics: 	at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.connect(DelegatingHttpsURLConnection.java:90)
12-30 23:25:30.189 20197 20225 E FirebaseCrashlytics: 	at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.connect(HttpsURLConnectionImpl.java:30)
12-30 23:25:30.189 20197 20225 E FirebaseCrashlytics: 	at com.google.firebase.crashlytics.internal.network.HttpGetRequest.execute(HttpGetRequest.java:11)
12-30 23:25:30.189 20197 20225 E FirebaseCrashlytics: 	at com.google.firebase.crashlytics.internal.settings.SettingsController$1.then(SettingsController.java:11)
12-30 23:25:30.189 20197 20225 E FirebaseCrashlytics: 	at com.google.android.gms.tasks.zzf.run(Unknown Source:3)
12-30 23:25:30.189 20197 20225 E FirebaseCrashlytics: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
12-30 23:25:30.189 20197 20225 E FirebaseCrashlytics: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
12-30 23:25:30.189 20197 20225 E FirebaseCrashlytics: 	at com.google.firebase.crashlytics.internal.common.ExecutorUtils$1$1.onRun(ExecutorUtils.java:1)
12-30 23:25:30.189 20197 20225 E FirebaseCrashlytics: 	at com.google.firebase.crashlytics.internal.common.BackgroundPriorityRunnable.run(BackgroundPriorityRunnable.java:2)
12-30 23:25:30.189 20197 20225 E FirebaseCrashlytics: 	at java.lang.Thread.run(Thread.java:920)
12-30 23:34:22.790 20197 26299 E SQLiteLog: (284) automatic index on C(anime_id)
12-30 23:34:22.790 20197 26299 E SQLiteLog: (284) automatic index on animes_categories(anime_id)
12-30 23:34:28.092 20197 20197 E AndroidRuntime: FATAL EXCEPTION: main
12-30 23:34:28.092 20197 20197 E AndroidRuntime: Process: xyz.jmir.tachiyomi.mi, PID: 20197
12-30 23:34:28.092 20197 20197 E AndroidRuntime: java.lang.RuntimeException: Unable to instantiate activity ComponentInfo{xyz.jmir.tachiyomi.mi/eu.kanade.tachiyomi.ui.player.PlayerActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.pm.ApplicationInfo android.content.Context.getApplicationInfo()' on a null object reference
12-30 23:34:28.092 20197 20197 E AndroidRuntime: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3901)
12-30 23:34:28.092 20197 20197 E AndroidRuntime: 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:4188)
12-30 23:34:28.092 20197 20197 E AndroidRuntime: 	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:103)
12-30 23:34:28.092 20197 20197 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
12-30 23:34:28.092 20197 20197 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
12-30 23:34:28.092 20197 20197 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2425)
12-30 23:34:28.092 20197 20197 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:106)
12-30 23:34:28.092 20197 20197 E AndroidRuntime: 	at android.os.Looper.loopOnce(Looper.java:226)
12-30 23:34:28.092 20197 20197 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:313)
12-30 23:34:28.092 20197 20197 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:8582)
12-30 23:34:28.092 20197 20197 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
12-30 23:34:28.092 20197 20197 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:563)
12-30 23:34:28.092 20197 20197 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1133)
12-30 23:34:28.092 20197 20197 E AndroidRuntime: Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.pm.ApplicationInfo android.content.Context.getApplicationInfo()' on a null object reference
12-30 23:34:28.092 20197 20197 E AndroidRuntime: 	at android.content.ContextWrapper.getApplicationInfo(ContextWrapper.java:190)
12-30 23:34:28.092 20197 20197 E AndroidRuntime: 	at android.webkit.WebSettings.addWebViewAssetPath(WebSettings.java:1376)
12-30 23:34:28.092 20197 20197 E AndroidRuntime: 	at android.webkit.WebSettings.getDefaultUserAgent(WebSettings.java:1369)
12-30 23:34:28.092 20197 20197 E AndroidRuntime: 	at eu.kanade.tachiyomi.ui.player.PlayerActivity.<init>(PlayerActivity.kt:21)
12-30 23:34:28.092 20197 20197 E AndroidRuntime: 	at java.lang.Class.newInstance(Native Method)
12-30 23:34:28.092 20197 20197 E AndroidRuntime: 	at android.app.AppComponentFactory.instantiateActivity(AppComponentFactory.java:95)
12-30 23:34:28.092 20197 20197 E AndroidRuntime: 	at androidx.core.app.CoreComponentFactory.instantiateActivity(CoreComponentFactory.java:1)
12-30 23:34:28.092 20197 20197 E AndroidRuntime: 	at android.app.Instrumentation.newActivity(Instrumentation.java:1273)
12-30 23:34:28.092 20197 20197 E AndroidRuntime: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3888)
12-30 23:34:28.092 20197 20197 E AndroidRuntime: 	... 12 more
12-30 23:34:32.095 20197 20197 E FirebaseCrashlytics: Error handling uncaught exception
12-30 23:34:32.095 20197 20197 E FirebaseCrashlytics: java.util.concurrent.TimeoutException
12-30 23:34:32.095 20197 20197 E FirebaseCrashlytics: 	at com.google.firebase.crashlytics.internal.common.Utils.awaitEvenIfOnMainThread(Utils.java:11)
12-30 23:34:32.095 20197 20197 E FirebaseCrashlytics: 	at com.google.firebase.crashlytics.internal.common.CrashlyticsController$1.onUncaughtException(CrashlyticsController.java:10)
12-30 23:34:32.095 20197 20197 E FirebaseCrashlytics: 	at com.google.firebase.crashlytics.internal.common.CrashlyticsUncaughtExceptionHandler.uncaughtException(CrashlyticsUncaughtExceptionHandler.java:3)
12-30 23:34:32.095 20197 20197 E FirebaseCrashlytics: 	at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1073)
12-30 23:34:32.095 20197 20197 E FirebaseCrashlytics: 	at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1068)
12-30 23:34:32.095 20197 20197 E FirebaseCrashlytics: 	at java.lang.Thread.dispatchUncaughtException(Thread.java:2200)
12-30 23:34:33.267 26476 26476 E ir.tachiyomi.m: Not starting debugger since process cannot load the jdwp agent.
12-30 23:34:33.268 26476 26476 E USNET   : USNET: appName: xyz.jmir.tachiyomi.mi
12-30 23:34:33.343 26476 26508 E FirebaseCrashlytics: Settings request failed.
12-30 23:34:33.343 26476 26508 E FirebaseCrashlytics: java.net.ConnectException: Failed to connect to firebase-settings.crashlytics.com/127.1.1.1:443
12-30 23:34:33.343 26476 26508 E FirebaseCrashlytics: 	at com.android.okhttp.internal.io.RealConnection.connectSocket(RealConnection.java:147)
12-30 23:34:33.343 26476 26508 E FirebaseCrashlytics: 	at com.android.okhttp.internal.io.RealConnection.connect(RealConnection.java:116)
12-30 23:34:33.343 26476 26508 E FirebaseCrashlytics: 	at com.android.okhttp.internal.http.StreamAllocation.findConnection(StreamAllocation.java:186)
12-30 23:34:33.343 26476 26508 E FirebaseCrashlytics: 	at com.android.okhttp.internal.http.StreamAllocation.findHealthyConnection(StreamAllocation.java:128)
12-30 23:34:33.343 26476 26508 E FirebaseCrashlytics: 	at com.android.okhttp.internal.http.StreamAllocation.newStream(StreamAllocation.java:97)
12-30 23:34:33.343 26476 26508 E FirebaseCrashlytics: 	at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:289)
12-30 23:34:33.343 26476 26508 E FirebaseCrashlytics: 	at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:232)
12-30 23:34:33.343 26476 26508 E FirebaseCrashlytics: 	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:465)
12-30 23:34:33.343 26476 26508 E FirebaseCrashlytics: 	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.connect(HttpURLConnectionImpl.java:131)
12-30 23:34:33.343 26476 26508 E FirebaseCrashlytics: 	at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.connect(DelegatingHttpsURLConnection.java:90)
12-30 23:34:33.343 26476 26508 E FirebaseCrashlytics: 	at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.connect(HttpsURLConnectionImpl.java:30)
12-30 23:34:33.343 26476 26508 E FirebaseCrashlytics: 	at com.google.firebase.crashlytics.internal.network.HttpGetRequest.execute(HttpGetRequest.java:11)
12-30 23:34:33.343 26476 26508 E FirebaseCrashlytics: 	at com.google.firebase.crashlytics.internal.settings.SettingsController$1.then(SettingsController.java:11)
12-30 23:34:33.343 26476 26508 E FirebaseCrashlytics: 	at com.google.android.gms.tasks.zzf.run(Unknown Source:3)
12-30 23:34:33.343 26476 26508 E FirebaseCrashlytics: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
12-30 23:34:33.343 26476 26508 E FirebaseCrashlytics: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
12-30 23:34:33.343 26476 26508 E FirebaseCrashlytics: 	at com.google.firebase.crashlytics.internal.common.ExecutorUtils$1$1.onRun(ExecutorUtils.java:1)
12-30 23:34:33.343 26476 26508 E FirebaseCrashlytics: 	at com.google.firebase.crashlytics.internal.common.BackgroundPriorityRunnable.run(BackgroundPriorityRunnable.java:2)
12-30 23:34:33.343 26476 26508 E FirebaseCrashlytics: 	at java.lang.Thread.run(Thread.java:920)
12-30 23:34:33.470 26476 26545 E SQLiteLog: (284) automatic index on C(anime_id)
12-30 23:34:33.470 26476 26545 E SQLiteLog: (284) automatic index on animes_categories(anime_id)
12-30 23:34:39.956 26476 26476 E AndroidRuntime: FATAL EXCEPTION: main
12-30 23:34:39.956 26476 26476 E AndroidRuntime: Process: xyz.jmir.tachiyomi.mi, PID: 26476
12-30 23:34:39.956 26476 26476 E AndroidRuntime: java.lang.RuntimeException: Unable to instantiate activity ComponentInfo{xyz.jmir.tachiyomi.mi/eu.kanade.tachiyomi.ui.player.PlayerActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.pm.ApplicationInfo android.content.Context.getApplicationInfo()' on a null object reference
12-30 23:34:39.956 26476 26476 E AndroidRuntime: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3901)
12-30 23:34:39.956 26476 26476 E AndroidRuntime: 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:4188)
12-30 23:34:39.956 26476 26476 E AndroidRuntime: 	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:103)
12-30 23:34:39.956 26476 26476 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
12-30 23:34:39.956 26476 26476 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
12-30 23:34:39.956 26476 26476 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2425)
12-30 23:34:39.956 26476 26476 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:106)
12-30 23:34:39.956 26476 26476 E AndroidRuntime: 	at android.os.Looper.loopOnce(Looper.java:226)
12-30 23:34:39.956 26476 26476 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:313)
12-30 23:34:39.956 26476 26476 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:8582)
12-30 23:34:39.956 26476 26476 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
12-30 23:34:39.956 26476 26476 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:563)
12-30 23:34:39.956 26476 26476 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1133)
12-30 23:34:39.956 26476 26476 E AndroidRuntime: Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.pm.ApplicationInfo android.content.Context.getApplicationInfo()' on a null object reference
12-30 23:34:39.956 26476 26476 E AndroidRuntime: 	at android.content.ContextWrapper.getApplicationInfo(ContextWrapper.java:190)
12-30 23:34:39.956 26476 26476 E AndroidRuntime: 	at android.webkit.WebSettings.addWebViewAssetPath(WebSettings.java:1376)
12-30 23:34:39.956 26476 26476 E AndroidRuntime: 	at android.webkit.WebSettings.getDefaultUserAgent(WebSettings.java:1369)
12-30 23:34:39.956 26476 26476 E AndroidRuntime: 	at eu.kanade.tachiyomi.ui.player.PlayerActivity.<init>(PlayerActivity.kt:21)
12-30 23:34:39.956 26476 26476 E AndroidRuntime: 	at java.lang.Class.newInstance(Native Method)
12-30 23:34:39.956 26476 26476 E AndroidRuntime: 	at android.app.AppComponentFactory.instantiateActivity(AppComponentFactory.java:95)
12-30 23:34:39.956 26476 26476 E AndroidRuntime: 	at androidx.core.app.CoreComponentFactory.instantiateActivity(CoreComponentFactory.java:1)
12-30 23:34:39.956 26476 26476 E AndroidRuntime: 	at android.app.Instrumentation.newActivity(Instrumentation.java:1273)
12-30 23:34:39.956 26476 26476 E AndroidRuntime: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3888)
12-30 23:34:39.956 26476 26476 E AndroidRuntime: 	... 12 more
12-30 23:34:43.958 26476 26476 E FirebaseCrashlytics: Error handling uncaught exception
12-30 23:34:43.958 26476 26476 E FirebaseCrashlytics: java.util.concurrent.TimeoutException
12-30 23:34:43.958 26476 26476 E FirebaseCrashlytics: 	at com.google.firebase.crashlytics.internal.common.Utils.awaitEvenIfOnMainThread(Utils.java:11)
12-30 23:34:43.958 26476 26476 E FirebaseCrashlytics: 	at com.google.firebase.crashlytics.internal.common.CrashlyticsController$1.onUncaughtException(CrashlyticsController.java:10)
12-30 23:34:43.958 26476 26476 E FirebaseCrashlytics: 	at com.google.firebase.crashlytics.internal.common.CrashlyticsUncaughtExceptionHandler.uncaughtException(CrashlyticsUncaughtExceptionHandler.java:3)
12-30 23:34:43.958 26476 26476 E FirebaseCrashlytics: 	at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1073)
12-30 23:34:43.958 26476 26476 E FirebaseCrashlytics: 	at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1068)
12-30 23:34:43.958 26476 26476 E FirebaseCrashlytics: 	at java.lang.Thread.dispatchUncaughtException(Thread.java:2200)
12-30 23:34:48.045 26629 26629 E ir.tachiyomi.m: Not starting debugger since process cannot load the jdwp agent.
12-30 23:34:48.046 26629 26629 E USNET   : USNET: appName: xyz.jmir.tachiyomi.mi
12-30 23:34:48.109 26629 26662 E FirebaseCrashlytics: Settings request failed.
12-30 23:34:48.109 26629 26662 E FirebaseCrashlytics: java.net.ConnectException: Failed to connect to firebase-settings.crashlytics.com/127.1.1.1:443
12-30 23:34:48.109 26629 26662 E FirebaseCrashlytics: 	at com.android.okhttp.internal.io.RealConnection.connectSocket(RealConnection.java:147)
12-30 23:34:48.109 26629 26662 E FirebaseCrashlytics: 	at com.android.okhttp.internal.io.RealConnection.connect(RealConnection.java:116)
12-30 23:34:48.109 26629 26662 E FirebaseCrashlytics: 	at com.android.okhttp.internal.http.StreamAllocation.findConnection(StreamAllocation.java:186)
12-30 23:34:48.109 26629 26662 E FirebaseCrashlytics: 	at com.android.okhttp.internal.http.StreamAllocation.findHealthyConnection(StreamAllocation.java:128)
12-30 23:34:48.109 26629 26662 E FirebaseCrashlytics: 	at com.android.okhttp.internal.http.StreamAllocation.newStream(StreamAllocation.java:97)
12-30 23:34:48.109 26629 26662 E FirebaseCrashlytics: 	at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:289)
12-30 23:34:48.109 26629 26662 E FirebaseCrashlytics: 	at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:232)
12-30 23:34:48.109 26629 26662 E FirebaseCrashlytics: 	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:465)
12-30 23:34:48.109 26629 26662 E FirebaseCrashlytics: 	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.connect(HttpURLConnectionImpl.java:131)
12-30 23:34:48.109 26629 26662 E FirebaseCrashlytics: 	at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.connect(DelegatingHttpsURLConnection.java:90)
12-30 23:34:48.109 26629 26662 E FirebaseCrashlytics: 	at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.connect(HttpsURLConnectionImpl.java:30)
12-30 23:34:48.109 26629 26662 E FirebaseCrashlytics: 	at com.google.firebase.crashlytics.internal.network.HttpGetRequest.execute(HttpGetRequest.java:11)
12-30 23:34:48.109 26629 26662 E FirebaseCrashlytics: 	at com.google.firebase.crashlytics.internal.settings.SettingsController$1.then(SettingsController.java:11)
12-30 23:34:48.109 26629 26662 E FirebaseCrashlytics: 	at com.google.android.gms.tasks.zzf.run(Unknown Source:3)
12-30 23:34:48.109 26629 26662 E FirebaseCrashlytics: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
12-30 23:34:48.109 26629 26662 E FirebaseCrashlytics: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
12-30 23:34:48.109 26629 26662 E FirebaseCrashlytics: 	at com.google.firebase.crashlytics.internal.common.ExecutorUtils$1$1.onRun(ExecutorUtils.java:1)
12-30 23:34:48.109 26629 26662 E FirebaseCrashlytics: 	at com.google.firebase.crashlytics.internal.common.BackgroundPriorityRunnable.run(BackgroundPriorityRunnable.java:2)
12-30 23:34:48.109 26629 26662 E FirebaseCrashlytics: 	at java.lang.Thread.run(Thread.java:920)
12-30 23:34:48.245 26629 26698 E SQLiteLog: (284) automatic index on C(anime_id)
12-30 23:34:48.246 26629 26698 E SQLiteLog: (284) automatic index on animes_categories(anime_id)
App version: 0.12.3.5 (standard, e793c6c, 71, 2021-11-26T00:20Z)
Android version: 12 (SDK 31)
Android build ID: SP1A.210812.016.G991BXXS3BULC
Device brand: samsung
Device manufacturer: samsung
Device name: o1s
Device model: SM-G991B
Device product name: o1sxeea

### Aniyomi version

0.12.3.5

### Android version

Android 12

### Device

Samsung S21

### Other details

Just a note, this happens for all extensions i have tried, and does not affect manga.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/jmir1/aniyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.12.3.5](https://github.com/jmir1/aniyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by juliannotanerd** [comment]
Same problem for me

**Comment by jmir1** [comment]
fixed by cc457815c9b8df133c3ee722d0318f2d0d9c576a
