### ISSUE TITLE
Allmovies extension error

### ISSUE THREAD

**Issue by ryan9911** [jmir1/aniyomi#299]
### Steps to reproduce

1.click on movies
2.gets NXDOMAIN error instead

### Expected behavior

Get to pick episode to watch 

### Actual behavior

![Screenshot_20220102-185854](https://user-images.githubusercontent.com/74333682/147873628-3ae6111d-d6c4-4810-a583-a54636cb740b.png)

### Aniyomi version

0.12.3.5-4403

### Android version

Android 11

### Device

Google Pixel 3

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/jmir1/aniyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.12.3.5](https://github.com/jmir1/aniyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by GoluLiliput** [comment]
I get the same error
