### ISSUE TITLE
[Feature Request] - Creating Backups Don't Include Anime in your library

### ISSUE THREAD

**Issue by Memezaa** [jmir1/aniyomi#30]
[ App version: 0.10.12.4-mi ]

Creating a backup does not include the Anime section of your library.

**Comment by batfos** [comment]
I think this should be priority. The app doesn't last even a day (crash on launch), so it needs to be reinstalled every time (data gone).

**Comment by ItsArchfiend** [comment]
Even on the latest version it's still a big for me
