### ISSUE TITLE
Download progress notification persists after 100%

### ISSUE THREAD

**Issue by Reigen441** [jmir1/aniyomi#304]
### Steps to reproduce

Downloaded episode in library. Extension was AnimePahe.  The download progress notification persisted even after download was complete. Had to manually disable progress notification from system for all future anime and manga downloads. 

### Expected behavior

The download progress notification should disappear.

### Actual behavior

The download progess notification continued showing with 100% as progress.

### Aniyomi version

0.12.3.5

### Android version

Android 9

### Device

Samsung Galaxy Note 8

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/jmir1/aniyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.12.3.5](https://github.com/jmir1/aniyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by glokta1** [comment]
Are you still having this issue? @Reigen441

**Comment by Reigen441** [comment]
No @glokta1 . Thanks a lot.

**Comment by xHaruke** [comment]
having the same problem on 0.12.3.10 with animepahe
