### ISSUE TITLE
i cant load all my manga in aniyomi

### ISSUE THREAD

**Issue by eyn31** [jmir1/aniyomi#307]
### Steps to reproduce

i just update my aniyomi
then i want to reload it, just 15 of em
but i have 100 manga
this not happend before

### Expected behavior

i have 100 manga, should it reload all of them

### Actual behavior

but the result is just reload 15 of them, this never happend before

### Crash logs

there is no crash, force close

### Aniyomi version

0.12.3.5-3393

### Android version

Android 10

### Device

Xiaomi Poco M3

### Other details

this is never hapend before update, maybe this cause of the apps not stable yet? or just me, please help me

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/jmir1/aniyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.12.3.5](https://github.com/jmir1/aniyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by Kaif31** [comment]
>

**Comment by jmir1** [comment]
this is the intended behaviour. go to settings > library > library update restrictions to change this.
