### ISSUE TITLE
Delete cached data that gets collected when watching online

### ISSUE THREAD

**Issue by some1onLSD** [jmir1/aniyomi#314]
### Describe your suggested feature

When you watch an episode/movie online (without downloading it) it keep cached data of that in the app directory and that is understandable so you won't wait a long time when you re-enter that same episode again but the problem is there's no choice of deleting this cached data, anyway I tried to watch a movie today and when I checked the app settings I noticed it's 500mb more and I couldn't clear it by tapping "clear cache" you can only clear it by tapping "clear storage" by then I'll lose my saved shows, fortunately I have root access on my phone and I found the cached data and I cleared it it was in data/data/com.xyz.jmir1..../files/media and I got rid of 500mb of cache. 

### Other details

I am writing this so I can ask if you could add a button that automatically deletes this by clicking it. Thanks for this amazing app.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/jmir1/aniyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.12.3.5](https://github.com/jmir1/aniyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by raeespulikkal** [comment]
There's an option now in the setting>advanced to clear chapter/episode data on app close in the data section. That should help reduce the space.

**Comment by 1onLSD** [comment]
it's on by default, didn't help that much I alwaysgo to the app root directory and delete files/media it helps reducing the space by a lot, watching just one episode of anime that is just 20min makes tge cache size around 150mb so right now doing it manually is the more sufficient.

**Comment by 12ohit** [comment]
Aniyomi got a new internal player now and it doesn't save the cache of buffer in app data anymore
