### ISSUE TITLE
Episode can't open

### ISSUE THREAD

**Issue by Samy20023** [jmir1/aniyomi#316]
When I tap to watch any episode they tell me:

 couldn't find any video links .

The problem in the new update 0.12.3.6 .

I try to open it in mpv player couldn't help .

Plaese, fix the problem. 

And thanks again .

**Comment by AuraGuardian2002** [comment]
Same on my end. Tested several animes on gogoanime and they are not working as post above described.

**Comment by glokta1** [comment]
If both of you have the problem specifically with Gogoanime, update its extension to 12.25. That fixed it for me.

**Comment by AuraGuardian2002** [comment]
I apologize for not getting back faster on this, but I went to the extensions tab that night and updated and it fixed the problem. Thank you for making a great app that does the heavy work for watching anime.

**Comment by glokta1** [comment]
@jmir1 I think we can close this issue now
