### ISSUE TITLE
Anime from any extensions isn't playing and downloading

### ISSUE THREAD

**Issue by Mrotakufreek** [jmir1/aniyomi#317]
### Steps to reproduce

1. When you trys to play any anime, then it says  couldn't find any video link 
2. When i am trying to download anime from gogo anime , then it shows error and  notification  shows list is empty

### Expected behavior

It should download and play anime seem lessly.

### Actual behavior

But its not playing and downloading any anime from all of extension.

### Aniyomi version

0.12.3.6-4498

### Android version

Android 11

### Device

Redmi note 8

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/jmir1/aniyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://aniyomi.jmir.xyz/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.12.3.5](https://github.com/jmir1/aniyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by raeespulikkal** [comment]
I just backed up my anime, fully uninstalled the app and its anime extentions, reinstalled and restored an the issue got fixed for me. I don't know if this is what fixed it or they did something...

**Comment by Sudip909** [comment]
Same as me not working anything and jmir always close my issue

**Comment by Whokrunalchauhan** [comment]
I tried updating the app to version ` 0.12.3.6-4504`  and for me when I play anime on-site via extension it plays but when I download and play it doesn't work for me. hope this issue of downloading gets fixed soon.

**Comment by giangalido** [comment]
Same as ne but now i always use external downloader (1DM) for anime, work fine for but i think it's a bit hassle for you because you need to download anime episode 1 by 1 and locate the destination path of each episode😅.

**Comment by giangalido** [comment]
Same as ne but now i always use external downloader (1DM) for anime, work fine for but i think it's a bit hassle for you because you need to download anime episode 1 by 1 and locate the destination path of each episode😅.
