### ISSUE TITLE
Nothing is Playing

### ISSUE THREAD

**Issue by Hanzixt** [jmir1/aniyomi#326]
### Steps to reproduce

Anime episodes are not playing

### Expected behavior

it should be playing episodes

### Actual behavior

No anime is loading. only black screen appears

### Aniyomi version

0.12.3.6-4504

### Android version

Android 10

### Device

Realme 5i

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/jmir1/aniyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://aniyomi.jmir.xyz/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.12.3.5](https://github.com/jmir1/aniyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by H3LLB0Y101** [comment]
Try updating the anime extension

**Comment by anifanthefist** [comment]
> ### Steps to reproduce
> 
> Anime episodes are not playing
> 
> ### Expected behavior
> 
> it should be playing episodes
> 
> ### Actual behavior
> 
> No anime is loading. only black screen appears
> 
> ### Crash logs
> 
> _No response_
> 
> ### Aniyomi version
> 
> 0.12.3.6-4504
> 
> ### Android version
> 
> Android 10
> 
> ### Device
> 
> Realme 5i
> 
> ### Other details
> 
> _No response_
> 
> ### Acknowledgements
> 
> - [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
> - [X] I have written a short but informative title.
> - [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/jmir1/aniyomi-extensions/issues/new/choose).
> - [X] I have tried the [troubleshooting guide](https://aniyomi.jmir.xyz/help/guides/troubleshooting/).
> - [X] I have updated the app to version **[0.12.3.5](https://github.com/jmir1/aniyomi/releases/latest)**.
> - [X] I have updated all installed extensions.
> - [X] I will fill out all of the requested information in this form.

I had the same problem with the v0.12.3.6 and it is better to downgrade to v0.12.3.5, and update the extensions. The latest update is full of problems.
