### ISSUE TITLE
Playback Options Bug (Video Player)

### ISSUE THREAD

**Issue by JemEm27** [jmir1/aniyomi#327]
### Steps to reproduce

There's a bug when I clicked the playback options

### Expected behavior

After using the playback options, I should be watching anime freely without hindrance.

### Actual behavior

After I clicked the playback options, my notification bar and navigation buttons (virtual buttons) is stuck. It feels as if there's a watermark.

### Aniyomi version

0.12.3.6

### Android version

Android 10

### Device

Realme 5i

### Other details

![IMG_20220110_040922](https://user-images.githubusercontent.com/97408566/148699020-92ca79be-296a-468b-9e97-16487be9ad3b.jpg)
![IMG_20220110_042249](https://user-images.githubusercontent.com/97408566/148699399-73bca406-938e-4373-99ca-f3117de8e5ab.jpg)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/jmir1/aniyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://aniyomi.jmir.xyz/help/guides/troubleshooting/).
- [x] I have updated the app to version **[0.12.3.5](https://github.com/jmir1/aniyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [x] I will fill out all of the requested information in this form.

**Comment by anifanthefist** [comment]
> ### Steps to reproduce
> 
> There's a bug when I clicked the playback options
> 
> ### Expected behavior
> 
> After using the playback options, I should be watching anime freely without hindrance.
> 
> ### Actual behavior
> 
> After I clicked the playback options, my notification bar and navigation buttons (virtual buttons) is stuck. It feels as if there's a watermark.
> 
> ### Crash logs
> 
> _No response_
> 
> ### Aniyomi version
> 
> 0.12.3.6
> 
> ### Android version
> 
> Android 10
> 
> ### Device
> 
> Realme 5i
> 
> ### Other details
> 
> ![IMG_20220110_040922](https://user-images.githubusercontent.com/97408566/148699020-92ca79be-296a-468b-9e97-16487be9ad3b.jpg)
> 
> ![IMG_20220110_042249](https://user-images.githubusercontent.com/97408566/148699399-73bca406-938e-4373-99ca-f3117de8e5ab.jpg)
> 
> 
> 
> ### Acknowledgements
> 
> - [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
> - [X] I have written a short but informative title.
> - [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/jmir1/aniyomi-extensions/issues/new/choose).
> - [X] I have tried the [troubleshooting guide](https://aniyomi.jmir.xyz/help/guides/troubleshooting/).
> - [X] I have updated the app to version **[0.12.3.5](https://github.com/jmir1/aniyomi/releases/latest)**.
> - [X] I have updated all installed extensions.
> - [X] I will fill out all of the requested information in this form.

Downgrade to v0.12.3.5 and update the extensions. 0.12.3.5 is not working for pretty everyone.

**Comment by glokta1** [comment]
same as #341. Discussion is taking place there. @jmir1 You can close this issue
