### ISSUE TITLE
notification won't disappear even after it finishes downloaded the anime

### ISSUE THREAD

**Issue by player2403** [jmir1/aniyomi#330]
### Steps to reproduce
![Screenshot_20220111-134625](https://user-images.githubusercontent.com/97405381/148888080-36514765-1e6c-4f99-8089-c5e85d009b82.png)

### Expected behavior

the notification should disappear after downloading

### Actual behavior

the notification still appears even after downloading

### Aniyomi version

0.12.3.6

### Android version

Android 9

### Device

Flare Tab Pro 2

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/jmir1/aniyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://aniyomi.jmir.xyz/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.12.3.5](https://github.com/jmir1/aniyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by glokta1** [comment]
same as #304 @jmir1

**Comment by jmir1** [comment]
Ok closing because it's a duplicate.
