### ISSUE TITLE
Not downloading

### ISSUE THREAD

**Issue by ITADORI-15** [jmir1/aniyomi#334]
@jmir1 
Bro the app isnt downloading the videos
The status is stuck at 0%
Doesnt move at all

**Comment by jmir1** [comment]
try clearing the download queue and try again.

**Comment by ITADORI-15** [comment]
Tried again and again

**Comment by AdarshK-Extension** [comment]
I faced same issue. For me it got resolved after I removed all installed extensions and the app and then reinstalled it.
