### ISSUE TITLE
Add Jisho.org dictionary on Raw Manga(Japanese)

### ISSUE THREAD

**Issue by Claude-Kenni** [jmir1/aniyomi#335]
### Describe your suggested feature

For instance, when reading raw manga(purely Japanese) there would be a tool that you can use to search for certain Japanese words this would help a learner of Japanese to quickly search, and thus, studying Japanese while reading manga would be a great help. 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/jmir1/aniyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.12.3.5](https://github.com/jmir1/aniyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by jmir1** [comment]
i don't think i will add this feature anytime soon but you can check out https://github.com/Rattlehead15/tachiyomiOCR if you don't know it already.
