### ISSUE TITLE
Anatomic should be able to fetch your internet 

### ISSUE THREAD

**Issue by Xediox-zex** [jmir1/aniyomi#338]
### Describe your suggested feature

Please make anatomic such that while downloading, it would fetch some internet, like on other apps like YouTube and Play store etc.  It can fetch the internet... 

### Other details

This will help those who have an internet connection but cant download or stream anime because of timeouts 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/jmir1/aniyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.12.3.5](https://github.com/jmir1/aniyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by jmir1** [comment]
i have no idea what you're saying right now
