### ISSUE TITLE
"couldn't not find any video link"

### ISSUE THREAD

**Issue by Sr6376** [jmir1/aniyomi#339]
### Steps to reproduce

Aniyomi anime is not and it shows error "couldn't not find any video link" on it.

### Expected behavior

Please fix it 

### Actual behavior

When you go to anime episode to watch the error throw you out of player.
![Screenshot_20220116-162130](https://user-images.githubusercontent.com/57284714/149657357-715bc785-be18-406c-aff5-0b7e814190fc.png)

### Aniyomi version

0.12.3.6

### Android version

Android 7,8

### Device

Gionee x1s

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/jmir1/aniyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://aniyomi.jmir.xyz/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.12.3.5](https://github.com/jmir1/aniyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by Zenitsu001** [comment]
we have the same problem bro AHHAHA
