### ISSUE TITLE
Android Navigation and Notification Bars stuck after accessing playback options in internal player

### ISSUE THREAD

**Issue by reiny2000** [jmir1/aniyomi#341]
### Steps to reproduce

1. Play any episode
2. Access playback options

### Expected behavior

 Navigation and Notification Bars should go away after you close the window
![Screenshot_20220116-201055](https://user-images.githubusercontent.com/40915736/149672814-cd786772-e6d6-43ab-9d18-1cbd366c21f1.png)

### Actual behavior

Navigation and Notification Bars remain visible
![Screenshot_20220116-201115](https://user-images.githubusercontent.com/40915736/149672838-8a9c4320-e3b6-4132-bcd7-38f147bd9d7f.png)

### Aniyomi version

0.12.3.6 and r4506

### Android version

Android 8.0.0

### Device

Moto Z

### Other details

I've tried all sources and the issue manifests the same on all of them.
I've tested versions 0.12.3.3 through 0.12.3.6. Only 0.12.3.3 doesn't have this issue.
It might be related to [issue 199](https://github.com/jmir1/aniyomi/issues/199) which is marked closed.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/jmir1/aniyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://aniyomi.jmir.xyz/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.12.3.5](https://github.com/jmir1/aniyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by glokta1** [comment]
Yeah issue #199 persists. On phones with notches (correct me if I'm wrong), the video also looks zoomed-in which wasn't the case before https://github.com/jmir1/aniyomi/commit/b526b6dbe2d0de4d8c33220f1e5dd2e822964616 

Example:
![image](https://user-images.githubusercontent.com/71697384/150082344-ee154cd7-b4f2-48f2-b757-a98b76daec0b.png)

**Comment by dm699** [comment]
>The video also looks zoomed-in which wasn't the case before [b526b6d](https://github.com/jmir1/aniyomi/commit/b526b6dbe2d0de4d8c33220f1e5dd2e822964616)
> 
> Example: ![image](https://user-images.githubusercontent.com/71697384/150082344-ee154cd7-b4f2-48f2-b757-a98b76daec0b.png)

That can be fixed by pressing this button 
![Screenshot_2022-01-19-13-08-45-63_dd604340c1d7941d42aee14dd16e00e8](https://user-images.githubusercontent.com/91522314/150085678-a7f26cb5-7c51-41e7-bd8d-8bbfd89db43b.jpg)

**Comment by glokta1** [comment]
@dm699 Oh :man_facepalming:. Thank you!

**Comment by glokta1** [comment]
So I did some looking around. The two main issues are navbar shows up:

- when exiting and reopening the app. 
This has an easy fix of moving `setVisibilities()` into an `onResume()` function. I've done this on my local build and can confirm it works.
- when using the options dialog.
This is more complicated. `onPause()` isn't called when the options dialog comes into the foreground, so `onResume()` isn't called and so `setVisibilities()` isn't called when we click away from the options dialog. Refer to [this](https://stackoverflow.com/questions/7240916/android-under-what-circumstances-would-a-dialog-appearing-cause-onpause-to-be) answer. 

One fix is to **create the dialog as an activity** so `onPause()` DOES get called. It does the job but seems rather clunky. I'm sure there's a better way to handle this but I don't have enough knowledge about Dialog boxes yet.
