### ISSUE TITLE
make ui a bit nicer

### ISSUE THREAD

**Issue by jmir1** [jmir1/aniyomi#348]

**Comment by BEEDELLROKEJULIANLOCKHART** [comment]
This is obviously too vague to be assistive.

**Comment by dm699** [comment]
no it's the creator themselves that opened this issue

**Comment by dm699** [comment]
> This is obviously too vague to be assistive.

No it's the creator that opened this issue

**Comment by BEEDELLROKEJULIANLOCKHART** [comment]
@dm699, oops. I have lost brownie-points.

**Comment by AdityaAnand99** [comment]
One way to make the UI nicer would be to base aniyomi not on tachiyomi but on tachiJ2K (a fork of tachiyomi) which is cleaner, better looking and feels less cluttered.

**Comment by jmir1** [comment]
> One way to make the UI nicer would be to base aniyomi not on tachiyomi but on tachiJ2K (a fork of tachiyomi) which is cleaner, better looking and feels less cluttered.

this will not happen in the forseeable future. by the way, this issue exists only for the puprose of tracking the development of the rewrite of the internal player.
