### ISSUE TITLE
[Feature request] Local library PDF support

### ISSUE THREAD

**Issue by ChinoKaffu** [jmir1/aniyomi#361]
### Describe your suggested feature

Support for scanning and opening pdf and able to read them as if it is manga. Something like a PPT slideshow would, with next and previous, zoom in and out, fit width or height. I've made this idea for the purpose of reading local light novels in pdf format in  aniyomi.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/jmir1/aniyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.12.3.5](https://github.com/jmir1/aniyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by ahmedgamal17** [comment]
@ChinoKaffu no manga support here open this issue on tachiyomi

**Comment by ChinoKaffu** [comment]
alright, my bad. Will close this issue.
