### ISSUE TITLE
Zoro.to(experimental)

### ISSUE THREAD

**Issue by Sparky3803** [jmir1/aniyomi#372]
### Describe your suggested feature

When I use zoro.to anime extension. I always watching sub anime but In the case of zoro.to their is no subtitles showing,please solve the problem.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/jmir1/aniyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.12.3.5](https://github.com/jmir1/aniyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by Sparky3803** [comment]
Please do something

**Comment by MedKing3** [comment]
That is why Zoro extension is still experimental. Try using another source.

**Comment by Claude-Kenni** [comment]
"Experimental"

**Comment by Sparky3803** [comment]
Got it, thanks!

**Comment by epiccreep** [comment]
Not a fix but with vlc you can use your subtitles or search and download the subs from vlc directly
