### ISSUE TITLE
Animepahe error 404

### ISSUE THREAD

**Issue by raeespulikkal** [jmir1/aniyomi#375]
I'm getting either 'HTTP Error 404' or 'error getting link' in animepahe extention on any anime I choose. Please look into it.

**Comment by Hellokittymaster09** [comment]
It might be a problem with the extensions at the moment /:

**Comment by raeespulikkal** [comment]
Atleast gogoanime works

**Comment by Hellokittymaster09** [comment]
Didn't knew that I only used animephae but thx for telling

**Comment by glokta1** [comment]
duplicate issue. see #366
