### ISSUE TITLE
I can't download aniyomi 

### ISSUE THREAD

**Issue by bonechan3** [jmir1/aniyomi#385]
### Crash logs

App download error 

### Aniyomi version

12.3.6

### Android version

10

### Device

A 11

### Other details

I can't download aniyomi When I download it an error occurs while downloading and stops, please solve this problem

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/jmir1/aniyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://aniyomi.jmir.xyz/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.12.3.5](https://github.com/jmir1/aniyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by alacazapp** [comment]
this also happens to me! does it say "needs authorization" too to you?

**Comment by arfiandasatritama** [comment]
> this also happens to me! does it say "needs authorization" too to you?

me too i cant download it, it always say"needs authorization"

**Comment by ahmedgamal17** [comment]
Try with VPN

**Comment by gamote21** [comment]
The vpn worked?

**Comment by mustafa895** [comment]
When I download aniyomi it give's me error that needs authorization
