### ISSUE TITLE
Add 9anime extension🙏

### ISSUE THREAD

**Issue by Nurul-5** [jmir1/aniyomi#386]
### Describe your suggested feature

Add 9anime extension please!!
Website: 9anime.to

### Other details

Website: 9anime.to

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/jmir1/aniyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.12.3.5](https://github.com/jmir1/aniyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by Nurul-5** [comment]
![Screenshot_2022-02-08-19-40-44-858_com android chrome](https://user-images.githubusercontent.com/99264427/152998686-da2c6655-5a3d-49a5-9fa2-746a3841a057.png)

**Comment by Whimfoome** [comment]
It would be hard (or even impossible) because 9anime has put many anti inspector features in their website. They did that to protect their content from being taken down or uploaded to other websites.
