### ISSUE TITLE
[Bug] Kitsu anime tracking not working

### ISSUE THREAD

**Issue by Reacien** [jmir1/aniyomi#39]
## Device information
* Tachiyomi version: Latest stable and preview version
* Android version: 10
* Device: Oneplus 5T

The kitsu anime tracking only shows the manga's and not the anime.
Checked it with myanimelist but that one does work, but it's not the site I use to keep my library updated.
Would be awesome if it can be fixed.

> Keep up the great work!

**Comment by jmir1** [comment]
forgot to close. was fixed with https://github.com/jmir1/aniyomi/commit/9e2db50b77fdd99578eddc55d07cc343bacb049b.
