### ISSUE TITLE
Sflix and Dopebox extensions are not working

### ISSUE THREAD

**Issue by AmitrajitDas** [jmir1/aniyomi#390]
### Steps to reproduce

1. Adding any movie or show from the above extensions.
2. Playing it

### Expected behavior

The media should play within 5 seconds

### Actual behavior

After 5 seconds or so it exits from the media full screen and sometimes shows the alert for error getting links/ try again.

### Aniyomi version

0.12.3.6

### Android version

Android 11

### Device

Vivo V15

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/jmir1/aniyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://aniyomi.jmir.xyz/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.12.3.5](https://github.com/jmir1/aniyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by AdityaAnand99** [comment]
I'm having the same problem, but worse. While earlier videos would play after a couple tries, now I just get the 'timeout' message.
