### ISSUE TITLE
Anime Extension- ANIMESUGE

### ISSUE THREAD

**Issue by Nova-Kamikaze** [jmir1/aniyomi#393]
### Describe your suggested feature

Animesuge is a great website to watch anime with 100% uptime and good search functionality and huge library

### Other details

Site address:- https://animesuge.to/

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/jmir1/aniyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.12.3.5](https://github.com/jmir1/aniyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by sriramvytla** [comment]
ok

**Comment by jmir1** [comment]
> ok
> 

ok
