### ISSUE TITLE
MPV crashes the app

### ISSUE THREAD

**Issue by XXDRD** [jmir1/aniyomi#395]
### Steps to reproduce

Enable external media player
Select mpv
Click on a downloaded episode 

### Expected behavior

Video to play

### Actual behavior

App crashes 

### Crash logs

https://bin.kv2.dev/~62079577410e7c32e6699252

### Aniyomi version

 0.12.3.6

### Android version

Android 12

### Device

Realme 3 pro

### Other details

https://user-images.githubusercontent.com/88576601/153708911-7e289a85-9cd3-441d-b290-f00101e25684.mp4

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/jmir1/aniyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://aniyomi.jmir.xyz/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.12.3.5](https://github.com/jmir1/aniyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by calimari0** [comment]
same issue here, can you do me a favour and see if it also happens with non downloaded episodes? it only happens for me with downloaded episodes, on all external players (mpv, vlc, mx)

**Comment by XXDRD** [comment]
No, it doesn't happen with non downloaded episodes. Streaming works perfectly fine!

**Comment by eokwuanga** [comment]
Happens to me too, MX player works but it takes a long time to open after you select a video, MPV crashes the app.

**Comment by XXDRD** [comment]
it works now
