### ISSUE TITLE
Auto play next episode

### ISSUE THREAD

**Issue by Ashish-add** [jmir1/aniyomi#406]
### Describe your suggested feature

I need to manually click to change the episode, it would be better if after completion of one episode it would automatically go to next episode. 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/jmir1/aniyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.12.3.5](https://github.com/jmir1/aniyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by Quickdesh** [comment]
@jmir1 I have the code made for an auto play option, but it's for the current player (non-mpv one) , should I PR it?

**Comment by jmir1** [comment]
> @jmir1 I have the code made for an auto play option, but it's for the current player (non-mpv one) , should I PR it?

no you dont need to make a PR because the whole player is going to be gone anyways

**Comment by ErenGrisha** [comment]
So just wanted to know that when the new player would be available and if it will be like the shiro app player or something different.

**Comment by mapreri** [comment]
Hello, and sorry for resurrecting such an old bug report.

It's not clear to me what's the status of this feature proposal.  To this date, current stable (v0.12.3.10) does not seem to implement this feature (I can't deny I might be blind and have missed it, but…).

Is it still in the plans, or what else?

**Comment by jmir1** [comment]
> Hello, and sorry for resurrecting such an old bug report.
> 
> It's not clear to me what's the status of this feature proposal. To this date, current stable (v0.12.3.10) does not seem to implement this feature (I can't deny I might be blind and have missed it, but…).
> 
> Is it still in the plans, or what else?

I closed the issue because it has been implemented for a long time. But because of some issues, the current development version of Aniyomi hasn't been published to the stable release channel.
You can try it out here though: https://github.com/jmir1/aniyomi-mpv-beta/releases/latest
