### ISSUE TITLE
Notification bar not hiding completely after accesing playback options

### ISSUE THREAD

**Issue by Sc0o0p** [jmir1/aniyomi#407]
## Steps to reproduce
1. Reproduce any video
2. Click on playback options

## Issue
This issue is related to #199, but it's **not** the same because that was fixed already. Before v0.12.3.6, the bar would show, turn opaque and resize the height of the player for a few pixels. On v0.12.3.6 (and thanks to #378) this was somewhat fixed, but the notification bar still persists, although it's now over the player and it doesn't resize the video.

# Screenshots
### Before accesing playback options
![Screenshot_20220220_120339_xyz jmir tachiyomi mi](https://user-images.githubusercontent.com/37896740/154839658-44412bea-b3aa-4141-b5a1-7e3cf1a27d74.jpg)

### After accesing playback options
![Screenshot_20220220_120348_xyz jmir tachiyomi mi](https://user-images.githubusercontent.com/37896740/154839656-0bfe3fbe-de6d-4538-a978-f5cec241b1ba.jpg)
Notice that the notification bar isn't completely hidden.

**Comment by Firu822** [comment]
same (when switching to dub/sub)

**Comment by jmir1** [comment]
#378 is not in the 0.12.3.6 version. its only in the preview version right now.
