### ISSUE TITLE
Episodes are not opening

### ISSUE THREAD

**Issue by Chanishyt** [jmir1/aniyomi#414]
### Steps to reproduce

![Screenshot_20220224-113248_Aniyomi](https://user-images.githubusercontent.com/100331075/155467491-2e33e8e0-d664-4c80-b62c-ede290e361c3.jpg)
That' what happing 

### Expected behavior

They should be playong the episode

### Actual behavior

They are not evwn responding

### Crash logs

App version: 0.12.3.6 (standard, 67c506d, 72, 2022-01-06T02:47Z)
Android version: 11 (SDK 30)
Android build ID: RP1A.200720.012.A505FDDS9CVA3
Device brand: samsung
Device manufacturer: samsung
Device name: a50
Device model: SM-A505F
Device product name: a50dd

### Aniyomi version

0.12.3.6

### Android version

Android 11

### Device

Samsung galaxy a50

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/jmir1/aniyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://aniyomi.jmir.xyz/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.12.3.5](https://github.com/jmir1/aniyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by NeutronPool** [comment]
Yeah, for me too

**Comment by ahmedgamal17** [comment]
Update the extension to fix it

**Comment by NeutronPool** [comment]
> 

thanks mate... it worked

**Comment by tusharsharma7791** [comment]
Same problem here also

**Comment by tusharsharma7791** [comment]
Problem solved : just update the extension

**Comment by fal3n-4ngel** [comment]
Update the extensions to Fix it

**Comment by Spikebinger99** [comment]
Gogo anime is fucked now cant even stream some animes anymore and cant even have a option the option for quality anymore goggles was the fastest and the smoothest app, on the other apps you cant watch with getting a buffer
