### ISSUE TITLE
animekisa.tv extension

### ISSUE THREAD

**Issue by seekwoo** [jmir1/aniyomi#421]
### Describe your suggested feature

please add "animekisa.tv"☑️ extension this domain works fine in my region and also better than other "anime kisa"❌ website. fully appreciate yours hardwork for us Thanks in advance ❤️

### Other details

![Screenshot_2022-03-01-23-21-37-961_com android chrome](https://user-images.githubusercontent.com/100714133/156218989-c1b953c9-2eff-44e4-ba7e-d5fb3ac67c7f.jpg)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/jmir1/aniyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.12.3.5](https://github.com/jmir1/aniyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by ahmedgamal17** [comment]
This is gogo scraper and we have gogo already
