### ISSUE TITLE
Have a fully automatic "install/update all" feature for extensions

### ISSUE THREAD

**Issue by AEther-AEternum** [jmir1/aniyomi#423]
### Describe your suggested feature

Like how SD Maid has an accessibility service to automatically clear app caches by automatically going to each app in settings and clicking "clear cache", all by itself, so you could leave it be and it would do all the work for you. There should be an "install all" button, and clicking "install" on each package should be automatic, hence the requirement of an accessibility service. Some people want to have as many sources as possible (like me), and it's kinda tedious to try and install all extensions manually. I did it though. And now I have to manually update them all as well, since I have to press "install" on each package still, "update all" merely starts each download and runs each apk, rather than a one-press then leave be and wait situation. 

### Other details

I know this is mainly a tachiyomi problem, since that has the ridiculous amount of extensions, not aniyomi. But I use aniyomi, not tachiyomi, and I would mostly like to see this feature here. 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/jmir1/aniyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.12.3.5](https://github.com/jmir1/aniyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by tusx** [comment]
I believe clicking on install is same as when you click on YES in windows when you run it as administrator. There is no actall way to bypass it. Its a security features that requires the user to click on install.
You have to click on install at the very least there is no other way around it.

**Comment by AEther-AEternum** [comment]
> I believe clicking on install is same as when you click on YES in windows when you run it as administrator. There is no actall way to bypass it. Its a security features that requires the user to click on install. You have to click on install at the very least there is no other way around it.

Oh, well that sucks. Sounds like I should just deal with it.
