### ISSUE TITLE
Pass anime streaming info into other app

### ISSUE THREAD

**Issue by husudosu** [jmir1/aniyomi#428]
### Steps to reproduce

1. Open app,
2. Go to any anime resource (tried Gogoanime, 9anime, AnimePahe),
3. Select any show ,
4. Push and hold an episode list item,
5. Use the last icon at the floating dialog.

### Expected behavior

The app should open an app selector  where can I select, then Aniyomi passes the intent data including HTTP-Header-fields and URL for the app. For example I made a MPV remote app and it handles intent from Aniyomi like this [link](https://github.com/husudosu/mpv-remote-app/blob/a46dca08447a7092e3dc42d8c320a413983144c1/src/Container.vue#L185)

### Actual behavior

On tapping Aniyomi immeditly starts playing on internal player. This wasnt't the behavior until 2 weeks ago.

### Aniyomi version

0.12.3.6

### Android version

Android 11, 12

### Device

Xiaomi Redmi Note 10 Pro, Xiaomi Redmi 6

### Other details

- App reinstalled

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/jmir1/aniyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://aniyomi.jmir.xyz/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.12.3.5](https://github.com/jmir1/aniyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by jmir1** [comment]
you need to to turn on "always use external player" in the player settings or long press an episode and click the bottom right icon to open in an external app.
