### ISSUE TITLE
Change Logo: Notification Bar, and More Tab

### ISSUE THREAD

**Issue by Mano5JP** [jmir1/aniyomi#431]
### Describe your suggested feature

On the notification and more page, Aniyomi still has the Tachiyomi app logo.

Suggestion: Because it is so basic, it should have its own logo to make it more distinct.

### Other details

You'll be confused with the Main Tachiyomi app if you don't check the notification bar.

On Notification Bar
![Screenshot_20220309-151607_Aniyomi](https://user-images.githubusercontent.com/64928088/157440655-3fe5fc3c-9262-4efc-80e5-9ff31bf6c2ad.jpg)

On More Tab
![Screenshot_20220309-151619_Aniyomi](https://user-images.githubusercontent.com/64928088/157440678-05bd4a6a-d149-429d-a487-238bd13dd3d9.jpg)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/jmir1/aniyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.12.3.5](https://github.com/jmir1/aniyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by jmir1** [comment]
closed by 171772a0a82fb3949c46e7400306de5a592d6bf1
