### ISSUE TITLE
Add Extension 

### ISSUE THREAD

**Issue by fahad121264** [jmir1/aniyomi#432]
### Describe your suggested feature

I would like to add an Arabic source that i think would be really help and thanks in advance
  https://cimalek.club/
 https://cinema4up.tv/

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/jmir1/aniyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.12.3.5](https://github.com/jmir1/aniyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by Mano5JP** [comment]
Open issues on correct repo.

![ext repo](https://user-images.githubusercontent.com/64928088/157452014-7b6b1e3a-aabe-4937-a1c6-b26e72b4fbb1.jpg)
