### ISSUE TITLE
Italian sources 

### ISSUE THREAD

**Issue by ilpk94** [jmir1/aniyomi#447]
Could you add two Italian sources please? 🙏
dreamsub.cc
animeworld.tv

**Comment by jmir1** [comment]
wrong repo for this issue, and also they already exist, along with two more 🤦

**Comment by jmir1** [comment]
https://github.com/jmir1/aniyomi-extensions/tree/master/src/it

**Comment by ilpk94** [comment]
You're right. I hadn't used aniyomi for a long time and didn't think about checking. Sorry
