### ISSUE TITLE
Auto update not working 

### ISSUE THREAD

**Issue by priyanshu8017** [jmir1/aniyomi#452]
### Steps to reproduce

1. The auto update is set to 12 hours
2. Update restrictions set to none
3. update library restrictions set to : only ongoing anime and manga

When ever I open aniyomi i have to update its library manually. Fix it or tell me if I'm doing anything wrong in the settings.

### Expected behavior

The update should work automatically. In early versions whenever I open Aniyomi it was updating itself automatically 

### Actual behavior

Now I'm going to the 'updates' section an tapping the force update button manually 

### Aniyomi version

0.12.3.6

### Android version

11

### Device

Xiaomi Redmi Note 9 (10X4G)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/jmir1/aniyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://aniyomi.jmir.xyz/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.12.3.5](https://github.com/jmir1/aniyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by ItzWarLockOp** [comment]
![IMG_20220324_154408](https://user-images.githubusercontent.com/98949064/159895701-6166bc6e-867d-4e2c-922b-a159652a1e33.jpg)
![IMG_20220324_155109](https://user-images.githubusercontent.com/98949064/159895705-65f0327e-3eb3-4377-9360-0bf9cb340b62.jpg)

Same thing Happening with me to . But in my case even after manually updating the library the number of episode not updating there.

**Comment by tusx** [comment]
Have your made any changes in settings library and anime category.
I also had the same issue. 
All you need to do is select which lable you wanna updat and which you dont wanna update and it should work as normal.
The location is settings > library > and then select both anime and managa
Should look something like this when you are done.

![Screenshot_20220325-102015_Aniyomi.jpg](https://user-images.githubusercontent.com/33265258/160150251-3547e3e7-6b0c-4abe-a437-dd2614a74493.jpg)

**Comment by shanawajahammed** [comment]
I have also same problems

**Comment by priyanshu8017** [comment]
After selecting the labels i dont want do update, it fixed

**Comment by priyanshu8017** [comment]
After selecting the labels i dont want do update, it fixed

**Comment by Exonymos** [comment]
Same problem but even the force update isn't doing anything
