### ISSUE TITLE
Backup Settings

### ISSUE THREAD

**Issue by AmateurYash** [jmir1/aniyomi#455]
### Describe your suggested feature

By making it so that all settings also get backed up along with the backup file of all the content.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/jmir1/aniyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.12.3.5](https://github.com/jmir1/aniyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by jmir1** [comment]
see #424
