### ISSUE TITLE
Adding a Light novel section 

### ISSUE THREAD

**Issue by Jjjggh** [jmir1/aniyomi#461]
### Describe your suggested feature

If some light novel extentions get added and get a dedicated section just like the anime or the manga this would be the ultimate app ever made .
There's already an app that does the light novel part but nothing else (shosetsu) but it isn't that well , so if you are able to add some extentions for light novels and a dedicated section for them it would be ultra amazing.  It can be also added in the sittings for the users to choose what type the want . 
For example if someone wants only anime to watch,  then the manga part is useless for that person and so with the light novels part , 

Your app is already fr**king amazing and i wish you the best 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/jmir1/aniyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.12.3.5](https://github.com/jmir1/aniyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by CR1MS0N24** [comment]
I think there's another app that's busy doing that know as saikou

**Comment by jmir1** [comment]
#70

**Comment by Pyhcho** [comment]
Man that gonna be lit

**Comment by jmir1** [comment]
> Man that gonna be lit

It would be sick
