### ISSUE TITLE
Add moenime extension

### ISSUE THREAD

**Issue by srenk** [jmir1/aniyomi#463]
### Describe your suggested feature

![Screenshot_20220328-103949_Chrome](https://user-images.githubusercontent.com/77874973/160322580-46d6d912-b6b7-444f-a8a5-879747dd6af2.jpg)

### Other details

https://moenime.web.id/

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/jmir1/aniyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.12.3.5](https://github.com/jmir1/aniyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by jmir1** [comment]
> If this is an issue with an extension, I should be opening an issue in the extensions repository.
