### ISSUE TITLE
suggestions for new sites in Spanish

### ISSUE THREAD

**Issue by ArchVIII** [jmir1/aniyomi#477]
### Describe your suggested feature

Name: AnimeOnline = Anime
Link: https://www1.animeonline.ninja/
Language: Spanish

Name: Tioanime = Anime
Link: https://tioanime.com/
Language: Spanish

Name: MundoDonghua = Donghua
Link: https://www.mundodonghua.com/
Language: Spanish

Name: Jkanime = Anime
Link: https://jkanime.net/
Language: Spanish

Name: Ironanime = Anime
Link: https://www1.ironanime.live/
Language: Spanish

Name: AnimeBlix = Anime in Spanish
Link: https://animeblix.com/
Language: Spanish

Name: Veranime = Anime
Link: https://www.veranime.org/
Language: Spanish

Name: AnimeMovil = Anime
Link: https://www.animemovil2.com/
Language: Spanish

Name: Henaojara = Anime in Spanish
Link: https://henaojara.com/
Language: Spanish

Name: Otakustv = Anime
Link: https://www1.otakustv.com/
Language: Spanish

Name: AnimeSpace = Anime
Link: https://animespace.tv/
Language: Spanish

Name: Animegt = Anime
Link: https://animegt.top/
Language: Spanish

Name: Azaku = Anime
Link: https://azaku.net/
Language: Spanish

Name: Animeflex = Anime/Series
Link: https://animeflex.tv/
Language: Spanish

Name: Zyanime = Anime
Link: https://zyanime.com/
Language: Spanish

Name: Porygonsubs = Anime
Link: https://porygonsubs.com/
Language: Spanish

Name: DoramasYt = Doramas
Link: https://www.doramasyt.com/
Language: Spanish

Name: DoramasJc= Doramas
Link: https://www.doramasjc.com/
Language: Spanish

Name: Doramasmp4 = Doramas
Link: https://doramasmp4.io/
Language: Spanish

Name: Seriesflix = Series / Anime
Link: https://seriesflix.la/
Language: Spanish

Name: Peliculasflix = Series / Anime / Movies
Link: https://peliculasflix.co/
Language: Spanish

Name: AsiLiveAction = Doramas / Series
Link: https://asialiveaction.com/
Language: Spanish

Name: Homecine = Series / Anime
Link: https://homecine.tv/
Language: Spanish

Name: Gnula = Series / Movies / Animes
Link: https://gnula.nu/
Language: Spanish

Name: Pelispop = Movies / Animes / Series
Link: https://pelispop.me/
Language: Spanish

Name: Cuevana 3 = Movies / Animes
Link: https://ww3.cuevana.pro/
Language: Spanish

Name: HentaiTk = Hentai
Link: https://hentaitk.net/
Language: Spanish

Name: Yohentai = Hentai
Link: https://yohentai.net/
Language: Spanish

Name: Latinohentai = Hentai 
Link: https://latinohentai.com/
Language: Spanish

Name: Tiohentai = Hentai
Link: https://tiohentai.com/
Language: Spanish

Name: Hentai ID = Hentai / Manga / Jav
Link: https://hentai-id.tv/ 
Link 2: https://hentai-id.tv/archivos/jav/
Language: Spanish

Name: Verhentai = Hentai
Link: https://verhentai.top/
Language: Spanish

Name: Ver-Hentai = Hentai
Link: https://www.ver-hentai.online/
Language: Spanish

Name: HentaiMama = Hentai
Link: https://hentaimama.io/
Language: Spanish

Name: Eshentai = Hentai
Link: https://www.eshentai.tv/
Language: Spanish

Name: VeoHentai = Hentai
Link: https://veohentai.com/
Language: Spanish

Name: HentaiWorld = Hentai
Link: https://hentaiworld.tv/
Language: Spanish

Name: MuchoHentai = Hentai
Link: https://muchohentai.com/
Language: Spanish

Name: Underhentai = Hentai
Link: https://www.underhentai.net/
Language: Spanish

Name: Jav Most = Jav
Link: https://www5.javmost.com/
Language: Spanish

Name: Animeflv.ru = little known anime
Link: https://animeflv.ac/
Language: Spanish

Name: Yugilatin = Anime
Link: https://yugilatin.blogspot.com/
Language: Spanish

Name: Pelisflix = Movies / Animes
Link: https://pelisflix.li/
Language: Spanish

### Other details

I know that I put many suggestions from various sources and I did not put them because I wanted to demand.
I put it so that you can know which are the most used Spanish pages by Spanish speaking users, I do not ask you to put all the sources today, but when you have time to spare.
Here in Latin America many of us value your work since Aniyomi is the best application. Greetings from Peru

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/jmir1/aniyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.12.3.5](https://github.com/jmir1/aniyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by jmir1** [comment]
> If this is an issue with an extension, I should be opening an issue in the extensions repository.
