### ISSUE TITLE
Android bar doesn't disappear

### ISSUE THREAD

**Issue by Palloxin** [jmir1/aniyomi#481]
### Steps to reproduce

https://user-images.githubusercontent.com/75091899/161092248-7aacc91e-93ba-4de7-bc6b-672a3e669d45.mp4

you can see in the video how the android bar is not transparent anymore and in a fixed state(doesn't move/hide) covering the right part of the screen

### Expected behavior

the android bar should hid itself

### Actual behavior

the android bar remain in a fixed state.

### Aniyomi version

0.12.3.6

### Android version

Android 8

### Device

Huawei p8 lite 2017

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/jmir1/aniyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://aniyomi.jmir.xyz/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.12.3.5](https://github.com/jmir1/aniyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by Palloxin** [comment]
i have just discovered that clicking on the gear of the player has the exact same effect on the android bar.

https://user-images.githubusercontent.com/75091899/161094069-180a8c88-bd1f-417c-bcba-5b2fc8246cba.mp4

**Comment by ahmedgamal17** [comment]
Use preview version

**Comment by jmir1** [comment]
#199
