### ISSUE TITLE
Android bar in a fixed state

### ISSUE THREAD

**Issue by Palloxin** [jmir1/aniyomi#482]
### Steps to reproduce

I know this bug has been fixed on the preview, but the same bug can be trigged in another way on the preview.
I don't know for other devices but here is how to trigger it.
1. watch and episode openidng the internal player
2. trigger the screen recording option of your android. for my phone you do it pressing together on-button+up-volume button

![Screenshot_20220403-175412](https://user-images.githubusercontent.com/75091899/161436670-c1805aaa-727c-4d58-bba1-2a8385894fdd.jpg)

![Screenshot_20220403-175421](https://user-images.githubusercontent.com/75091899/161436680-85b85c00-637e-4889-b057-f6965e43b1b4.jpg)

### Expected behavior

the android bar should not be in a fixed state but disappear

### Actual behavior

android bar in a fixed state.

### Aniyomi version

r4507

### Android version

Android 8

### Device

Huawei p8 lite 2017

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/jmir1/aniyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://aniyomi.jmir.xyz/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.12.3.5](https://github.com/jmir1/aniyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by jmir1** [comment]
See #199

**Comment by Palloxin** [comment]
> See #199

well, the bug is the same and already solved partially on the preview (the screen come from the preview) but can still be triggered as i explained above. can you re-open it?

**Comment by Quickdesh** [comment]
Feature has been added in the beta, wait for update to stable
