### ISSUE TITLE
Subtitle on movies

### ISSUE THREAD

**Issue by glorymaster** [jmir1/aniyomi#483]
### Describe your suggested feature

thank u for this app, may we know if subtitles on movies are on development or will be available on the upcoming updates ? thank u so  much

### Other details

thank u

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/jmir1/aniyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.12.3.5](https://github.com/jmir1/aniyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by jmir1** [comment]
Yes it will come in one of the next updates
