### ISSUE TITLE
Problem with downloads

### ISSUE THREAD

**Issue by pavonismc** [jmir1/aniyomi#484]
### Steps to reproduce

True to download from sflix or any other western movies extension

### Expected behavior

The download should with no problems and should only stop once once the entire files in storage

### Actual behavior

Instead it shows you how I try to start downloaded if you look into your folder you will find the temp file but it immediately pauses the download at 0% and whenever you try to resume it passes it again over and over can you make it so that it doesn't pass and continuous persisting with the download

### Aniyomi version

The current version of aniyomi

### Android version

Android 12

### Device

Oppo reno5

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/jmir1/aniyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://aniyomi.jmir.xyz/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.12.3.5](https://github.com/jmir1/aniyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by jmir1** [comment]
This should be fixed in the preview version of aniyomi.

**Comment by pavonismc** [comment]
thank you very much
