### ISSUE TITLE
New extension for real life movies 

### ISSUE THREAD

**Issue by yxsh-exe** [jmir1/aniyomi#493]
### Describe your suggested feature

Sir I would like to add new extension at the anime section as it should be easy and convenient as we can watch anime and movies both in one app 
Here the link :https://ww.thesoap2day.com/soaphome/ 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/jmir1/aniyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.12.3.5](https://github.com/jmir1/aniyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by Jjjggh** [comment]
Bro 
It's already here 

Use Sflix extension 
It has hugh-hugh- hughmaaan movies and series if you are for some reason into that weird shit
