### ISSUE TITLE
Mal-Sync

### ISSUE THREAD

**Issue by GodTaisaku** [jmir1/aniyomi#494]
### Describe your suggested feature

Is it possible to have mal-sync in aniyomi? I also watch anime on my laptop but the battery dies pretty fast. So, it would be pretty convenient if aniyomi knows what timestamp I'm in by using mal-sync. Like, watching from laptop/PC to phone. I don't if it's possible tho. 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/jmir1/aniyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.12.3.5](https://github.com/jmir1/aniyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by Quickdesh** [comment]
I dont believe MAL saves the timestamp of a specific episode

**Comment by GodTaisaku** [comment]
> I dont believe MAL saves the timestamp of a specific episode

Not MAL. Mal-Sync. It's a chrome extension. It automatically updates your MyAnimeList(also kitsu and anilist) when you watch on anime websites. Search it up for more details.

**Comment by Quickdesh** [comment]
There is no way for the app to communicate with a  browser extension. If it had a public location where it stored the data, then and only then can aniyomi use it. In this case, the connection is MAL, which doesn't support episode save data.

So this feature isn't possible

**Comment by GodTaisaku** [comment]
> There is no way for the app to communicate with a browser extension. If it had a public location where it stored the data, then and only then can aniyomi use it. In this case, the connection is MAL, which doesn't support episode save data.
> 
> So this feature isn't possible

I see, that's a bummer then. You can close this now
