### ISSUE TITLE
New source 

### ISSUE THREAD

**Issue by Akashi123-deep** [jmir1/aniyomi#499]
New source for anime
Name : anime iat
Link : https://www.animeiat.tv/
Language : Arabic

**Comment by Akashi123-deep** [comment]
![Screenshot_20220409-012716_Chrome](https://user-images.githubusercontent.com/102795903/162551193-050d638c-0ced-495d-9531-39b13e9895f0.jpg)

**Comment by MoonLGH** [comment]
wrong repositories buddy
https://github.com/jmir1/aniyomi-extensions
