### ISSUE TITLE
Kuronime Change Domain

### ISSUE THREAD

**Issue by HikariHeaven** [jmir1/aniyomi#503]
### Steps to reproduce

1. Open kuronime ext
2. All anime can't appeared
3. Just appeared text "185.231.223.254: NXDOMAIN". And you just can access that use an open on WebView 

### Expected behavior

This should happen to access in normal mode, not use open on webview

### Actual behavior

This happened instead cause Kuronime change them domain to 185.231.223.254

### Crash logs

--------- beginning of system
--------- beginning of main
04-10 10:56:17.760 14636 14636 E Parcel  : Reading a NULL string not supported here.
App version: 0.12.3.6-4513 (standard, 98b7e1dbe, 72, 2022-04-01T17:57Z)
Android version: 11 (SDK 30)
Android build ID: RMX2180_11_C.11
Device brand: realme
Device manufacturer: realme
Device name: RMX2180
Device model: RMX2180
Device product name: RMX2180T2

App version: 0.12.3.6-4513 (standard, 98b7e1dbe, 72, 2022-04-01T17:57Z)
Android version: 11 (SDK 30)
Android build ID: RMX2180_11_C.11
Device brand: realme
Device manufacturer: realme
Device name: RMX2180
Device model: RMX2180
Device product name: RMX2180T2

### Aniyomi version

0.12.3.6-4513

### Android version

Android 11

### Device

Realme C15

### Other details

![Screenshot_2022-04-10-10-51-47-21_423fe07c33ed17f15a4e92e5e3a15972](https://user-images.githubusercontent.com/61365229/162601007-842abe48-1a44-4944-98e3-4a993c1a10d4.jpg)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/jmir1/aniyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://aniyomi.jmir.xyz/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.12.3.5](https://github.com/jmir1/aniyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by jmir1** [comment]
> If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/jmir1/aniyomi-extensions/issues/new/choose).
