### ISSUE TITLE
PLEASE ADD MORE DOMAIN OF ANIMEPAHE

### ISSUE THREAD

**Issue by Adi432144** [jmir1/aniyomi#509]
### Describe your suggested feature

As per ANIMEPAHE updated their domain for better anime 
The available domain in your app is old domain

### Other details

The new domain in animephae is 
https://animepahe.ac/ so please update this domain in your app 🙏🙏🙏

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/jmir1/aniyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.12.3.5](https://github.com/jmir1/aniyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by sinnghabhay80** [comment]
Actually I don't think that this site is from the same developer as they are not even promoting it on their original site and the whole layout is also kind of messed up right now.
