### ISSUE TITLE
Anime search shows limited results

### ISSUE THREAD

**Issue by sdMickey** [jmir1/aniyomi#51]
While searching for anime like one piece. I recieved many results like ovas and movies but not the main anime. I was unable to find the anime as only 14 results were shown. If the developer sees this comment, first of all amazing app dude, please increase the number of anime you see while searching. https://user-images.githubusercontent.com/54260201/120678954-483d4900-c4b6-11eb-94d5-5d1c36a5f406.mp4

**Comment by jmir1** [comment]
what extension are you using?

**Comment by sdMickey** [comment]
4anime

**Comment by sdMickey** [comment]
> what extension are you using?

4anime

**Comment by jmir1** [comment]
Closing because this was an issue specific to one extension that's now deprecated
