### ISSUE TITLE
CAN YOU ADD THIS COMIC WEBSITE IN MANGA EXTENSION

### ISSUE THREAD

**Issue by Adi432144** [jmir1/aniyomi#513]
### Describe your suggested feature

Hello there I recently found a comic website which has various amount of comic DC & other 
Please make sure add this website as extension in maga extension

### Other details

I know you have other websites like this but I don't think so this is best so make sure to add
The website is 👇
https://readcomiconline.li/

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/jmir1/aniyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.12.3.5](https://github.com/jmir1/aniyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by Adi432144** [comment]
Thanks for replying to me 😃

**Comment by CR1MS0N24** [comment]
I think that extension was available at some time
