### ISSUE TITLE
seasons and episode

### ISSUE THREAD

**Issue by glorymaster** [jmir1/aniyomi#516]
### Describe your suggested feature

hey guy's thanks for the reply on my last feature request . Can I request a feature where in a tv series seasons and episodes are divided and not combined.. thank you so much and please refer to the image I attached for reference.. thank u.
![Screenshot_20220413_000753](https://user-images.githubusercontent.com/71760685/163007049-477923fc-1d18-4e73-adb5-28bcca655761.jpg)

![Screenshot_20220413_000819](https://user-images.githubusercontent.com/71760685/163007517-4ba2e5aa-ae41-4fef-86e6-1a37fd8b5566.jpg)

### Other details

hope this will be implement soon. 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/jmir1/aniyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.12.3.5](https://github.com/jmir1/aniyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by aldehxde** [comment]
was this ever resolved? I was looking to curate my local files. but I can't break them down per season

**Comment by glorymaster** [comment]
> was this ever resolved/implemented? I was looking to curate my local files. but I can't break them down per season

it was not solved as most of the extensions are down...and I think they will never add extensions for movies and series in the future..

**Comment by aldehxde** [comment]
> > was this ever resolved/implemented? I was looking to curate my local files. but I can't break them down per season
> 
> it was not solved as most of the extensions are down...and I think they will never add extensions for movies and series in the future..

i was actually referring to the feature you were suggesting, because some animes have multiple seasons. it would be nice if we could sort them in the local folder by season instead of listing 100+ episodes in one go just like one piece

**Comment by Secozzi** [comment]
> was this ever resolved/implemented? I was looking to curate my local files. but I can't break them down per season

See #289

**Comment by aldehxde** [comment]
> > was this ever resolved/implemented? I was looking to curate my local files. but I can't break them down per season
> 
> See [#289](https://github.com/aniyomiorg/aniyomi/issues/289)

this has to do with the naming I was looking for more something like this https://user-images.githubusercontent.com/71760685/163007517-4ba2e5aa-ae41-4fef-86e6-1a37fd8b5566.jpg

**Comment by glorymaster** [comment]
yeah yeah ..I get it, what I mean is they stop I think at some point because of some dmca notice...and the features that are requested has never been implemented

**Comment by Secozzi** [comment]
> yeah yeah ..I get it, what I mean is they stop I think at some point because of some dmca notice...and the features that are requested has never been implemented

This isn't true. The dmca notice was only for the extensions, so we won't work on any extensions. There were no dmca notice to the app though, and development is still continuing.

**Comment by aldehxde** [comment]
hope they will implement on the next update your suggested feature. I'm really not into streaming, that's why I try to curate my watchlist and your suggested feature would definitely be a big qof improvement.

**Comment by glorymaster** [comment]
i hope so.

**Comment by jmir1** [comment]
> was this ever resolved/implemented? I was looking to curate my local files. but I can't break them down per season

It's definitely planned for this year, for me personally. Not sure when I'll get to it
