### ISSUE TITLE
Anime player optimizations.

### ISSUE THREAD

**Issue by Chhatreshkhatri** [jmir1/aniyomi#52]
Slide on screen to seek video in player as well transparent player layout.
![IMG_20210607_105120](https://user-images.githubusercontent.com/84904668/120962966-689f2900-c77e-11eb-8e54-18b649a9add1.jpg)

**Comment by BikramKumar6928** [comment]
Sorry for jumping mid conversation without any notice.

One suggestion. Can the play button be in the middle?

Currently the layout is previous episode, play/pause, next episode, +85s(which is very nice, thanks), settings.

This makes the next episode as the middle button, which IMO differs from the UX of other players where play/pause is the middle button.

With the current buttons, maybe keep the settings to the extreme left. Then everything will fall into place. The skip 85s should be on right as it denotes a forward skip.

PFA Screenshot.

![Screenshot_20211115-003117_Aniyomi](https://user-images.githubusercontent.com/24207657/141695123-f5a8bfd5-d5d1-4383-ab25-8a8d4b565950.png)
