### ISSUE TITLE
Cannot Download on 9anime

### ISSUE THREAD

**Issue by Pervases** [jmir1/aniyomi#523]
![Screenshot_2022-04-15-13-34-21-736](https://user-images.githubusercontent.com/103200096/163526418-90908a9f-1351-4e1d-967f-5d1bc5c1d95f.png)
![Screenshot_2022-04-15-13-34-25-997](https://user-images.githubusercontent.com/103200096/163526443-6abf1e3d-ce0d-4c6b-bb9f-16e2624d486b.png)
![Screenshot_2022-04-15-13-34-46-331](https://user-images.githubusercontent.com/103200096/163526450-afb10cfa-f130-4ca5-a99f-a4b5e06b1eec.png)
### Steps to reproduce

1. Install 9anime Extension
2. Browse any anime
3. Tap on the download button

### Expected behavior

The Anime episode should be downloaded, or at least the progress bar (pie) should appear.

### Actual behavior

Instead of the progress bar, reddish exclamation mark appears. The Aniyomi notification bar displays "Download Completed" but the download directory is empty.

### Aniyomi version

0.12.3.6

### Android version

Android 11

### Device

RedMagic 6S Pro

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/jmir1/aniyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://aniyomi.jmir.xyz/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.12.3.5](https://github.com/jmir1/aniyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by RehanPlayz** [comment]
I have the same issue
