### ISSUE TITLE
Couldn t find any video link

### ISSUE THREAD

**Issue by harshal551** [jmir1/aniyomi#528]
### Steps to reproduce

1. Open one piece anime 
2. Select any episode 
3. Then the video will open and say couldn t find any video link
![Uploading Screenshot_20220414_185240.jpg…]()

### Expected behavior

I think it is a problem with connection of link in web site to aniyomi

### Actual behavior

I was watching episode of one piece regularly everyday but suddeny yesterday it says couldn t find any video link. It happed day before yesterday but the issue was solved at evening but the issue get yesterday also i thought that the issue will solved till night but its 24 hours now but no solution. One more thing the issue that was solved day before yesterday the issue was solved beacuse at evening a update came in anime extention of gogoanime.

### Aniyomi version

0.12.3.6

### Android version

8

### Device

Vivo y91

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/jmir1/aniyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://aniyomi.jmir.xyz/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.12.3.5](https://github.com/jmir1/aniyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by Bleepbopbip** [comment]
This is also happening to me. I was watching Bleach and it was yesterday night I woke and continued watching and after about 12 mins into the episode it stopped and when I tried to reopen it says "couldn't find video link".

**Comment by 2067manishkulkarni** [comment]
Yeah, the same is happening to me everyday.
Yesterday tried to watch attack on Titan from gogoanime extension but it would always say couldn't find any video links. So I tried other extensions and the same is happening. This has been happenig since gogoanime update and also I miss my anime. Good version please fix the issue of extensions after the update.

**Comment by MechaStreisand91** [comment]
I am having the same issue for Gogoanime. For other extensions it says the location cannot be found too.

**Comment by Maxxlianuj** [comment]
Oo bhai koi bi anime ni chal rha h kya seen h dheko yll kya huaa h ab to anime hi chalna band ho gya

**Comment by jmir1** [comment]
"If this is an issue with an extension, I should be opening an issue in the extensions repository."

**Comment by 2067manishkulkarni** [comment]
Thank you for your help the extension update just got in now evrything is
working fine

**Comment by 2067manishkulkarni** [comment]
Ok so the extension issue was kind of solved but attack on Titan and other
anime aren't working and showing 'couldnt find any video links' also other
anime are taking much longer to start please help

**Comment by 2067manishkulkarni** [comment]
The 12.40 gogoanime update just came

**Comment by Hero-GamingZ** [comment]
Been having the same problem with Tokuzilla , before I was able to watch using the extension but now it says it can't find the video link

**Comment by jmir1** [comment]
> Been having the same problem with Tokuzilla , before I was able to watch using the extension but now it says it can't find the video link

Bro you seriously just commented on a 2 year old issue

**Comment by AbdulrahmanIII** [comment]
Clear app data
This should solve it

**Comment by Animake-jpg** [comment]
> > Been having the same problem with Tokuzilla , before I was able to watch using the extension but now it says it can't find the video link
> 
> Bro you seriously just commented on a 2 year old issue

Y not bro. D same is happening to me. What should I do

**Comment by Secozzi** [comment]
> Y not bro

Because the actual problem they were having is no longer relevant. Go ask where extensions are being maintained instead of here.

**Comment by Animake-jpg** [comment]
O sorry bro
