### ISSUE TITLE
Gogoanime

### ISSUE THREAD

**Issue by Spikebinger99** [jmir1/aniyomi#530]
### Steps to reproduce

![Screenshot_20220414-221923_Aniyomi](https://user-images.githubusercontent.com/100854392/163684018-ad9da947-2aeb-4210-a30b-97b0cbcb8fbe.jpg)

Please remove doodstream 

### Expected behavior

Bring back the Optional Quality like 480p to 1080p

### Actual behavior

Optional Quality pleaee

### Crash logs

Nothing

### Aniyomi version

0.12.3.5

### Android version

andriod 10

### Device

Samsung 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/jmir1/aniyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://aniyomi.jmir.xyz/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.12.3.5](https://github.com/jmir1/aniyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by FruriousRD** [comment]
Agreed it takes forever to load

**Comment by Yootz** [comment]
It got updated and it's even worse now, it keeps saying can't open video links

**Comment by Cidokagenou** [comment]
![Screenshot_20230219-144027](https://user-images.githubusercontent.com/125793743/219939439-d8c3cd25-25bd-4b85-9e09-edee526b43b1.png)
How to fix it
