### ISSUE TITLE
 [Feature Request] Local Sources for anime

### ISSUE THREAD

**Issue by ghost** [jmir1/aniyomi#54]
## Why/User Benefit/User Problem
Streaming websites nowadays only use official crunchyroll/funimation subs for the anime they provide, these subs are not that good, so many people prefer fansubs over official ones for that perticular reason although there are a handful of sites that offer fansubs like Animepahe which can be added in extension later down the line, i believe for now its best to make use of the "Local source" function tachiyomi provides, since people can download the episodes from whatever source they please and put them in a speciefied Local folder manually so tachiyomi can detect and add said episodes to their library. by doing that, tachiyomi can act as a full hub of the user's online and local anime library and gives the user full freedom over the quality, subs and dubs.

## What/Requirements
So, i still use tachiyomi's local source function, and i don't think it should behave any different from it, the user just have to copy/paste the episodes he wants into a "Tachiyomi/Local/<Anime Name>/" folder and so it can be detected by tachiyomi and later added by the user with discover feature.
the issue is that tachiyomi can't play some video formats "HEVC 265x/264x AVC" and some others, which wouldn't be a problem cause these can be played in an external player

**Note**: The requested feature can already be done by replacing downloaded episodes of said shows with what the user wants.

**Comment by jmir1** [comment]
the video player used my this app (exoplayer 2) should be capable of playing hevc on android marshmallow and higher.
however, support for different video codecs/types isn't configured properly yet, and local sources for anime need to be fixed.

**Comment by AbdullahMehiz** [comment]
Yea so can it also use SSA/ASS subs? Only handful of players support these kids of subs properly(mpv is the only actual good one)

**Comment by selfrisingfloor** [comment]
it'd also be better if the app could automatically fetch metadata for local anime from an online database (MAL, Anilist etc).

possible implementation: A MAL/Anilist etc extension to add anime and sync metadata, which will create a local folder where the user can put their episodes (or make the extension fetch episode from a user specified local directory)

**Comment by yooman1213** [comment]
#48

Well i already post it as bug but no reply or any reaction?

Sadge

**Comment by AbdullahMehiz** [comment]
> #48
> 
> Well i already post it as bug but no reply or any reaction?
> 
> Sadge

well, your bug report was quite lacking in details

**Comment by yooman1213** [comment]
Well local source already implemented in manga on original Tachiyomi

So there not much to say though 

So i thought it's just the same as how local source on manga been read, but in this case this is an video parser on how the app reads the file on local.

Well i get it coding it's not easy, i was developer once. (Intermediate flutter dev).

Well i don't want to ask to much from the developer of this fork, i just want watching/playing from local source to be fix.

**Comment by jmir1** [comment]
> Well local source already implemented in manga on original Tachiyomi
> 
> So there not much to say though
> 
> So i thought it's just the same as how local source on manga been read, but in this case this is an video parser on how the app reads the file on local.
> 
> Well i get it coding it's not easy, i was developer once. (Intermediate flutter dev).
> 
> Well i don't want to ask to much from the developer of this fork, i just want watching/playing from local source to be fix.

and it will be fixed, but please don't talk about random other things in unrelated issues

**Comment by jmir1** [comment]
this will be fixed, I am aware of the problem. It's just something I haven't gotten around to yet

**Comment by jmir1** [comment]
> #48
> 
> Well i already post it as bug but no reply or any reaction?
> 
> Sadge

I didn't reply to your issue because there is nothing to be said about it. Yes, it is a bug, you are correct. And I was already aware of it as well. I plan on fixing it but don't have an idea of when.
