### ISSUE TITLE
Center the play button of the player+ add force rotation button

### ISSUE THREAD

**Issue by Palloxin** [jmir1/aniyomi#546]
### Describe your suggested feature

Add the force rotation button that would allow us to force the rotation of the video in the player indipendently from the automatic rotation of android being disabled or activated.
In addition i would like this button to be added here (see the image, blue color).
another addition would be the change of the position of the play button to the perfect middle.
![IMG_20220424_114241](https://user-images.githubusercontent.com/75091899/164970497-fd2cc532-bd90-4d7c-8c99-8493c637f1b8.jpg)

### Other details

Actually the play button being not in the middle is quite strange and an aestethic flaw in my opinion. So addihg the force rotation button would make the change of position of the play button possible. So it would become pleasent to the eyes + the addition of a useful button.
the reason i would like the addition of the new button is because when i am charging the phone the sense the video is displayed on the screen is not comfortable since the charge cable is in the way, so i would like the button to force the rotation in a favorable way without activating the automatic rotation of android.
With the addition of the force rotation button you can place the play button in the middle since in this way it would be the button in the middle.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/jmir1/aniyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.12.3.5](https://github.com/jmir1/aniyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by Quickdesh** [comment]
New beta version has a new player altogether and the features you mentioned are already there

[Aniyomi beta](https://github.com/jmir1/aniyomi-mpv-beta/releases/latest)
