### ISSUE TITLE
Can you please provide it on ios 

### ISSUE THREAD

**Issue by Dvixe** [jmir1/aniyomi#553]
### Describe your suggested feature

Please upload a ios version

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/jmir1/aniyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.12.3.5](https://github.com/jmir1/aniyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by Quickdesh** [comment]
Not going to happen

Use ["NineAnimator"](https://github.com/SuperMarcus/NineAnimator)
