### ISSUE TITLE
[Bug] The "Sort" feature isn't working

### ISSUE THREAD

**Issue by AbdullahMehiz** [jmir1/aniyomi#56]
## Device information
* Tachiyomi version: Preview r3626
* Android version: 10
* Device: Xiaomi Redmi Note 8 Pro

## Steps to reproduce
1. Change sorting method

### Expected behavior
Episodes should be re-sorted as intended

### Actual behavior
the episodes never get sorted as the user intended (the order of the episodes stays the same even! after changing sorting method)

**Comment by fitrimasaan** [comment]
Just want to add to this. Sorting works fine for manga. Only the anime part is not working.
