### ISSUE TITLE
A desktop version

### ISSUE THREAD

**Issue by AdriBD83** [jmir1/aniyomi#560]
### Describe your suggested feature

Please make a desktop version for aniyomi. aniyomi is a great app for watching anime and reading manga.
Using emulator or WSA needs higher requirements which all pcs can't keep up so if there was any desktop version for this it would be very great.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/jmir1/aniyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.12.3.5](https://github.com/jmir1/aniyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by MoonLGH** [comment]
the answer is obvious, no
but iirc, tachidesk was had a version for aniyomi that is un contiuned, 
if you want native aniyomi to run, the answer is also obvious, make it yourself

**Comment by MoonLGH** [comment]
ref dupe : #120 #147

quote
>[jmir1](https://github.com/jmir1) commented [on Sep 20, 2021](https://github.com/jmir1/aniyomi/issues/147#issuecomment-922546461)
fyi: tachidesk is currently not supporting aniyomi extensions anymore

**Comment by Poopooracoocoo** [comment]
You do realise that Aniyomi and Tachiyomi use native components for the interface and that you're asking for an entirely new app?

**Comment by MoonLGH** [comment]
yeah simple way to say it is, USE HAKUNEKO
thanks

**Comment by MoonLGH** [comment]
https://github.com/manga-download/hakuneko
this discussion shall not be continued further
