### ISSUE TITLE
recommend souce

### ISSUE THREAD

**Issue by edmxn** [jmir1/aniyomi#570]
### Describe your suggested feature

Souce for Spanish language [Español]

### Other details

AnimeFlash 2
https://animeflash2.xyz/

JK Anime
https://jkanime.net/

HolaAnime
https://holanime.net/

AnimeID
https://www.animeid.tv/

TioAnime
https://tioanime.com/

AnimeMovil2
https://animemovil2.com/

YTAnime TV
https://ytanime.tv/

AnimeBlix
https://animeblix.com/

AnimeOnline Ninja
https://www1.animeonline.ninja/

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/jmir1/aniyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.12.3.5](https://github.com/jmir1/aniyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by MoonLGH** [comment]
wrong repo
https://github.com/jmir1/aniyomi-extensions/issues/new/choose

no further discussion shall be talked here

close

**Comment by Diegopyl1209** [comment]
Animeflash2 
HolaAnime
Tioanime
YTanime TV
Anime online Ninja

They are scrapers from animeFLV and animefenix

**Comment by edmxn** [comment]
> Animeflash2 HolaAnime Tioanime YTanime TV Anime online Ninja
> 
> They are scrapers from animeFLV and animefenix

Is that so? Is that there are some animes that are in better quality than in animeflv (of those websites)
