### ISSUE TITLE
Vertical anime player

### ISSUE THREAD

**Issue by Zedd0038** [jmir1/aniyomi#591]
### Describe your suggested feature

Need an option to make the player vertical

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/jmir1/aniyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.12.3.5](https://github.com/jmir1/aniyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by 12ohit** [comment]
Aniyomi's beta version has this feature and it will be coming in stable Aniyomi in future(no ETA though), if you want you can try out the beta version now:
https://github.com/jmir1/aniyomi-mpv-beta/releases/latest
