### ISSUE TITLE
I don't know is big or what just fix it

### ISSUE THREAD

**Issue by Adi432144** [jmir1/aniyomi#592]
### Steps to reproduce

I am user of aniyomi 
I currently facing problem in watching anime in 9anime extension
So fix it 

### Expected behavior

When ever I clicked on any episode of anime from 9anime extension 
This pop up 
![Screenshot_20220520-152904](https://user-images.githubusercontent.com/74503284/169522500-f277044a-99b2-4b4d-aae6-9dee49b3b8c3.png)
So please fix it 🙏😭

### Actual behavior

I don't know how is happening but this is a big problem 

### Aniyomi version

0.12.3.6

### Android version

Android 6

### Device

Samsung galaxy J7

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/jmir1/aniyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://aniyomi.jmir.xyz/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.12.3.5](https://github.com/jmir1/aniyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by AnimalTheGamer300** [comment]
This happens for 9anime. I tried 2 other sources and AnimeKisa has HTTP/HTTPS issues, but Animixplay seems to working.

**Comment by Adi432144** [comment]
But I mostly use 9anime 😭 😢 do something 🙏🙏🙏🙏😭
