### ISSUE TITLE
I THINK NOW YOU CAN UPDATE 9ANIME EXTENSION

### ISSUE THREAD

**Issue by Adi432144** [jmir1/aniyomi#594]
### Describe your suggested feature

As few days there is problem with 9anime which causes trouble to watch/download episode
Today I checked the website of 9anime.id there is no cloudflare pop up and website interface restored to normal

### Other details

I think you should update the 9anime extension because the website is back Normal the way it was before and no cloudflare pop up 
So i might think is right time to update

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/jmir1/aniyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.12.3.5](https://github.com/jmir1/aniyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by Nhuttz** [comment]
bug fix pls

**Comment by estrath** [comment]
hi @jmir1 
just a real quick question, apparently the key aka vrf was working but not anymore: 'eST4kCjadnvlAm5b1BOGyLJzrE90Q6oKgRfhV+M8NDYtcxW3IP/qp2i7XHuwZFUs'

now i was digging deep for weeks into aniwave js code and whatnot and couldnt find anything similiar, so how did you manage to come up with it? i think im into somthing i just need you to pinpoint about the key,

please reply.

**Comment by jmir1** [comment]
> hi @jmir1 
> just a real quick question, apparently the key aka vrf was working but not anymore: 'eST4kCjadnvlAm5b1BOGyLJzrE90Q6oKgRfhV+M8NDYtcxW3IP/qp2i7XHuwZFUs'
> 
> now i was digging deep for weeks into aniwave js code and whatnot and couldnt find anything similiar, so how did you manage to come up with it? i think im into somthing i just need you to pinpoint about the key,
> 
> please reply.
> 

I suggest you join the discord server and ask in the #dev channel. I'm not the one who was working on the extension before it broke, but someone else can probably help you.

**Comment by estrath** [comment]
> > hi @jmir1
> > just a real quick question, apparently the key aka vrf was working but not anymore: 'eST4kCjadnvlAm5b1BOGyLJzrE90Q6oKgRfhV+M8NDYtcxW3IP/qp2i7XHuwZFUs'
> > now i was digging deep for weeks into aniwave js code and whatnot and couldnt find anything similiar, so how did you manage to come up with it? i think im into somthing i just need you to pinpoint about the key,
> > please reply.
> 
> I suggest you join the discord server and ask in the #dev channel. I'm not the one who was working on the extension before it broke, but someone else can probably help you.

can you provide me with the discord link, thank you so much.

**Comment by jmir1** [comment]
https://discord.aniyomi.org
