### ISSUE TITLE
THERE IS A CLOUDFLARE BUG IN 9ANIME

### ISSUE THREAD

**Issue by Adi432144** [jmir1/aniyomi#597]
### Steps to reproduce

I made a clip that show bug in 9anime
1. Reloading for episodes (faild to bypass cloudflare)
2. Search for anime ( faild to bypass cloudflare)
3. To play episode ( failed to bypass cloudflare)

### Expected behavior

I want to this to be happening in 9anime
1. When I Reloading for episodes then episode show
2. When I searc anime then the anime i seach will appear
3. When I play episode then the episode start playing

### Actual behavior

The actual happened in 9anime is
1. When I Reloading for episodes then failed to bypass cloudflare pop up
2. When I search for anime faild to bypass cloudflare pop up
3. When I play episode then failed to bypass cloudflare pop up

### Crash logs

Uploading 20220524-085117-720x1280_uHCcdpjP.mp4…

### Aniyomi version

0.12.3.6

### Android version

Android 6

### Device

Samsung galaxy J7

### Other details

Please try to create something for cloudflare pop up

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/jmir1/aniyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://aniyomi.jmir.xyz/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.12.3.5](https://github.com/jmir1/aniyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by Jcross1029** [comment]
im having this same issue

**Comment by Adi432144** [comment]
> im having this same issue, using a moto G stylus "2019"
I know 😯🙁
I installed This app because of 9anime for sure 
Because 9anime is my first best website to watch'

**Comment by Adi432144** [comment]
@jmir1 please help us with this problem
😢😢😭😭😔🙏🙏🙏

**Comment by ahmedgamal17** [comment]
@Adi432144  9anime is broken stop spamming or pinging the dev

**Comment by Adi432144** [comment]
@ahmedgamal17 
Do you have any😠 prove I am spam😬 
Then tell me😑 why is not working then if you consider yourself something 😝

**Comment by yoonminiz** [comment]
Same issue on my redmi note 9s

**Comment by jdyaras** [comment]
Hi, I also repeated all the troubleshooting steps, even deleted all my cache and app data, then did a forced close before rebooting my phone, but it didn't work. Finally I just uninstalled aniyomi, after cleaning everything from it, and reinstalled it, but 9anime didn't work or load any episode.

**Comment by Adi432144** [comment]
@jdyaras i know bro how it feels like 
That's why I write issue so app maker/ developers take action about this issue but no this guy @ahmedgamal17 said I am spamming 
Then I deleted aniyomi

**Comment by jmir1** [comment]
> jdyaras i know bro how it feels like 
> That's why I write issue so app maker/ developers take action about this issue but no this guy ahmedgamal17 said I am spamming 
> Then I deleted aniyomi

You guys have to chill a bit... Everyone is working on this app in their free time so it's only natural that bugs take some time to get fixed...

**Comment by jmir1** [comment]
Also, extension issues should be opened in the extensions repo. So I'm closing this issue.

**Comment by Adi432144** [comment]
@jmir1 sorry for this behaviour I am extremely sorry 🙁😔 
And thanks for making this amazing app
I write this issue because iam frustrated and again sorry 😞
