### ISSUE TITLE
Unable to Bypass Cloudflare

### ISSUE THREAD

**Issue by sr-777** [jmir1/aniyomi#604]
### Steps to reproduce

> Steps to reproduce this error

> Install and 9anime extension
> click on any tiles or try to search something

### Expected behavior

> Expected Behaviour:
`episode should load and search should work`

### Actual behavior

> Actual Behaviour
![IMG_20220529_124614](https://user-images.githubusercontent.com/97355073/170856488-0508c527-e18d-4e53-bff1-18bb68ae8c6f.jpg)
![IMG_20220529_124529](https://user-images.githubusercontent.com/97355073/170856490-f8668b26-b4ca-4b46-b56f-f6c6d1129300.jpg)

### Aniyomi version

0.12.3.5

### Android version

9

### Device

Mi phone

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/jmir1/aniyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://aniyomi.jmir.xyz/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.12.3.5](https://github.com/jmir1/aniyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by GMRobo** [comment]
Please check the troubleshooting guide again because i know this exact issue is in there.

**Comment by SpaceCookiez** [comment]
https://aniyomi.jmir.xyz/help/guides/troubleshooting/#solving-the-cloudflare-issue

**Comment by Adi432144** [comment]
@SpaceCookiez 
Bro i tried everything in trouble shooting many times but nothing happened
And there no cloudflare pop up in webview and chrome also .
So what do now

**Comment by 12ohit** [comment]
@sr-777 @Adi432144 This is not the cloud flare issue, the 9anime extension itself has problem wait until it gets fixed, until that you can do nothing to make it work
