### ISSUE TITLE
Use ExoPlayer as the built-in player

### ISSUE THREAD

**Issue by lasersPew** [jmir1/aniyomi#611]
### Describe your suggested feature

Use ExoPlayer as the built-in player instead of the current player.

### Other details

Well, I've liked every feature of this app except the player. also, exoplayer is built by gogle.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/jmir1/aniyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.12.3.6](https://github.com/jmir1/aniyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by jmir1** [comment]
aniyomi has always used exoplayer 🤦

**Comment by lasersPew** [comment]
doesnt look like it.

**Comment by jmir1** [comment]
🗿
