### ISSUE TITLE
[Bug] App Crashing on Launch after installing yesterday

### ISSUE THREAD

**Issue by jeremy-power** [jmir1/aniyomi#63]
## Device information
* Tachiyomi version: 0.11.1.4 and 0.11.1.5
* Android version: 10
* Device: OnePlus 5T

## Steps to reproduce
1. Open App

### Expected behavior
The app should properly load.

### Actual behavior
The app crashes to home screen

## Other details
I installed fresh yesterday, I still have Tachiyomi installed, I added 1 manga to my library from MangaLife extension and the app was working well.
I tried opening it today and was unable to. I tried updating to 0.11.1.5 but this did not change the problem. I can try reinstalling but thought I should submit a bug report first as it seems like a major issue I would like to help fix.

I have attached an adb logcat file active during the crash, I was not sure what to filter by to narrow it down.
[aniyomi-log.txt](https://github.com/jmir1/tachiyomi-mi/files/6626394/aniyomi-log.txt)
I have also recorded a quick demo of the crash here:
https://streamable.com/z8l54x

I am unable to access the dump crash logs button in the app.

I hope this helps, let me know if you need any more information.

Jeremy

**Comment by 22seegerb** [comment]
Having the same issue with simmiar circumstances. Something to note is the fact that I have notifications setup and auto-update set to 3 hours for both Tachiyomi and with Aniyomi, but I only received notifications from Tachiyomi which may indicate that grabbing the updates was the issue.
