### ISSUE TITLE
Tracker for movie/Tv: Simkl is the one

### ISSUE THREAD

**Issue by shipoxx** [jmir1/aniyomi#633]
### Describe your suggested feature

Hey so there's no tracking method for movies or tv shows on aniyomi and it's really a pain to do it manually everytime
So why note jmir add a tracker for movies and tv shows (they support anime too)

And it's the API is public (owner of the website is really great guy lol)

### Other details

https://simkl.docs.apiary.io/#

https://github.com/SIMKL/API

https://simkl.com/

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/jmir1/aniyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.12.3.6](https://github.com/jmir1/aniyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by masyk** [comment]
Simkl is supported in the latest beta https://github.com/jmir1/aniyomi-mpv-beta/releases
https://github.com/jmir1/aniyomi/issues/616
