### ISSUE TITLE
Dowload queue cancel all

### ISSUE THREAD

**Issue by Electrici1** [jmir1/aniyomi#65]
The old version Tachiyomi was better at download feature. The queued mangas or anime never cancel even if your phone us offline. Unlike the latest(currently using). I download 100 plus chapters, finished half of it, pause and go offline. After i get back online, the half download queue GONE!
By the way. 
Thank you so much for the app( S TIER). 😍😍

**Comment by god-among-men** [comment]
please fix this thank you

**Comment by jmir1** [comment]
Pretty sure this issue has been fixed, but let me know if you still encounter it!
