### ISSUE TITLE
autoscrolling for manga/manhwa

### ISSUE THREAD

**Issue by waffleboi9000** [jmir1/aniyomi#654]
### Describe your suggested feature

Some kind of function to automatically scroll vertically for content that requires a lot of scrolling, preferably with some kind of speed adjustment.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/jmir1/aniyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.12.3.7](https://github.com/jmir1/aniyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by 12ohit** [comment]
Please open this issue on Tachiyomi and if they add this then Aniyomi will have it too🙂

**Comment by 12ohit** [comment]
I don't know if Aniyomi devs even work on Manga stuff but I can tell you that right now they are busy working on new internal player, so it's not gonna happen soon here too..

**Comment by waffleboi9000** [comment]
Understandable.
