### ISSUE TITLE
9anime change there web id which in turn is unrecognizable to the app source

### ISSUE THREAD

**Issue by Tasenova99** [jmir1/aniyomi#656]
### Steps to reproduce

1. Going to Sources
2. Extensions
3. 9 Anime

### Expected behavior

It should just open up if it was directed to one of the following websites 
9anime.to
2nd removed now replaced with 9anime.id
9anime.pl

### Actual behavior

It now just draws a blank because the new sources url changed. since it all goes to 9anime.id now instead of any of the previous 9anime domains
they updated the site's looks but I'm pretty sure the app doesn't get effected by that

### Aniyomi version

0.12.3.7

### Android version

Android 11

### Device

Samsung 9

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/jmir1/aniyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://aniyomi.jmir.xyz/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.12.3.7](https://github.com/jmir1/aniyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by 12ohit** [comment]
> If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/jmir1/aniyomi-extensions/issues/new/choose).

Bruh
