### ISSUE TITLE
[Source Request] www.wcoanimedub.tv.

### ISSUE THREAD

**Issue by Samk19** [jmir1/aniyomi#675]
### Describe your suggested feature

Source
Link: www.wcoanimedub.tv
Feature: dub anime exclusive 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/jmir1/aniyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.12.3.7](https://github.com/jmir1/aniyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by 12ohit** [comment]
Please open issue related extensions on [extensions repository](https://github.com/jmir1/aniyomi-extensions/issues/new/choose).
