### ISSUE TITLE
Feature request: playing media externally but in a different way. Hear me out

### ISSUE THREAD

**Issue by jackie5602** [jmir1/aniyomi#707]
### Describe your suggested feature

The reason why I'm making this feature request is kinda selfish lol, I got a below average internet connection (down ~12Mbit/s, up ~2Mbit/s, don't ask how, I'm a third worlder lmao), and I saw the external app feature and I like it. I use it from time to time, but not very often because of my internet connection.

I assume that external app automatically plays the video in 1080p, and that's what I have issues with, the thing just keeps buffering and it's annoying, a lot of the time I watch anime in the Aniyomi player.

I just wish, if it's possible at all, for a feature to be made where you can play what you're watching manually via an external app, and have either a prompt each time, where it asks in which quality/resolution you want to play it in, or have it play in the current resolution. For an example, if the video's been set to, let's say 720p, have it play in ex. VLC as 720p as well.

That's it, all I've wanted to say. I thank y'all in advance if it's possible. But if it's not just ignore my request lol, I don't mind. Cya

EDIT: There's another user that had the same feature in mind: https://github.com/jmir1/aniyomi/issues/575

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/jmir1/aniyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.12.3.7](https://github.com/jmir1/aniyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by 12ohit** [comment]
Or you can go into the settings of the extension you want to use and select the preferred video quality to 720p(or your desired one) and then VLC will always play the episode in that quality if it's available.

**Comment by jackie5602** [comment]
> Or you can go into the settings of the extension you want to use and select the preferred video quality to 720p(or your desired one) and then VLC will always play the episode in that quality if it's available.

oh thank you, I didn't know this can be done that way
