### ISSUE TITLE
9anime ext getting uninstalled 

### ISSUE THREAD

**Issue by Rohan-Somadder** [jmir1/aniyomi#721]
### Steps to reproduce

Open the app and check the installed extension list in the extension tab

### Expected behavior

The 9anime extension should be installed once and it should remain installed 

### Actual behavior

https://photos.app.goo.gl/CqdDoVhiZSAhTFt7A

### Aniyomi version

Stable 0.12.3.7

### Android version

Android 12

### Device

Realme 9 pro 5G

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/jmir1/aniyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://aniyomi.jmir.xyz/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.12.3.7](https://github.com/jmir1/aniyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by Mindirix** [comment]
same here

**Comment by jmir1** [comment]
fixed with new extension updates
