### ISSUE TITLE
9anime's Problem

### ISSUE THREAD

**Issue by katagirii** [jmir1/aniyomi#722]
### Describe your suggested feature

Am not a Developer. Don't know much about it but it seems 9anime is Changing Things in it's website again and again, so that the Extension won't work. There is a website which is Exactly 9anime with a Little UI Changes, *animesuge.to* that is. Try making that website's extension. Don't know if it will work though.

### Other details

Website :- animesuge.to

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/jmir1/aniyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.12.3.7](https://github.com/jmir1/aniyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by Sathvik8** [comment]
Yes ,but there is no animesuge extension
