### ISSUE TITLE
Extensions that use Cloudflare cant be bypassed

### ISSUE THREAD

**Issue by Norikiru** [jmir1/aniyomi#732]
### Steps to reproduce

Open any plugin that uses Cloudflare

### Expected behavior

Be able to view anime and manga.

### Actual behavior

Shows an error: "Failed to bypass Cloudflare"

## Following extensions that I had tested:
**Anime:** None for now
**Manga:** [Mangafreak](https://w13.mangafreak.net/), [nhentai](https://nhentai.net/)

## Here are screenshots of the extensions that I am not able to use due to this issue:
![Screenshot_20220819-213058_Aniyomi](https://user-images.githubusercontent.com/99774021/185632133-416fe773-9ae0-46fb-b354-c3f831bd6de6.png)
![Screenshot_20220819-213222_Aniyomi](https://user-images.githubusercontent.com/99774021/185632237-fabfa11b-2cfa-4cdc-b496-71b17d8f0bbf.png)

### Aniyomi version

0.12.3.7

### Android version

Android 12.1

### Device

Redmi 7A

### Other details

IMPORTANT: Cloudflare doesn't let me in Aniyomi nor WebView BUT it does let me in when I use Google Chrome.

I do know that this is technically an extension problem, but I think the [CloudflareInterceptor.kt](https://github.com/jmir1/aniyomi/blob/master/app/src/main/java/eu/kanade/tachiyomi/network/interceptor/CloudflareInterceptor.kt) file is **probably** the culprit here. The websites that I use that uses Cloudflare had a new layout/design when it checks if I am human or not which probably means that they had updated into a newer version that the interceptor cant bypass?

## My phone is running a custom ROM:
LineageOS 19.1 (UNOFFICIAL) | Android 12.1

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/jmir1/aniyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://aniyomi.jmir.xyz/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.12.3.7](https://github.com/jmir1/aniyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by MikaelaMuller** [comment]
Interesting, i have the same issue too and i didn't know this issue isn't just isolated on Mangafreak, by the way how did you diagnose this?

**Comment by Buchimi** [comment]
This issue has actually been discussed on tachiyomi and the solution is to change the user agent. 
You can change the user agent manually in tachiyomi but not yet in aniyomi.

**Comment by Norikiru** [comment]
> This issue has actually been discussed on tachiyomi and the solution is to change the user agent. You can change the user agent manually in tachiyomi but not yet in aniyomi.

Would this be soon implemented onto Aniyomi? It seems that many people are also experiencing this issue with most of Tachiyomi (manga) extensions but not really with Aniyomi (anime) extensions.

**Comment by Buchimi** [comment]
> > This issue has actually been discussed on tachiyomi and the solution is to change the user agent. You can change the user agent manually in tachiyomi but not yet in aniyomi.
> 
> Would this be soon implemented onto Aniyomi? It seems that many people are also experiencing this issue with most of Tachiyomi (manga) extensions but not really with Aniyomi (anime) extensions.
> 
> Edit: I guess for those who are having this issue with Tachiyomi extensions, I recommend switching to Tachiyomi for the time being.

I have no idea rly.

**Comment by n0k0m3** [comment]
@jmir1 needs to merge (cherry pick) latest commit related to User Agent to fix this:
Original repo: https://github.com/tachiyomiorg/tachiyomi/commit/7c7bd72c8e1170966b396384d190437da12c3e32
TachiSY: https://github.com/jobobby04/TachiyomiSY/commit/58ef23995964bd20867ac3b359b5d8f9ceb01aa8
TachiAZ:https://github.com/az4521/TachiyomiAZ/commit/71f7e12525e817fd50bc35445fdfcce77614236c

**Comment by Norikiru** [comment]
Fixed in a recent update.

**Comment by rothinkumar** [comment]
How to find the correct user agent

**Comment by rothinkumar** [comment]
> Fixed in a recent update.

Brother i am facing this in supjav where cloudefare bypass is needed.I tried some user agent but couldn't find the right one... could you help me on this...
My chrome is updated to 130
And my Android version is 12

**Comment by Secozzi** [comment]
> > Fixed in a recent update.
> 
> Brother i am facing this in supjav where cloudefare bypass is needed.I tried some user agent but couldn't find the right one... could you help me on this... My chrome is updated to 130 And my Android version is 12

Read the guide on our site instead of commenting on old issues: https://aniyomi.org/docs/guides/troubleshooting/#cloudflare
