### ISSUE TITLE
[Feature Request] Support for Full Subtitles for DUB

### ISSUE THREAD

**Issue by kooolarpan** [jmir1/aniyomi#74]
Please provide subtitles for the DUB. It would help a lot.

**Comment by kooolarpan** [comment]
@jmir1 Why is this issue closed? Just wanted to know if the subs can be added or not?

**Comment by jmir1** [comment]
issue is closed because it is opened in the wrong repo.
the answer is obviously yes, but it depends on what source has dubbed anime with subs

**Comment by jmir1** [comment]
you can open an issue in jmir1/aniyomi-extensions and suggest a new source to be added that has the stuff you are looking for

**Comment by kooolarpan** [comment]
Ohh, Ok. Thanks for the info.
