### ISSUE TITLE
9anime crash "bruh"

### ISSUE THREAD

**Issue by Nintenstation** [jmir1/aniyomi#745]
To my surprise, it seems like 9anime is working better than before and is able to search through anime. With that being said, there is still one issue: you can't open any episode without a "bruh" error occuring. I wonder if this can be fixed so that the issue of 9aniyomi can be fixed once and for all?
Thank you in advance.

**Comment by DaRacci** [comment]
Same thing happens when trying to download an episode too.

**Comment by AngelaVilladiego** [comment]
Haha yeah I get this error trying to download an episode. Unable to download any episodes anymore, used to work then suddenly stopped working, updated and still getting the bruh error. 

Kind of funny but would be helpful to have an idea what kind of error is occuring (though "bruh" might just mean "idk why this error is happening bruh how did it even break")

**Comment by Nintenstation** [comment]
> Haha yeah I get this error trying to download an episode. Unable to download any episodes anymore, used to work then suddenly stopped working, updated and still getting the bruh error. 
> 
> Kind of funny but would be helpful to have an idea what kind of error is occuring (though "bruh" might just mean "idk why this error is happening bruh how did it even break")

Haha, agreed. It's a weird error that even the source itself might be confused over what the problem is. But if we can fix this, then I'd finally rest easy knowing my favorite source (9anime) is finally working again!! G'luck to the team.

**Comment by sirlordofderp** [comment]
I'm getting the error still too. While extremely humorous it would be nice to watch stuff again.

**Comment by Nintenstation** [comment]
> I'm getting the error still too. While extremely humorous it would be nice to watch stuff again.

It really sucks, but it feels like they just won't fix it... Don't wanna be pessimistic, but it has been like this for far too long! At this point, it may be too difficult to just fix. Shame since it was kinda the best source...

**Comment by sirlordofderp** [comment]
> > I'm getting the error still too. While extremely humorous it would be nice to watch stuff again.
> 
> It really sucks, but it feels like they just won't fix it... Don't wanna be pessimistic, but it has been like this for far too long! At this point, it may be too difficult to just fix. Shame since it was kinda the best source...

Personality I think 9anime having multiple sources on the site as Mell as sources for both subbed and dubbed is making the app try pulling multiple streams from a single link. Basically it's trying to pull both subbed and dubbed I think

**Comment by jmir1** [comment]
the 9anime extension is currently broken :sob:
they are making life very difficult for us so i don't know when it will be fixed.
in the future, please open issues with the extensions in the [extensions repo](https://github.com/jmir1/aniyomi-extensions).
