### ISSUE TITLE
[Feature Request] <Write short description here>

### ISSUE THREAD

**Issue by Marsavis5** [jmir1/aniyomi#76]
hello i love your app aniyomi but can you add more extensions like gogo, animixplay etc and also add multiple qualities like 360p,480p,720pand 1080p options in the player plzzzzzzzzzzzz

**Comment by Marsavis5** [comment]
Plz consider it

**Comment by ty-coon** [comment]
Quality options already in the player choose your source 2dgirls.net, its just player crashes sometimes and can't download some videos.
