### ISSUE TITLE
Attempting to play in external app causes crash

### ISSUE THREAD

**Issue by Grafcube** [jmir1/aniyomi#761]
### Steps to reproduce

1. Download an episode from any source.
2. Select the episode and click "Play Externally".

### Expected behavior

Episode should start playing in external player (VLC in my case).

### Actual behavior

App crashes immediately.

### Crash logs

[aniyomi_crash_logs.txt](https://github.com/jmir1/aniyomi/files/9537277/aniyomi_crash_logs.txt)

### Aniyomi version

App version: 0.12.3.8 (standard, dc8d1af, 72, 2022-08-25T23:30Z)

### Android version

Android 12

### Device

Samsung Galaxy M32

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/jmir1/aniyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://aniyomi.jmir.xyz/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.12.3.8](https://github.com/jmir1/aniyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by 12ohit** [comment]
Settings -> Downloads -> Download location -> Custom location and then select the same location(i.e. /storage/emulated/0/Aniyomi/downloads) but make sure you select it with custom location

**Comment by Grafcube** [comment]
> Settings -> Downloads -> Download location -> Custom location and then select the same location(i.e. /storage/emulated/0/Aniyomi/downloads) but make sure you select it with custom location

Thanks. This solves the problem for me. I'm not I should close the issue though since it should probably work with the default option.

**Comment by 12ohit** [comment]
Don't worry it's already been fixed, you can test it out in beta app https://github.com/jmir1/aniyomi-mpv-beta/releases/latest

**Comment by Grafcube** [comment]
Oh I see. Closing as completed then. Thanks.
