### ISSUE TITLE
Choose server from Aniyomi manually

### ISSUE THREAD

**Issue by edmxn** [jmir1/aniyomi#768]
### Describe your suggested feature

In this case the website has several servers. The player chose MixDrop. MixDrop gave error even in WebView, but the hqq.tv server was working and loaded the episode correctly on the web, it would be better if they gave the option to choose a server from the player or before opening the video

### Other details

Even if the qualities can be chosen in the extension settings, the servers are not chosen (obviously)

I have no idea if there is something similar already existing, if so please tell me

![Screenshot_20220914-214622_Aniyomi](https://user-images.githubusercontent.com/101371218/190310188-d1d08528-e5c8-48cb-aaee-f82b3714a488.jpg)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/jmir1/aniyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.12.3.8](https://github.com/jmir1/aniyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by Samfun75** [comment]
Beta Player

![Screenshot_20220915-101459_Aniyomi](https://user-images.githubusercontent.com/38332931/190340981-24b2bca9-7dce-4dd9-86ec-64d60b37e13f.jpg)
![Screenshot_20220915-101426_Aniyomi](https://user-images.githubusercontent.com/38332931/190340972-2ce57bcd-de69-42ec-9fe8-aec36664f8d4.jpg)

Stable Player

![Screenshot_20220915-101528_Aniyomi](https://user-images.githubusercontent.com/38332931/190341407-680d1cc5-9ea8-4f88-8f5e-b74656b1e3be.jpg)
![Screenshot_20220915-101536_Aniyomi](https://user-images.githubusercontent.com/38332931/190341420-4a9beb82-2980-47bc-8703-74778b05d1fa.jpg)

**Comment by Samfun75** [comment]
> Well, maybe it depends on the web, because in AnimeNinja (esp) the servers do not appear in quality options. The same and there are other extensions that have this problem so it is better that they take it as a general problem

If that's the case then this issue doesn't belong in this repo open it at the extensions repo with detailed information like a list of extensions with the missing server names and other relevant information.
