### ISSUE TITLE
Extension users sort

### ISSUE THREAD

**Issue by Lukyzzz** [jmir1/aniyomi#776]
### Describe your suggested feature

I think it could be really useful to be able to see how many people are currently using each extension, letting new users know right away which extensions are more popular.
It could help people that lost their favorite extension due being obsolete and don't quite know which expression it should migrate to.

### Other details

Really, there's too much manga extension, it would be good to be able to just tap on a "Sort by : Most popular" and download the top 3 or something.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/jmir1/aniyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.12.3.8](https://github.com/jmir1/aniyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by Samfun75** [comment]
This is already ruled out as it puts stress on the extensions sources of the popular extensions. Join the discord server if you want to find out more.

**Comment by Lukyzzz** [comment]
> This is already ruled out as it puts stress on the extensions sources of the popular extensions. Join the discord server if you want to find out more.

Figure it could be the case, but hoped it wasn't.
