### ISSUE TITLE
Turkish subtitle

### ISSUE THREAD

**Issue by chrxllo** [jmir1/aniyomi#786]
### Describe your suggested feature

please add turkish extensions for turks

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/jmir1/aniyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.12.3.8](https://github.com/jmir1/aniyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by 12ohit** [comment]
Close this issue and open it here: https://github.com/jmir1/aniyomi-extensions/issues/new?assignees=&labels=Source+request&template=request_source.yml

**Comment by kyoyacchi** [comment]
Kaynaklar desteklemediği sürece imkansız. Üstteki kişinin de dediği gibi bu "issue"yi kapatıp verdiği linkten "source request" (kaynak isteği) yapmanı öneririm.

**Comment by chrxllo** [comment]
F
