### ISSUE TITLE
The next or previous button is not working

### ISSUE THREAD

**Issue by nAbArA187** [jmir1/aniyomi#79]
The next or previous button is not working

**Comment by jmir1** [comment]
@deadeyeskun your comment has literally nothing to do with this issue

**Comment by nAbArA187** [comment]
Hi. extension was 4anime.to, app version is 0.11.1.7-3703, anime black
clover

**Comment by ty-coon** [comment]
@nAbArA187 if your app is crashing after tapping next episode button, then dump your crash logs.... As its been fixed in new updates, now its next and previous button works fine.

**Comment by ty-coon** [comment]
Right 4anime.to source next and previous button not working i checked it.

**Comment by nAbArA187** [comment]
Great thanks will update once i got home. Thank you
