### ISSUE TITLE
SuperStrem Extension Subtitle Support For Movies & Shows

### ISSUE THREAD

**Issue by MukeshBauri** [jmir1/aniyomi#790]
### Describe your suggested feature

When i watch an episode the in built player opens and there are no subtitles in the movie or show that i am watching. Please add subtitle support.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/jmir1/aniyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.12.3.8](https://github.com/jmir1/aniyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by Samfun75** [comment]
Are you using [beta](https://github.com/jmir1/aniyomi-mpv-beta/releases/latest)?

**Comment by MukeshBauri** [comment]
> 

Using latest stable version it's Doesn't support SRT Subtitles it supports Subtitles which is embedded in the video like in Anime.

**Comment by MukeshBauri** [comment]
Thanks for the kind reply! ;)
