### ISSUE TITLE
[Feature Request] A button to mark watched anime episode as unwatched 

### ISSUE THREAD

**Issue by goyalparth** [jmir1/aniyomi#80]
## Why/User Benefit/User Problem
(explain why this feature should be added)
A button should be added so that the animes that have been marked watches can be marked unwatched again. 

## What/Requirements
(explain how this feature would behave)
So after clicking this button the episode that has been watched by the user can be marked unwatched.

**Comment by ty-coon** [comment]
Its already in the app, to mark episode watched and unmark watched episode, as well u can mark episodes in bulk by tapping mark below episodes.

**Comment by ty-coon** [comment]
![IMG_20210620_113339](https://user-images.githubusercontent.com/83224209/122663906-6c3da180-d1bb-11eb-839b-3529519973b9.jpg)
