### ISSUE TITLE
All Anime Sources slow

### ISSUE THREAD

**Issue by KalebSchmidlkofer** [jmir1/aniyomi#805]
### Steps to reproduce

1. Download Any Source
2. Open up the source
3. It takes about 5 minutes to load the names then another 5 minutes to load the cover art for all the items in view

### Expected behavior

The anime source opens up and shows me anime to download and or add to my library within a minute or two

### Actual behavior

I open up the source and it takes about 5 minutes to give me the name another 5 minutes to load cover art for only items in view then if you click on one another 5 minutes to  load that pages content

### Aniyomi version

0.12.3.8

### Android version

Android 11

### Device

Samsung Galaxy A11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/jmir1/aniyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://aniyomi.jmir.xyz/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.12.3.8](https://github.com/jmir1/aniyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by KalebSchmidlkofer** [comment]
Im not sure if this is an issue with the extensions

**Comment by sinnghabhay80** [comment]
I think this is an issue with your internet connection speed and not the extension/app.

**Comment by KalebSchmidlkofer** [comment]
My Interenet speed is ok im getting 75 mb/s on a day to day basis

**Comment by KalebSchmidlkofer** [comment]
Nothing I have done has fixed it but its fine
