### ISSUE TITLE
document.selector(episodeLink Selector()).first() must not be null

### ISSUE THREAD

**Issue by sohamchatterjee08092002** [jmir1/aniyomi#81]
## Device information
* Tachiyomi version: 0.11.1.7
* Android version: 11
* Device: Redmi Note 9 Pro (MIUI 12.0.5)

I tried to download anime from gogoanime, tenshi.moe and 4anime.to extensions

### Expected behavior
The animes should be downloaded without any error

### Actual behavior
For gogoanime and temshi.moe it is showing

`document.selector(episodeLinkSelector()).first() must not be null`

 And for 4anime.to it is showing that download atarted bur actually it is not downloading.

**Comment by jmir1** [comment]
already fixed in the preview.
