### ISSUE TITLE
Sflix extension [Couldn't find any video links]

### ISSUE THREAD

**Issue by HaZe5657** [jmir1/aniyomi#829]
### Steps to reproduce

1. Play any of the movies or TV shows.

### Expected behavior

Short buffer proceeded by playback of video.

### Actual behavior

Buffers for a while and then closes out the video. Gives an error/pop-up message that says "Couldn't find any video links."
![Screenshot_20221116-110011](https://user-images.githubusercontent.com/85792795/202091860-c5f64951-af78-477d-b04f-8a707318374e.png)

I use the 1.0.0.1 cloudflare DNS, because otherwise, sflix, vidstream, and some other extensions to name a few, don't work. 
Viewing the sflix site under Webview says that it's been blocked under an IT act, I live in India.
![Screenshot_20221116-110558](https://user-images.githubusercontent.com/85792795/202092649-ec5f549b-ce8e-438e-beb5-9dbe735a3a4c.png)
Viewing the sflix.to site under chrome, it comes up normally.

I had experienced this issue before, but then the sflix extension recieved an update and the problem was resolved.

### Aniyomi version

App version: 0.12.3.8 (standard, dc8d1af, 72, 2022-08-25T23:30Z)

### Android version

Android version: 11 (SDK 30) Android build ID: ROQ31.166-63

### Device

Device brand: motorola Device manufacturer: motorola Device name: cyprus64 Device model: moto e40 Device product name: cyprus64

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/jmir1/aniyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://aniyomi.jmir.xyz/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.12.3.8](https://github.com/jmir1/aniyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by HaZe5657** [comment]
[Forgot to add] PS:The sflix.to site comes up normally if I search it up on chrome, with the DNS turned on of course.

**Comment by 12ohit** [comment]
> If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/jmir1/aniyomi-extensions/issues/new/choose).
