### ISSUE TITLE
[Bug] Downloaded anime cannot be viewed through default video player

### ISSUE THREAD

**Issue by EnglishPatchFanatic** [jmir1/aniyomi#83]
I am currently on the latest build

https://github.com/jmir1/aniyomi/releases/tag/v0.11.1.7

And without downloading any episode, streaming the video player can run it without any problem.

However, if you download an episode then watch it through aniyomi the app says the video can't be played.

I'm using Samsung A11 Android 11 and I am using the default video player not another external video player.

**Comment by jmir1** [comment]
from what source and what episode are you trying to play?

**Comment by EnglishPatchFanatic** [comment]
It's the Gogoanime source and I tried this with two different series: Oremonogatari and Kumo desuga nani ka?

Note: The downloaded videos can be played throuvh the file manager but not on the app itself.
