### ISSUE TITLE
Superstream extension: Error when Searching

### ISSUE THREAD

**Issue by WanderingReaper** [jmir1/aniyomi#835]
### Steps to reproduce

When we try to search for a movie/show in the "Superstream extension" it shows a JSON error message. 

### Expected behavior

Earlier it showed the search results normally.

### Actual behavior

The following Error shows up:

 "Unexpected JSON token at offset 45: Expected start of the array '[', but had ':' instead JSON Input: ..... ":" search sever error ","data": {"content"."<html>\r\n<head><.....

### Aniyomi version

0.12.3.8

### Android version

Android 12

### Device

Samsung A72

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/jmir1/aniyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://aniyomi.jmir.xyz/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.12.3.8](https://github.com/jmir1/aniyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by WanderingReaper** [comment]
Fixed automatically.

**Comment by PrashantNath** [comment]
nope its still give error
