### ISSUE TITLE
Remove some references to Tachiyomi that cause confusion

### ISSUE THREAD

**Issue by CarlosEsco** [jmir1/aniyomi#85]
Nice fork you have here.  I was wondering if you could change the following so the main app gets less issues, and questions in our discord about you app.

- [x] Remove Tachiyomi website from the about section
- [x] Fix wording for Issue Template "Feature request Suggest a feature to improve Tachiyomi"
- [x] Remove Issue template " Extension/source/catalogue issue Do not open an issue here. See https://github.com/tachiyomiorg/tachiyomi-extensions" 
- [x] Add a template for opening anime specific exetension issues and point it to your repo
- [x] Fix wording for Issue Template " Official Tachiyomi extensions GitHub repository Issues about a Manga extension/source/catalogue should be opened here instead."

This one doesn't cause confusion but more seems like it isn't needed on your readme (since it wouldn't effect strings specific to your app)
- [ ] Remove the translated badge

**Comment by jmir1** [comment]
again, sorry about all the misguided people who open issues in the wrong repos.
i already removed most of the old tachiyomi-specific links in-app.
i'll change the issue templates as well, thanks for pointing it out.

**Comment by CarlosEsco** [comment]
No worries.  I think the main culprit is the website, since people click that then end up back at our discord.
![image](https://user-images.githubusercontent.com/2092019/122768995-28f23a00-d272-11eb-972b-8b4f356d0e17.png)

**Comment by jmir1** [comment]
oh, shoot, i missed that one. fixed now.
