### ISSUE TITLE
Animixplay not working

### ISSUE THREAD

**Issue by itzswagking** [jmir1/aniyomi#859]
### Steps to reproduce

1. Go to animixplay
2. Click on any anime 
3. Does not start the video 
4. Shows "expected start of object '{' ,but had 'EOF' instead. JSON input:page not found back home"

### Expected behavior

The video should play 

### Actual behavior

It is not playing and showing the error mentioned above 

### Aniyomi version

0.12.3.8

### Android version

Android 13

### Device

Samsung s20 fe 5g

### Other details

> 
![Screenshot_20221226_090005_Aniyomi](https://user-images.githubusercontent.com/121341738/209496380-f180c688-7abf-4915-afc0-6beb2f15d50e.jpg)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/jmir1/aniyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://aniyomi.jmir.xyz/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.12.3.8](https://github.com/jmir1/aniyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by bcolflesh** [comment]
Animixplay closed permanently, per their website: https://animixplay.to/

**Comment by itzswagking** [comment]
Ohh ok i ll make sure to pull a request for an alternative because animixplay was quick and the downloads were fast in it too
