### ISSUE TITLE
[Feature Request] <myanimelist/anilist anime import>

### ISSUE THREAD

**Issue by Peckchamp14** [jmir1/aniyomi#86]
why?:
it should be added because someone have hundreds of animes in their list and dont have the time to import them all
how?:
it should work by logging into the tracker eg mal or anilist then press a import button which will then import the animes,it will create a "watching" category for animes thats listed as watching,"completed" for completed animes  and "on hold"and"dropped" categories and put the animes in their respective category

**Comment by jmir1** [comment]
duplicate #25

**Comment by LittleFreak** [comment]
Is there a way to reconsider this feature?
MAL emphasize even the use of the new API.
@jmir1
