### ISSUE TITLE
SuperStream not working

### ISSUE THREAD

**Issue by itzswagking** [jmir1/aniyomi#860]
### Steps to reproduce

1. Go to browse
2. Go to the extension Superstream
3. Shows error 

### Expected behavior

It should show the movies and web series and should not give error while playing

### Actual behavior

It showed error as soon as you open the extension of superstream in the browse area

### Aniyomi version

0.12.3.8

### Android version

Android 13

### Device

Samsung s20 fe 5g

### Other details

![Screenshot_20221226_090620_Aniyomi](https://user-images.githubusercontent.com/121341738/209496612-615c3fbb-5472-406f-b8c8-f9664b207118.jpg)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/jmir1/aniyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://aniyomi.jmir.xyz/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.12.3.8](https://github.com/jmir1/aniyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by itzswagking** [comment]
This issue is fixed.

**Comment by uieonru** [comment]
issuation
