### ISSUE TITLE
[Feature request] Toggle option to disable swipe to forward on the player

### ISSUE THREAD

**Issue by Palloxin** [jmir1/aniyomi#981]
### Describe your suggested feature

A toggle option in the settings to turn off the swipe feature on the video ( move forward or backward on the player) I can't even clean the screen since the video will 'move' (not sure of term). The double tap is enough to quickly move. 

### Other details

This swipe:

https://user-images.githubusercontent.com/75091899/235014938-2c85d59d-387a-4301-a09e-eaadc7b8d152.mp4

A way to disable it woukd be awesome. You could say "click the lock icon" but i woukd like to keep the rest 'on' especially the double tap to move forward or backward, i don't need the swipe method and its presence is a burden.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/jmir1/aniyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.12.3.10](https://github.com/jmir1/aniyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by Secozzi** [comment]
Click the three dots in the top right, scroll down and disable "Enable horizontal seek gesture"

**Comment by Palloxin** [comment]
Oh thank you, i wrote "swipe" and i didn't find the option
